from pathlib import Path
import datetime,hashlib,json,subprocess,sys
O=Path(__file__).resolve().parent;B=O.parent;R=B/'m62-public-safe-oct02';HEAD='bf5d2df4e7ee5156993169cdd9610fa014bdae4f'
def sha(v):return hashlib.sha256(v).hexdigest()
def put(n,x):(O/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
def gh(n,*args):
 assert not (O/(n+'-receipt.json')).exists();put(n+'-command.json',{'argv':['gh',*args],'started_utc':datetime.datetime.now(datetime.timezone.utc).isoformat()});x=subprocess.run(['gh',*args],capture_output=True);(O/(n+'.stdout')).write_bytes(x.stdout);(O/(n+'.stderr')).write_bytes(x.stderr);put(n+'-receipt.json',{'actual_exit':x.returncode,'stdout_bytes':len(x.stdout),'stdout_sha256':sha(x.stdout),'stderr_bytes':len(x.stderr),'stderr_sha256':sha(x.stderr),'finished_utc':datetime.datetime.now(datetime.timezone.utc).isoformat()});assert x.returncode==0,(n,x.returncode);return json.loads(x.stdout)
i=gh('issue-before','api','repos/kl3574/Learning_Workbench/issues/32');p=gh('pr-before','api','repos/kl3574/Learning_Workbench/pulls/56');br=gh('branch-before','api','repos/kl3574/Learning_Workbench/branches/feat%2FM6.3-local-control-bootstrap')
assert sha(i['body'].encode())=='c7d19cf771272e4e5435e01115af45a5acdd7941fff4115485a87679bc31e544' and sha(p['body'].encode())=='e88210de731a3c647ab9a8a75bd57cf36c33de748ea663c260777d3fdd4297e4';assert p['head']['sha']==br['commit']['sha']==HEAD and p['draft'] and p['state']=='open' and p['merged_at'] is None
assert subprocess.run(['git','rev-parse','HEAD'],cwd=R,capture_output=True,check=True).stdout.decode().strip()==HEAD
assert sha((R/'PRODUCT_DESIGN.md').read_bytes())=='b140764e416dac644b45ed8c0b6bd1c71eb9b578cb3b5b19d2530a94cea4cfec'
begin,end='<!-- engineering_progress:start -->','<!-- engineering_progress:end -->';assert i['body'].count(begin)==i['body'].count(end)==1
prefix=i['body'].split(begin)[0];suffix=i['body'].split(end)[1];shared=i['body'].split(begin)[1].split(end)[0].strip()
def change(a,b):
 global shared
 assert shared.count(a)==1,a[:90];shared=shared.replace(a,b)
change('当前公开分支与草稿 PR56 已实际回读为 `079a008cf88b37e4517cb391503a1e7393ccf374`，1561 工程输入。运行源码锚点为 `d78c4d159a2831f7d5e1721a9a466ec5b3e66421`；079 的后续变更为进度证据及三个确切归档规则。原用户 b895 检出保留；没有 GitHub merge、release 或部署。','当前公开分支与草稿 PR56 已实际回读为 `bf5d2df4e7ee5156993169cdd9610fa014bdae4f`，1564工程输入；GitHub tree与本地commit tree一致。正常commit/push均实际0，首次PR head未同步的原readback保留，随后只读回验成功、没有第二次push，具体首读差异原因未确立。完整本地门禁固定源码锚点为101cee47，发布版本只另加确切归档属性与进度；其余1563工程输入相同。原用户b895检出和唯一规范保留；没有GitHub merge、release或部署。079及其原失败属于明确历史证据。')
change('四项规范内修复已正常合入本地 `101cee47d8e746dddac81fb6e8829069fcabff09`，1564工程输入；尚未推送。','四项规范内修复已正常合入本地 `101cee47d8e746dddac81fb6e8829069fcabff09`，1564工程输入，现已随公开bf5d2df正常推送。')
change('另有两条确切的不可变证据空白归档规则，不改运行语义。','101本身另有两条确切归档规则；完整门禁后本次追加11个确切归档文件规则，不改运行语义。')
change('已独立审阅仅匹配10个确切progress归档文件的规则','已独立审阅仅匹配11个确切progress归档文件的规则')
change('仅10归档路径改变','仅11归档路径改变')
change('新的暂存默认空白检查与发布扫描尚待实际执行。','两次原暂存空白检查exit2保留（第二次为原diff归档本身的Vite尾空格）；后续原默认暂存检查实际0、原全tracked发布扫描实际0/23933文件，暂存树前后相同。扫描不能替代独立有限来源审核。活动进度残留RUNNING字段已纠正，原状态保存为previous/history；最终额外staged scope独审尚待收件，不冒称其最终通过。')
change('下一任务：完成终态证据和有限来源审核、正常暂存提交检查，再正常推送已审阅源码并等待新原CI。公开分支仍079，本地101加确切归档规则尚未推送。原两CI已结束，没有 rerun、cancel 或 dispatch。','新公开bf5d的原CI已实际出现：[push37657156244](https://github.com/kl3574/Learning_Workbench/actions/runs/37657156244)和[PR37657163285](https://github.com/kl3574/Learning_Workbench/actions/runs/37657163285)，均attempt1/in_progress，终态与各测试计数尚未知，不沿用旧计数。下一任务是回读新原job的真实终态与来源，并继续生产完整InputProof/runtime工程。原079两CI终态FAIL继续保留，没有rerun、cancel或dispatch。')
body=prefix+begin+'\n'+shared+'\n'+end+suffix;prbody='受控turn、逐操作审批和产物回导已按唯一规范持续实施。四项已审阅修复及固定101完整门禁证据已正常推送bf5d2df；本地Python4587P/2数值环境跳过与浏览器133P分别限定，新原CI运行中。生产Agent仍未验收。\n\n'+shared+'\nRefs #32\n'
sys.path.insert(0,str(R/'scripts'));from check_publication import inspect;from progress import read_state,save
assert not inspect('progress/issue-body.md',body.encode()) and not inspect('progress/pr-body.md',prbody.encode())
for n,v in [('issue',body),('pr',prbody)]:(O/(n+'-body.md')).write_text(v);put(n+'-patch.json',{'body':v})
gh('issue-write','api','--method','PATCH','repos/kl3574/Learning_Workbench/issues/32','--input',str(O/'issue-patch.json'));ia=gh('issue-after','api','repos/kl3574/Learning_Workbench/issues/32');assert ia['body']==body and {k:i[k] for k in ['number','title','state','labels','milestone','assignees']}=={k:ia[k] for k in ['number','title','state','labels','milestone','assignees']};assert ia['body'].split(begin)[0]==prefix and ia['body'].split(end)[1]==suffix
gh('pr-write','api','--method','PATCH','repos/kl3574/Learning_Workbench/pulls/56','--input',str(O/'pr-patch.json'));pa=gh('pr-after','api','repos/kl3574/Learning_Workbench/pulls/56');assert pa['body']==prbody and pa['head']['sha']==HEAD and pa['draft'] and pa['state']=='open' and pa['merged_at'] is None and pa['title']==p['title'] and pa['base']['sha']==p['base']['sha']
record={'recorded_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'public_head':HEAD,'issue_body_sha256':sha(body.encode()),'pr_body_sha256':sha(prbody.encode()),'scope':'Issue32managedregionanddraftPR56bodyonly;metadatauntouched','draft_open_unmerged':True,'actual_commit_push_exit':[0,0],'current_CI':'Neworiginalpush37657156244/PR37657163285 attempt1 observedin_progress;countsNOT_YET_KNOWN','old079_CI':'BothFAILretained','local_gate_anchor':'101cee47d8e746dddac81fb6e8829069fcabff09','physical_numeric':'2BLOCKED_ENVIRONMENTskips/no fallback','real_model_calls':0,'merge_release_deploy':False,'M6_3':'NOT_ACCEPTED','M7':'NOT_UNLOCKED'};put('READBACK.json',record)
s=read_state();t=next(x for x in s['tasks'] if x['id']=='M6.3');previous=t['current_public_ci'];t['previous_public079_ci_snapshot']=previous;t['current_public_ci']=json.loads((B/'m63-current101-normal-push-pure-readback-continuation-oct07/FIRST-ACTUAL-CI-SNAPSHOT.json').read_bytes());t['publication_head']=HEAD;t['documentary_publication_head']=HEAD;t['source_publication_status']='ACTUAL_NORMAL_PUSH_BF5D_EXACT_BRANCH_DRAFTPR_TREE_NEW_ORIGINAL_CI_RUNNING_NOT_ACCEPTED';t['last_issue_body_sha256']=record['issue_body_sha256'];t['last_pr_body_sha256']=record['pr_body_sha256'];t['last_issue_readback_at']=record['recorded_utc'];s['last_pr_body_sha256']=record['pr_body_sha256'];s['checkpoint']['publication_head']=HEAD;s['verification']['m6_3_publicbf_actual_sourcepush_managed_sync']=record;s['verification']['ci']='Publicbf5d originalpush37657156244 andPR37657163285 attempt1 actualin_progress; no terminalcounts inferred. Old079push5S1integrationFAIL/PR4S2FAIL retained; notwholeM63.';s['task_sync']='ACTUAL_ISSUE32_DRAFTPR56_PUBLICBF5D_NORMAL_PUSH_NEW_ORIGINAL_CI_RUNNING';s['task_sync_readback_at']=record['recorded_utc'];t['next_action']='公开bf5d已正常推送、branch/PR/tree只读一致；原push37657156244与PR37657163285已运行，继续回读原jobs真实终态，不rerun/cancel/dispatch。固定101本地4587P/2数值ENVskip/3warn和133nativeP已封存；11确切归档规则与23933发布扫描实际0，旧079失败与静态HOME偏差保留。生产完整InputProof/runtime仍缺，零实际平台模型请求；M6.3/AC21未验收，M7todo。';s['next_action']=t['next_action'];s['checkpoint']['next_action']=t['next_action'];save(s)
print('Actual Issue32/PR56 currentbf sourcepush+originalCI readback synced; no new source push by this script.')
