import type { SessionResponse } from '../../../../../packages/contracts/generated/api-types'
import type { CodexTurnControlView, GenericApprovalView, GenericApprovalDecisionAck } from '../../../../../packages/contracts/generated/codex-turn-types'
export const approvalWorkspace = 'workspace_approval_synthetic', approvalActor = 'actor_approval_synthetic'
export const approvalSession = (): SessionResponse => ({ workspace_id: approvalWorkspace, actor_session_id: approvalActor, role: 'author', csrf_token: 'synthetic-local-csrf', active_independent_attempt_id: null, active_open_book_attempt_id: null })
export const approvalView = (): GenericApprovalView => ({ id: 'approval_synthetic', revision: 1, actor_session_id: approvalActor, session_id: 'codex_session_synthetic', turn_id: 'turn_approval_synthetic', run_id: 'job_approval_synthetic', job: { id: 'job_approval_synthetic', status: 'running' }, job_revision: 8,
 operation: { kind: 'command', command_text: '{"text":"合成 α\\n","version":"codex-synthetic-literal-command-v1"}', cwd: 'turn_outputs', executable_sha256: '1'.repeat(64), environment_sha256: '2'.repeat(64), read_files: [], writable_area: 'turn_outputs', filesystem_scope_sha256: '3'.repeat(64), network: 'denied', operation_profile_sha256: '4'.repeat(64) }, operation_sha256: '5'.repeat(64),
 created_at: '2026-10-05T00:00:00Z', expires_at: '2099-10-05T00:00:00Z', decision: 'pending', validity: 'current', execution: 'not_started', decided_at: null, started_at: null, finished_at: null, result_sha256: null, error_code: null })
export const approvalControl = (): CodexTurnControlView => ({ id: 'turn_approval_synthetic', session_id: 'codex_session_synthetic', actor_session_id: approvalActor, job: { id: 'job_approval_synthetic', status: 'running' }, job_revision: 8, run_revision: 2, last_seq: 4, cancel_requested: false, execution: 'active', outcome: null, approval_ids: ['approval_synthetic'], approval_controls: [{ id: 'approval_synthetic', revision: 1, operation_sha256: '5'.repeat(64), decision: 'pending', validity: 'current' }], consent_control: null, manifest_id: null, created_at: '2026-10-05T00:00:00Z', started_at: '2026-10-05T00:00:01Z', finished_at: null, error_code: null })
export const approvalAck = (decision: 'approve_once' | 'decline' = 'approve_once', actor = approvalActor): GenericApprovalDecisionAck => ({ id: 'approval_synthetic', revision: 2, actor_session_id: actor, operation_sha256: '5'.repeat(64), decision, applied: true, session_id: 'codex_session_synthetic', turn_id: 'turn_approval_synthetic', run_id: 'job_approval_synthetic', job: { id: 'job_approval_synthetic', status: 'running' } })
