-- PRODUCT_DESIGN v3.0.0 storage contract. SQLite JSON1 + FTS5 required.
-- These tables are a persistence design, not a running service or complete access-control system.
PRAGMA foreign_keys=ON;
CREATE TABLE schema_migrations(version TEXT PRIMARY KEY, applied_at TEXT NOT NULL, checksum TEXT NOT NULL);
CREATE TABLE workspace(id TEXT PRIMARY KEY,title TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>=1),preferences_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(preferences_json)),created_at TEXT NOT NULL);
CREATE TABLE bootstrap_codes(code_hash TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),expires_at TEXT NOT NULL,used_at TEXT);
CREATE TABLE local_sessions(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),token_hash TEXT NOT NULL UNIQUE,csrf_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('learner','author')),expires_at TEXT NOT NULL,revoked_at TEXT);
CREATE TABLE content_blobs(sha256 TEXT PRIMARY KEY CHECK(length(sha256)=64),relative_path TEXT NOT NULL UNIQUE,size INTEGER NOT NULL CHECK(size>=0),created_at TEXT NOT NULL);
CREATE TABLE sources(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),blob_sha256 TEXT REFERENCES content_blobs(sha256),media_type TEXT NOT NULL,title TEXT NOT NULL,rights TEXT NOT NULL,parser_version TEXT,metadata_json TEXT NOT NULL CHECK(json_valid(metadata_json)),created_at TEXT NOT NULL);
CREATE TABLE objects(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),kind TEXT NOT NULL CHECK(kind IN ('course','lesson','block','concept','route','question','practice_set','assessment','note')),current_revision INTEGER CHECK(current_revision>=1),lifecycle TEXT NOT NULL DEFAULT 'active' CHECK(lifecycle IN ('active','archived')));
CREATE TABLE revisions(object_id TEXT NOT NULL REFERENCES objects(id),revision INTEGER NOT NULL CHECK(revision>=1),sha256 TEXT NOT NULL CHECK(length(sha256)=64),metadata_json TEXT NOT NULL CHECK(json_valid(metadata_json)),status TEXT NOT NULL DEFAULT 'published' CHECK(status='published'),created_at TEXT NOT NULL,PRIMARY KEY(object_id,revision),UNIQUE(object_id,revision,sha256));
CREATE TRIGGER revisions_no_update BEFORE UPDATE ON revisions BEGIN SELECT RAISE(ABORT,'published revision immutable'); END;
CREATE TRIGGER new_object_no_current BEFORE INSERT ON objects WHEN NEW.current_revision IS NOT NULL BEGIN SELECT RAISE(ABORT,'create object with null pointer before first published revision'); END;
CREATE TRIGGER valid_current_revision BEFORE UPDATE OF current_revision ON objects WHEN NEW.current_revision IS NOT NULL AND NOT EXISTS(SELECT 1 FROM revisions WHERE object_id=NEW.id AND revision=NEW.current_revision) BEGIN SELECT RAISE(ABORT,'current pointer must reference own published revision'); END;
CREATE TABLE object_dependencies(owner_id TEXT NOT NULL,owner_revision INTEGER NOT NULL,target_id TEXT NOT NULL,target_revision INTEGER NOT NULL,relation TEXT NOT NULL,PRIMARY KEY(owner_id,owner_revision,target_id,target_revision,relation),FOREIGN KEY(owner_id,owner_revision) REFERENCES revisions(object_id,revision),FOREIGN KEY(target_id,target_revision) REFERENCES revisions(object_id,revision));
CREATE TABLE block_bodies(block_id TEXT NOT NULL,block_revision INTEGER NOT NULL,body_sha256 TEXT NOT NULL REFERENCES content_blobs(sha256),PRIMARY KEY(block_id,block_revision),FOREIGN KEY(block_id,block_revision) REFERENCES revisions(object_id,revision));
CREATE TABLE concept_edges(course_id TEXT NOT NULL,course_revision INTEGER NOT NULL,prerequisite_id TEXT NOT NULL REFERENCES objects(id),dependent_id TEXT NOT NULL REFERENCES objects(id),CHECK(prerequisite_id<>dependent_id),PRIMARY KEY(course_id,course_revision,prerequisite_id,dependent_id),FOREIGN KEY(course_id,course_revision) REFERENCES revisions(object_id,revision));
CREATE TABLE route_steps(route_id TEXT NOT NULL,route_revision INTEGER NOT NULL,step_id TEXT NOT NULL,position INTEGER NOT NULL CHECK(position>=0),target_id TEXT NOT NULL,target_revision INTEGER NOT NULL,requires_json TEXT NOT NULL CHECK(json_valid(requires_json)),PRIMARY KEY(route_id,route_revision,step_id),UNIQUE(route_id,route_revision,position),FOREIGN KEY(route_id,route_revision) REFERENCES revisions(object_id,revision),FOREIGN KEY(target_id,target_revision) REFERENCES revisions(object_id,revision));
CREATE TABLE drafts(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),kind TEXT NOT NULL,revision INTEGER NOT NULL CHECK(revision>=1),base_ref_json TEXT CHECK(base_ref_json IS NULL OR json_valid(base_ref_json)),candidate_json TEXT NOT NULL CHECK(json_valid(candidate_json)),candidate_sha256 TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('draft','in_review','approved','needs_changes','published','cancelled')),updated_at TEXT NOT NULL);
CREATE TABLE reviews(id TEXT PRIMARY KEY,draft_id TEXT NOT NULL REFERENCES drafts(id),draft_revision INTEGER NOT NULL,candidate_sha256 TEXT NOT NULL,revision INTEGER NOT NULL CHECK(revision>=1),receipt_json TEXT NOT NULL CHECK(json_valid(receipt_json)),reviewer_session_id TEXT REFERENCES local_sessions(id),created_at TEXT NOT NULL);
CREATE TABLE solutions(question_id TEXT NOT NULL,question_revision INTEGER NOT NULL,solution_revision INTEGER NOT NULL CHECK(solution_revision>=1),private_json TEXT NOT NULL CHECK(json_valid(private_json)),sha256 TEXT NOT NULL,review_status TEXT NOT NULL CHECK(review_status IN ('draft','needs_review','approved')),PRIMARY KEY(question_id,question_revision,solution_revision),FOREIGN KEY(question_id,question_revision) REFERENCES revisions(object_id,revision));
CREATE TRIGGER solution_no_update BEFORE UPDATE ON solutions BEGIN SELECT RAISE(ABORT,'create new solution revision'); END;
CREATE TABLE practice_sessions(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),practice_id TEXT NOT NULL,practice_revision INTEGER NOT NULL,question_refs_json TEXT NOT NULL CHECK(json_valid(question_refs_json)),solution_refs_json TEXT NOT NULL CHECK(json_valid(solution_refs_json)),status TEXT NOT NULL CHECK(status IN ('active','submitted','abandoned')),revision INTEGER NOT NULL CHECK(revision>=1),created_at TEXT NOT NULL,FOREIGN KEY(practice_id,practice_revision) REFERENCES revisions(object_id,revision));
CREATE TABLE practice_responses(session_id TEXT NOT NULL REFERENCES practice_sessions(id),question_id TEXT NOT NULL,answer_json TEXT NOT NULL CHECK(json_valid(answer_json)),updated_at TEXT NOT NULL,PRIMARY KEY(session_id,question_id));
CREATE TABLE attempts(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),assessment_id TEXT NOT NULL,assessment_revision INTEGER NOT NULL,mode TEXT NOT NULL CHECK(mode IN ('independent','assisted','open_book')),policy_json TEXT NOT NULL CHECK(json_valid(policy_json)),question_refs_json TEXT NOT NULL CHECK(json_valid(question_refs_json)),solution_refs_private_json TEXT NOT NULL CHECK(json_valid(solution_refs_private_json)),status TEXT NOT NULL CHECK(status IN ('active','submitted','grading','graded','needs_review','abandoned')),revision INTEGER NOT NULL CHECK(revision>=1),created_at TEXT NOT NULL,deadline_at TEXT,submitted_at TEXT,submit_reason TEXT CHECK(submit_reason IN ('user','deadline') OR submit_reason IS NULL),submitted_responses_json TEXT CHECK(submitted_responses_json IS NULL OR json_valid(submitted_responses_json)),FOREIGN KEY(assessment_id,assessment_revision) REFERENCES revisions(object_id,revision));
CREATE UNIQUE INDEX one_active_independent ON attempts(workspace_id) WHERE mode='independent' AND status='active';
CREATE TRIGGER immutable_attempt_policy BEFORE UPDATE OF mode,policy_json,question_refs_json,solution_refs_private_json,deadline_at ON attempts WHEN OLD.mode<>NEW.mode OR OLD.policy_json<>NEW.policy_json OR OLD.question_refs_json<>NEW.question_refs_json OR OLD.solution_refs_private_json<>NEW.solution_refs_private_json OR OLD.deadline_at IS NOT NEW.deadline_at BEGIN SELECT RAISE(ABORT,'assigned questions solutions and policy immutable'); END;
CREATE TRIGGER immutable_submission BEFORE UPDATE OF submitted_responses_json,submitted_at ON attempts WHEN OLD.status<>'active' AND (OLD.submitted_responses_json IS NOT NEW.submitted_responses_json OR OLD.submitted_at IS NOT NEW.submitted_at) BEGIN SELECT RAISE(ABORT,'submitted answers immutable'); END;
CREATE TABLE responses(attempt_id TEXT NOT NULL REFERENCES attempts(id),question_id TEXT NOT NULL,draft_revision INTEGER NOT NULL CHECK(draft_revision>=1),answer_json TEXT NOT NULL CHECK(json_valid(answer_json)),updated_at TEXT NOT NULL,PRIMARY KEY(attempt_id,question_id));
CREATE TRIGGER response_insert_only_active BEFORE INSERT ON responses WHEN NOT EXISTS(SELECT 1 FROM attempts WHERE id=NEW.attempt_id AND status='active') BEGIN SELECT RAISE(ABORT,'attempt not active'); END;
CREATE TRIGGER response_update_only_active BEFORE UPDATE ON responses WHEN NOT EXISTS(SELECT 1 FROM attempts WHERE id=OLD.attempt_id AND status='active') BEGIN SELECT RAISE(ABORT,'attempt not active'); END;
CREATE TABLE grades(attempt_id TEXT NOT NULL REFERENCES attempts(id),grading_revision INTEGER NOT NULL CHECK(grading_revision>=1),result_json TEXT NOT NULL CHECK(json_valid(result_json)),created_at TEXT NOT NULL,PRIMARY KEY(attempt_id,grading_revision));
CREATE TRIGGER grade_no_update BEFORE UPDATE ON grades BEGIN SELECT RAISE(ABORT,'create new grading revision'); END;
CREATE TABLE learning_events(event_id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),kind TEXT NOT NULL,origin TEXT NOT NULL CHECK(origin IN ('native','user_supplied_import')),payload_json TEXT NOT NULL CHECK(json_valid(payload_json)),occurred_at TEXT NOT NULL);
CREATE TRIGGER event_no_update BEFORE UPDATE ON learning_events BEGIN SELECT RAISE(ABORT,'events append-only in normal operations'); END;
CREATE TABLE exposures(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),event_id TEXT NOT NULL UNIQUE REFERENCES learning_events(event_id),exposure_group TEXT NOT NULL,question_ref_json TEXT NOT NULL CHECK(json_valid(question_ref_json)),kind TEXT NOT NULL CHECK(kind IN ('hint','solution','prior_attempt','imported_claim')),occurred_at TEXT NOT NULL);
CREATE INDEX exposure_lookup ON exposures(workspace_id,exposure_group,occurred_at);
CREATE TABLE evidence(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),event_id TEXT NOT NULL REFERENCES learning_events(event_id),attempt_id TEXT REFERENCES attempts(id),grading_revision INTEGER,evidence_json TEXT NOT NULL CHECK(json_valid(evidence_json)),freshness TEXT NOT NULL,UNIQUE(event_id,id),FOREIGN KEY(attempt_id,grading_revision) REFERENCES grades(attempt_id,grading_revision));
CREATE TABLE learning_progress(workspace_id TEXT PRIMARY KEY REFERENCES workspace(id),revision INTEGER NOT NULL CHECK(revision>=1),projection_json TEXT NOT NULL CHECK(json_valid(projection_json)),last_event_id TEXT REFERENCES learning_events(event_id));
CREATE TABLE learner_profiles(workspace_id TEXT PRIMARY KEY REFERENCES workspace(id),revision INTEGER NOT NULL CHECK(revision>=1),profile_json TEXT NOT NULL CHECK(json_valid(profile_json)),updated_at TEXT NOT NULL);
CREATE TABLE notes_index(note_id TEXT NOT NULL,note_revision INTEGER NOT NULL,workspace_id TEXT NOT NULL REFERENCES workspace(id),anchor_id TEXT NOT NULL,anchor_revision INTEGER NOT NULL,anchor_state TEXT NOT NULL CHECK(anchor_state IN ('exact','stale','unresolved')),PRIMARY KEY(note_id,note_revision),FOREIGN KEY(note_id,note_revision) REFERENCES revisions(object_id,revision),FOREIGN KEY(anchor_id,anchor_revision) REFERENCES revisions(object_id,revision));
CREATE TABLE recommendations(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),rule_version TEXT NOT NULL,snapshot_json TEXT NOT NULL CHECK(json_valid(snapshot_json)),decision TEXT NOT NULL CHECK(decision IN ('pending','accepted','dismissed')),stale INTEGER NOT NULL DEFAULT 0 CHECK(stale IN (0,1)),created_at TEXT NOT NULL);
CREATE TABLE workbench_sessions(workspace_id TEXT PRIMARY KEY REFERENCES workspace(id),revision INTEGER NOT NULL CHECK(revision>=1),session_json TEXT NOT NULL CHECK(json_valid(session_json)),updated_at TEXT NOT NULL);
CREATE TABLE threads(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),scope_json TEXT NOT NULL CHECK(json_valid(scope_json)),title TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE context_snapshots(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),snapshot_sha256 TEXT NOT NULL,envelope_json TEXT NOT NULL CHECK(json_valid(envelope_json)),private_input_blob_sha256 TEXT REFERENCES content_blobs(sha256),created_at TEXT NOT NULL);
CREATE TABLE jobs(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),kind TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('queued','running','awaiting_approval','completed','failed','cancelled')),revision INTEGER NOT NULL CHECK(revision>=1),input_sha256 TEXT NOT NULL,input_json TEXT NOT NULL CHECK(json_valid(input_json)),result_json TEXT CHECK(result_json IS NULL OR json_valid(result_json)),cancel_requested INTEGER NOT NULL DEFAULT 0 CHECK(cancel_requested IN (0,1)),retry_count INTEGER NOT NULL DEFAULT 0 CHECK(retry_count>=0),next_retry_at TEXT,lease_owner TEXT,lease_until TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE runs(id TEXT PRIMARY KEY REFERENCES jobs(id),thread_id TEXT NOT NULL REFERENCES threads(id),context_snapshot_id TEXT REFERENCES context_snapshots(id),snapshot_json TEXT NOT NULL CHECK(json_valid(snapshot_json)));
CREATE TABLE messages(id TEXT PRIMARY KEY,thread_id TEXT NOT NULL REFERENCES threads(id),role TEXT NOT NULL CHECK(role IN ('user','assistant')),context_snapshot_id TEXT REFERENCES context_snapshots(id),run_id TEXT REFERENCES runs(id),content_markdown TEXT NOT NULL,citations_json TEXT NOT NULL CHECK(json_valid(citations_json)),status TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE job_events(job_id TEXT NOT NULL REFERENCES jobs(id),seq INTEGER NOT NULL CHECK(seq>0),type TEXT NOT NULL,payload_json TEXT NOT NULL CHECK(json_valid(payload_json)),occurred_at TEXT NOT NULL,PRIMARY KEY(job_id,seq));
CREATE UNIQUE INDEX one_terminal_per_job ON job_events(job_id) WHERE type IN ('completed','failed','cancelled');
CREATE TABLE provider_configs(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),revision INTEGER NOT NULL CHECK(revision>=1),config_json TEXT NOT NULL CHECK(json_valid(config_json)),secret_store_locator TEXT,updated_at TEXT NOT NULL);
CREATE TABLE consents(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),provider_id TEXT NOT NULL REFERENCES provider_configs(id),revision INTEGER NOT NULL CHECK(revision>=1),scope_json TEXT NOT NULL CHECK(json_valid(scope_json)),status TEXT NOT NULL CHECK(status IN ('active','revoked','expired')),expires_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE approvals(id TEXT PRIMARY KEY,job_id TEXT NOT NULL REFERENCES jobs(id),revision INTEGER NOT NULL CHECK(revision>=1),operation_sha256 TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('pending','approved','declined','expired')),scope_json TEXT NOT NULL CHECK(json_valid(scope_json)),actor_session_id TEXT REFERENCES local_sessions(id),expires_at TEXT NOT NULL);
CREATE TABLE usage_records(id TEXT PRIMARY KEY,job_id TEXT NOT NULL REFERENCES jobs(id),provider_id TEXT NOT NULL REFERENCES provider_configs(id),input_tokens INTEGER CHECK(input_tokens>=0),output_tokens INTEGER CHECK(output_tokens>=0),search_count INTEGER NOT NULL DEFAULT 0 CHECK(search_count>=0),estimated_cost TEXT,actual_cost TEXT,currency TEXT,created_at TEXT NOT NULL);
CREATE TABLE ingestion_imports(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),source_id TEXT NOT NULL REFERENCES sources(id),job_id TEXT NOT NULL REFERENCES jobs(id),input_sha256 TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('staged','parsing','preview_ready','committed','cancelled','failed')),preview_json TEXT CHECK(preview_json IS NULL OR json_valid(preview_json)),created_at TEXT NOT NULL);
CREATE TABLE artifacts(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),job_id TEXT REFERENCES jobs(id),blob_sha256 TEXT NOT NULL REFERENCES content_blobs(sha256),profile TEXT NOT NULL,manifest_json TEXT NOT NULL CHECK(json_valid(manifest_json)),visibility TEXT NOT NULL CHECK(visibility IN ('learner','author_private','personal_private')),created_at TEXT NOT NULL);
CREATE TABLE proposals(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),kind TEXT NOT NULL,operation_sha256 TEXT NOT NULL,revision INTEGER NOT NULL CHECK(revision>=1),proposal_json TEXT NOT NULL CHECK(json_valid(proposal_json)),status TEXT NOT NULL CHECK(status IN ('preview','approved','applied','cancelled','failed')),created_at TEXT NOT NULL);
CREATE TABLE codex_sessions(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),revision INTEGER NOT NULL CHECK(revision>=1),sandbox_root_id TEXT NOT NULL,external_thread_id TEXT,adapter_version TEXT NOT NULL,status TEXT NOT NULL,metadata_json TEXT NOT NULL CHECK(json_valid(metadata_json)));
CREATE TABLE connectors(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),config_json TEXT NOT NULL CHECK(json_valid(config_json)),sync_cursor_json TEXT CHECK(sync_cursor_json IS NULL OR json_valid(sync_cursor_json)),last_sync TEXT);
CREATE TABLE feedback(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),payload_json TEXT NOT NULL CHECK(json_valid(payload_json)),created_at TEXT NOT NULL);
CREATE TABLE outbox(id TEXT PRIMARY KEY,event_type TEXT NOT NULL,payload_json TEXT NOT NULL CHECK(json_valid(payload_json)),delivered_at TEXT,attempts INTEGER NOT NULL DEFAULT 0);
CREATE TABLE idempotency(actor TEXT NOT NULL,route TEXT NOT NULL,key TEXT NOT NULL,request_sha256 TEXT NOT NULL,result_json TEXT CHECK(result_json IS NULL OR json_valid(result_json)),created_at TEXT NOT NULL,expires_at TEXT,PRIMARY KEY(actor,route,key));
CREATE TABLE indexes(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),corpus_sha256 TEXT NOT NULL,index_version TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('ready','stale','building','missing')),manifest_json TEXT NOT NULL CHECK(json_valid(manifest_json)),created_at TEXT NOT NULL);
CREATE VIRTUAL TABLE fts_chunks USING fts5(object_id UNINDEXED,revision UNINDEXED,workspace_id UNINDEXED,chunk_id UNINDEXED,tokens,body,tokenize='unicode61');
-- FTS tokens are application-presegmented Chinese; private solutions never enter this table.
-- Courses, lessons, concepts, routes and notes have one canonical metadata source in revisions;
-- projection/index tables must be rebuilt from that source, not become a second editable copy.
-- Application services additionally check workspace ownership, exact hashes, graph acyclicity,
-- reference entity kinds, assigned response question IDs, deadlines, policy, leases and consent.
-- Privacy purge is an explicit maintenance workflow; ordinary API routes cannot mass-delete rows.
