import { useState } from 'react'
import type { ContentRef } from '../../../../../packages/contracts/generated/types'
import type { ConceptStateSource } from '../../../../../packages/contracts/generated/api-types'
import { refKey } from '../reader/target'
import { eligibilityReasons } from '../review/reviewModel'
import { selfLabels } from './ProfileFields'
import { evidenceStateLabels, skillLabels } from './conceptModel'
import { useConceptStates } from './useConceptStates'
import './learning.css'
const applicability = { usable: '当前适用性已核验', pending_review: '当前适用性待核验，保留历史记录', confirmed_stale: '已有明确失效记录' }
const applicabilityReasons: Record<string, string> = { SEMANTIC_DEPENDENCY_REVISION_CHANGED: '题目或概念的语义依赖修订已变化，尚未完成影响核验。', SEMANTIC_DEPENDENCY_NOT_ACTIVE: '语义依赖当前不可用，尚未完成影响核验。', EXACT_CONTENT_CHANGE_PENDING: '存在命中精确依赖的待处理内容变更。' }
function Ref({ value }: { value: ContentRef }) { return <code className="learning-ref">{value.entity} · {value.id} · r{value.revision}<br />SHA-256 {value.sha256}</code> }
function Source({ source, input }: { source: ConceptStateSource; input: boolean }) { const evidence = source.evidence; return <details className="learning-source"><summary>{input ? '用于当前规则窗口' : '历史来源记录'} · 评分版本 {source.grading_revision} · {evidence.score == null ? '分数为空' : `归一题分 ${evidence.score} / 1`}</summary><p>原提交时间：<time dateTime={source.submitted_at}>{source.submitted_at}</time>。重新评分不算新的学习样本。</p><p>{evidence.eligible ? '历史资格：符合独立证据条件' : '历史资格：保留记录，不纳入独立证据'}；{applicability[source.applicability.status]}。</p><p>{evidence.independence === 'independent' ? '本次独立模式记录' : evidence.independence === 'assisted' ? '允许辅助的模式记录，不表示实际求助' : '独立性尚未确认'}；{evidence.freshness === 'novel' ? '历史记录支持此前未见' : evidence.freshness === 'repeated' ? '此前已见，不当作首次未见' : '此前是否见过尚未确认'}。</p><ul>{source.reason_codes.map(code => <li key={code}>{eligibilityReasons[code]}</li>)}{source.applicability.reason_codes.map(code => <li key={code}>{applicabilityReasons[code] ?? `来源返回的待核验原因：${code}`}</li>)}</ul><dl><dt>证据 / 事件</dt><dd><code>{evidence.id}<br />{evidence.event_id}</code></dd><dt>作答实例 / 同源题组</dt><dd><code>{source.attempt_id}<br />{source.exposure_group}</code></dd><dt>测试</dt><dd><Ref value={source.assessment_ref} /></dd><dt>题目</dt><dd><Ref value={source.question_ref} /></dd><dt>概念</dt><dd><Ref value={source.concept_ref} /></dd></dl><details><summary>已核验的精确语义依赖</summary>{source.applicability.checked_refs.map(ref => <p key={refKey(ref)}><Ref value={ref} /></p>)}</details></details> }
export function ConceptStates({ workspace, paused, course, version = 0 }: { workspace: string; paused: boolean; course: ContentRef | null; version?: number }) {
  const [limited, setLimited] = useState(false), data = useConceptStates(workspace, paused, limited ? course?.id : undefined, version), value = data.value
  if (paused) return <p>当前学习策略尚未核验或限制此内容。概念与证据暂不显示。</p>
  return <section className="learning-panel" aria-label="概念与技能证据"><p>这里展示可解释的记录状态。自报、课程阅读、练习参与和独立作答分列；不是掌握概率，也不代表认证掌握。</p><div className="learning-actions"><label className="learning-check"><input type="checkbox" checked={limited} disabled={!course} onChange={event => setLimited(event.target.checked)} />只看所选课程身份的全部历史修订</label><button onClick={data.refresh}>刷新概念状态</button></div>{data.loading && <p role="status">正在读取精确概念与证据…</p>}{data.error && <p role="alert">{data.error}</p>}{value && <><details><summary>核对本次完整课程与概念范围</summary><p>当前范围包含 {value.course_refs.length} 个精确课程修订、{value.concepts.length} 个精确概念修订；不会把不同修订拼成一个测试归属。</p>{value.course_refs.map(ref => <p key={refKey(ref)}><Ref value={ref} /></p>)}{value.concepts.map(item => <p key={refKey(item.ref)}>{item.title} · r{item.ref.revision} · {item.skill_dimensions.map(skill => skillLabels[skill]).join('、') || '未声明技能维度'}<br /><Ref value={item.ref} /></p>)}</details><p>规则：learning-state-v1，未校准。窗口最多采用最近 3 个不同同源题组；至少 2 次测试、3 组均满分才称“多条一致记录”。有实际失分显示“需要巩固”。</p>{!value.concepts.length && <p>尚无真实概念。可以先导入教材；未生成占位能力或分数。</p>}{value.concepts.length > 0 && !value.items.length && <p>概念目录已保留，但没有已声明或实际记录的技能维度，尚未诊断。</p>}
      {value.items.map(row => <section key={`${refKey(row.concept_ref)}:${row.skill}`} className="concept-state" aria-label={`${row.title} r${row.concept_ref.revision} · ${skillLabels[row.skill]}`}><h3>{row.title} · r{row.concept_ref.revision} · {skillLabels[row.skill]}</h3><strong>{evidenceStateLabels[row.evidence_state]}</strong><p>{row.self_report ? `用户自报：${selfLabels[row.self_report.level]}（${row.self_report.updated_at}）` : '尚未自报'}；课程是否已读请查看教材阅读记录，不由阅读推出本概念能力。</p><dl className="concept-counts"><div><dt>当前独立证据</dt><dd>{row.independent_count} 题次</dd></div><div><dt>允许辅助的模式记录</dt><dd>{row.assisted_count} 题次</dd></div><div><dt>重复 / 独立性或此前是否见过尚未知</dt><dd>{row.repeated_count} / {row.unknown_count} 题次</dd></div><div><dt>分数为空</dt><dd>{row.null_count} 题次</dd></div><div><dt>适用性待核验 / 确认过期</dt><dd>{row.pending_review_count} / {row.stale_count} 题次</dd></div><div><dt>练习提交</dt><dd>{row.practice_submission_count} 次会话</dd></div><div><dt>提示 / 解答</dt><dd>{row.hint_count} / {row.solution_count} 次事件</dd></div></dl><p className="learning-muted">题次、会话和事件分别计数；排除分类可能重叠，不相加为能力总分。</p><details><summary>查看此概念技能的原始来源（{row.sources.length} 条证据）</summary><Ref value={row.concept_ref} />{row.sources.length ? row.sources.map(source => <Source key={source.evidence.id} source={source} input={row.state_input_evidence_ids.includes(source.evidence.id)} />) : <p>没有可展示的独立评分来源，不制造证据。</p>}{row.practice_submission_sources.map(item => <details key={item.event_id}><summary>练习参与 · {item.submitted_at}</summary><Ref value={item.target_ref} /><p>会话 {item.source_id} · 事件 {item.event_id}</p><p>只证明参与，不授予掌握证据。</p></details>)}{[...row.hint_sources, ...row.solution_sources].map(item => <details key={item.event_id}><summary>{item.kind === 'hint_revealed' ? '提示' : '解答'}事件 · {item.occurred_at}</summary><Ref value={item.question_ref} /><p>练习会话 {item.practice_session_id} · 事件 {item.event_id}</p></details>)}</details></section>)}
    </>}</section>
}
