import { expect, test } from 'vitest'
import type { ConceptState, ConceptStateResponse } from '../../../../../packages/contracts/generated/api-types'
import { conceptChoices, validateConceptStates } from './conceptModel'
const concept = { entity: 'concept' as const, id: 'concept_original', revision: 1, sha256: 'a'.repeat(64) }
const scope = (): ConceptStateResponse => ({ concepts: [{ ref: concept, title: '原创概念', skill_dimensions: [] }, { ref: { ...concept, revision: 2, sha256: 'b'.repeat(64) }, title: '原创概念新修订', skill_dimensions: [] }], course_refs: [], items: [] })
const row = (): ConceptState => ({ concept_id: concept.id, concept_ref: concept, title: '原创概念', skill: 'compute', evidence_state: 'none', independent_count: 0, assisted_count: 0, stale_count: 0, repeated_count: 0, unknown_count: 0, null_count: 1, pending_review_count: 0, self_report: null, evidence_ids: ['evidence_original'], state_input_evidence_ids: [], sources: [{ evidence: { id: 'evidence_original', event_id: 'event_original', concept_id: concept.id, skill: 'compute', eligible: false, score: null, independence: 'independent', freshness: 'novel', reason: '参考未审' }, question_ref: { entity: 'question', id: 'question_original', revision: 1, sha256: 'c'.repeat(64) }, concept_ref: concept, assessment_ref: { entity: 'assessment', id: 'assessment_original', revision: 1, sha256: 'd'.repeat(64) }, attempt_id: 'attempt_original', grading_revision: 1, submitted_at: '2026-09-15T00:00:00Z', exposure_group: 'group_original', qualification_basis: 'submission_frozen', reason_codes: ['ANSWER_UNREVIEWED', 'GRADE_UNRESOLVED'], applicability: { status: 'usable', reason_codes: [], checked_refs: [concept] } }], practice_submission_count: 0, practice_submission_sources: [], hint_count: 0, hint_sources: [], solution_count: 0, solution_sources: [] })
test('the complete concept directory offers self-report choices even without skill rows and deduplicates concept identity only', () => { const value = scope(); expect(validateConceptStates(value)).toBe(value); expect(value.concepts).toHaveLength(2); expect(conceptChoices(value)).toEqual([{ id: concept.id, title: '原创概念' }]); expect(value.items).toEqual([]) })
test('original null and excluded evidence remains inspectable but cannot become current state input', () => { const value = scope(); value.items = [row()]; expect(validateConceptStates(value).items[0].sources[0].evidence.score).toBeNull(); value.items[0].state_input_evidence_ids.push('evidence_original'); expect(() => validateConceptStates(value)).toThrow('尚未获准') })
test('same concept id with a different revision or skill never satisfies a precise source binding', () => { const value = scope(); value.items = [row()]; value.items[0].sources[0].concept_ref = value.concepts[1].ref; expect(() => validateConceptStates(value)).toThrow('不匹配'); value.items = [row()]; value.items[0].sources[0].evidence.skill = 'derive'; expect(() => validateConceptStates(value)).toThrow('不匹配') })
test('participation count cannot invent a session when its actual source list is empty', () => { const value = scope(); value.items = [row()]; value.items[0].practice_submission_count = 1; expect(() => validateConceptStates(value)).toThrow('参与来源') })
