import { expect, test } from 'vitest'
import type { LearnerProfile } from '../../../../../packages/contracts/generated/types'
import { decodeProfileDraft, editProfileDraft, newProfileDraft, profileDirty } from './profileDrafts'
const profile: LearnerProfile = { workspace_id: 'workspace_profile', revision: 1, goals: [], goal_concept_ids: [], weekly_minutes: 120, language: 'zh-CN', preferred_difficulty: 'beginner', self_assessments: [] }
const decode = (value: unknown) => decodeProfileDraft(JSON.stringify(value), profile.workspace_id)
test('unconfirmed profile input preserves the true original basis and command across disk decoding', () => { const original = newProfileDraft(profile), edited = editProfileDraft(original, { ...original.fields, goals: ['理解 🧠é'], weekly_minutes: '' }); expect(profileDirty(original)).toBe(false); expect(profileDirty(edited)).toBe(true); expect(decode(edited)).toEqual(edited); expect(edited.base).toEqual(profile); expect(edited.command_id).not.toBe(original.command_id); expect(decode(edited).command_id).toBe(edited.command_id) })
test('server receipt must be a matching next revision and editing after it starts from the acknowledged basis', () => { const original = newProfileDraft(profile), value = editProfileDraft(original, { ...original.fields, goals: ['原创目标'] }), saved = { ...profile, revision: 2, goals: ['原创目标'] }; value.acknowledged = saved; expect(profileDirty(decode(value))).toBe(false); const next = editProfileDraft(value, { ...value.fields, language: 'en' }); expect(next.base).toEqual(saved); expect(next.command_id).not.toBe(value.command_id); expect(next.acknowledged).toBeNull(); expect(() => decode({ ...value, acknowledged: { ...saved, goals: ['另一命令'] } })).toThrow(); expect(() => decode({ ...value, acknowledged: { ...saved, revision: 4 } })).toThrow() })
test('workspace changes and imported origin/extra secret fields cannot be treated as valid profile cache', () => { const original = newProfileDraft(profile); expect(() => decode({ ...original, workspace_id: 'another_workspace' })).toThrow(); expect(() => decode({ ...original, secret: 'unexpected' })).toThrow(); expect(() => decode({ ...original, base: { ...profile, self_assessments: [{ concept_id: 'concept_one', level: 'independent_use', origin: 'server_grade', updated_at: '2026-09-14T00:00:00Z' }] } })).toThrow() })
test('self report is a concept identity once, never one assertion per revision', () => { const value = newProfileDraft(profile); value.fields.self_assessments = [{ concept_id: 'concept_one', level: 'encountered' }, { concept_id: 'concept_one', level: 'independent_use' }]; expect(() => decode(value)).toThrow(); value.fields.self_assessments.pop(); expect(decode(value).fields.self_assessments).toEqual([{ concept_id: 'concept_one', level: 'encountered' }]); expect(() => decode({ ...value, fields: { ...value.fields, self_assessments: [{ ...value.fields.self_assessments[0], revision: 2 }] } })).toThrow() })
