import type { LearnerProfile } from '../../../../../packages/contracts/generated/types'
import { profileFields, type ProfileFields as Fields } from './profileDrafts'
export type ConceptChoice = { id: string; title: string }
export const selfLabels = { not_learned: '未学', encountered: '接触过', independent_use: '能独立使用' }
const difficultyLabels = { beginner: '基础', intermediate: '进阶', advanced: '深入' }
export function ProfileFields({ value, concepts, disabled, change }: { value: Fields; concepts: ConceptChoice[]; disabled: boolean; change: (value: Fields) => void }) {
  const all = [...concepts, ...[...new Set([...value.goal_concept_ids, ...value.self_assessments.map(item => item.concept_id)])].filter(id => !concepts.some(item => item.id === id)).map(id => ({ id, title: `${id}（当前目录不可读，原选择保留）` }))]
  return <fieldset disabled={disabled} className="profile-fields"><legend>学习目标与自报基础</legend><label>学习目标（每行一项）<textarea aria-label="学习目标" rows={3} value={value.goals.join('\n')} onChange={event => change({ ...value, goals: event.target.value ? event.target.value.split('\n') : [] })} /></label><div className="learning-form-row"><label>每周可投入分钟数<input aria-label="每周学习分钟数" inputMode="numeric" value={value.weekly_minutes} onChange={event => change({ ...value, weekly_minutes: event.target.value })} /></label><label>学习语言<input aria-label="学习语言" value={value.language} onChange={event => change({ ...value, language: event.target.value })} /></label><label>偏好难度<select aria-label="偏好难度" value={value.preferred_difficulty} onChange={event => change({ ...value, preferred_difficulty: event.target.value as Fields['preferred_difficulty'] })}>{Object.entries(difficultyLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label></div>
    <p>以下概念来自当前工作区真实可读目录。同一概念的不同修订共用一项自报；自报不等于测试成绩。</p>{all.length ? all.map(item => <div key={item.id} className="profile-concept"><label className="learning-check"><input type="checkbox" checked={value.goal_concept_ids.includes(item.id)} onChange={event => change({ ...value, goal_concept_ids: event.target.checked ? [...value.goal_concept_ids, item.id] : value.goal_concept_ids.filter(id => id !== item.id) })} />目标概念：{item.title}</label><label>自报基础：{item.title}<select aria-label={`自报基础：${item.title}`} value={value.self_assessments.find(row => row.concept_id === item.id)?.level ?? ''} onChange={event => { const retained = value.self_assessments.filter(row => row.concept_id !== item.id); change({ ...value, self_assessments: event.target.value ? [...retained, { concept_id: item.id, level: event.target.value as Fields['self_assessments'][number]['level'] }] : retained }) }}><option value="">尚未自报 / 删除当前自报</option>{Object.entries(selfLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label></div>) : <p>尚无可选概念。可以先填写自由学习目标，再导入自己的教材。</p>}
  </fieldset>
}
function Facts({ value }: { value: Fields }) { return <dl><dt>目标</dt><dd>{value.goals.join('；') || '未填写'}</dd><dt>目标概念</dt><dd>{value.goal_concept_ids.join('、') || '未选择'}</dd><dt>每周时间</dt><dd>{value.weekly_minutes || '尚未填完'} 分钟</dd><dt>语言 / 难度</dt><dd>{value.language} / {difficultyLabels[value.preferred_difficulty]}</dd><dt>自报</dt><dd>{value.self_assessments.map(item => `${item.concept_id}：${selfLabels[item.level]}`).join('；') || '未自报'}</dd></dl> }
export function ProfileComparison({ base, local, remote }: { base: LearnerProfile; local: Fields; remote: LearnerProfile | null }) { return <section aria-label="画像三方比较" className="learning-comparison"><h3>比较原基准、本页与服务端画像</h3><div><section><h4>原基准 · 修订 {base.revision}</h4><Facts value={profileFields(base)} /></section><section><h4>本页候选</h4><Facts value={local} /></section><section><h4>服务端{remote ? ` · 修订 ${remote.revision}` : ' · 尚未知'}</h4>{remote ? <Facts value={profileFields(remote)} /> : <p>尚未成功读回，请保留本页输入并重新读取。</p>}</section></div></section> }
