import { writeFileSync } from 'node:fs'
import { expect, test } from '../../apps/web/node_modules/@playwright/test/index.mjs'
import type { AuthoringDraftView, AuthoringJobPage, AuthoringJobView, ConsentProposalView, NumericCheckView } from '../../packages/contracts/generated/api-types'
import { AuthoringRuntime } from './authoringRuntime'
import { role, configure, prepare, preview, numericPreview, screenshot } from './authoringTestData'

test('actual Authoring preparation diagnoses missing proof without dispatch and learner can recover safe cancellation', async ({ playwright }, info) => {
  test.setTimeout(90_000)
  const runtime = await AuthoringRuntime.start('no_proof')
  try {
    const context = await runtime.openBrowser(playwright.chromium), page = context.pages()[0]
    await runtime.authenticateOnly(page); await role(page, runtime.origin, 'author'); await configure(page, runtime)
    expect(runtime.control().proof_registered).toBe(false)
    const { dialog, ack, original } = await prepare(page)
    expect(runtime.control().received_request_count).toBe(0)
    const rejected = await preview(page, dialog)
    expect(rejected.status()).toBe(409); expect((await rejected.json()).error.code).toBe('CAPABILITY_UNSUPPORTED')
    const unchanged: AuthoringJobView = await page.request.get(`/api/v1/authoring/jobs/${ack.id}`).then(v => v.json())
    expect(unchanged.consent_id).toBeNull(); expect(unchanged.proposal_id).toBeNull(); expect(unchanged.raw_answer).toBeNull()
    await role(page, runtime.origin, 'learner')
    await page.getByRole('button', { name: '创作', exact: true }).click()
    await expect(dialog.getByLabel('例题主题', { exact: true })).toHaveCount(0)
    await expect(dialog.getByRole('region', { name: '受保护创作详情', exact: true })).toHaveCount(0)
    const cancelling = page.waitForResponse(v => v.request().method() === 'POST' && v.url().endsWith(`/api/v1/jobs/${ack.id}/cancel`))
    await dialog.getByRole('button', { name: `明确取消任务 ${ack.id}`, exact: true }).click()
    expect((await cancelling).status()).toBe(200)
    await expect(dialog.getByText(new RegExp(`^${ack.id} · cancelled · r`))).toBeVisible()
    const final: AuthoringJobPage = await page.request.get('/api/v1/authoring/jobs').then(v => v.json())
    expect(final.items).toHaveLength(1); expect(final.items[0].status).toBe('cancelled')
    expect(final.items[0].result_refs).toEqual([]); expect(final.items[0].warnings).toEqual([])
    expect(JSON.stringify(final)).not.toContain(original.request.topic)
    expect(runtime.control().received_request_count).toBe(0)
    writeFileSync(info.outputPath('actual-authoring-no-proof.json'), JSON.stringify({ scope: 'Real local HTTP/SQLite/worker/browser. Production-style empty proof registry; original synthetic provider configuration only. Preview rejected, zero dispatch, learner safe cancellation. No model or numeric result.', prepared: original, no_proposal: unchanged, safe_final: final, runtime: runtime.control() }, null, 2))
  } finally { await runtime.close() }
})

test('explicit same-Job loopback grant creates a draft and numeric preview needs its own decision', async ({ playwright }, info) => {
  test.setTimeout(120_000)
  const runtime = await AuthoringRuntime.start('complete'), errors: string[] = []
  try {
    const context = await runtime.openBrowser(playwright.chromium), page = context.pages()[0]
    page.on('pageerror', error => errors.push(error.message))
    await runtime.authenticateOnly(page); await role(page, runtime.origin, 'author'); await configure(page, runtime)
    let prepares = 0
    page.on('request', value => { if (value.method() === 'POST' && value.url().endsWith('/api/v1/authoring/jobs')) prepares++ })
    const { dialog, ack } = await prepare(page)
    expect(runtime.control().proof_registered).toBe(true); expect(runtime.control().received_request_count).toBe(0)
    const previewResponse = await preview(page, dialog); expect(previewResponse.status()).toBe(201)
    const proposal: ConsentProposalView = await previewResponse.json()
    expect(proposal.summary.job_id).toBe(ack.id); expect(proposal.summary.purpose).toBe('authoring')
    expect(runtime.control().received_request_count).toBe(0)
    await dialog.getByLabel('我已核对本次例题的冻结范围、提供商、预算与到期时间', { exact: true }).check()
    await dialog.getByRole('button', { name: '准备批准例题模型调用', exact: true }).click()
    const granting = page.waitForResponse(v => v.request().method() === 'POST' && v.url().endsWith('/api/v1/consents'))
    await dialog.getByRole('button', { name: '确认发送批准授权', exact: true }).click()
    expect((await granting).status()).toBe(201)
    let current!: AuthoringJobView
    await expect.poll(async () => { current = await page.request.get(`/api/v1/authoring/jobs/${ack.id}`).then(v => v.json()); return current.summary.status }, { timeout: 10_000 }).toBe('completed')
    await dialog.getByRole('button', { name: '重新读取本次创作任务', exact: true }).click()
    await dialog.getByRole('button', { name: '读取这份准确例题候选', exact: true }).click()
    const candidate = current.summary.candidate; expect(candidate).not.toBeNull()
    const draft: AuthoringDraftView = await page.request.get(`/api/v1/authoring/drafts/${candidate!.draft_id}`).then(v => v.json())
    expect(draft.state).toBe('draft'); expect(draft.base_ref).toBeNull(); expect(draft.numeric_check_ids).toEqual([])
    expect(current.raw_answer).toBe(runtime.control().answer_markdown)
    await expect(dialog.getByLabel('完整候选正文', { exact: true })).toHaveText(draft.payload.body_markdown)
    expect(draft.validation.mathematical).toBe('NOT_RUN'); expect(draft.validation.independent_pedagogy).toBe('NOT_RUN')
    const rejectedPreview = await numericPreview(page, dialog, candidate!.draft_id)
    expect((await page.request.get('/api/v1/authoring/jobs').then(v => v.json()) as AuthoringJobPage).items).toHaveLength(1)
    const declining = page.waitForResponse(v => v.request().method() === 'POST' && v.url().endsWith(`/api/v1/authoring/numeric-checks/${rejectedPreview.id}/decision`))
    await dialog.getByRole('button', { name: '明确拒绝本次数值执行', exact: true }).click()
    const declinedAck = await declining; expect(declinedAck.status()).toBe(200); expect((await declinedAck.json()).job).toBeNull()
    await dialog.getByRole('button', { name: '另行读取数值检查当前状态', exact: true }).click()
    await expect(dialog.getByText('当前决定：decline · r2', { exact: true })).toBeVisible()
    const approvedPreview = await numericPreview(page, dialog, candidate!.draft_id)
    await dialog.getByLabel('我已核对全部变量、表达式、容差、候选与本机隔离范围，单独批准这一次执行', { exact: true }).check()
    const approving = page.waitForResponse(v => v.request().method() === 'POST' && v.url().endsWith(`/api/v1/authoring/numeric-checks/${approvedPreview.id}/decision`))
    await dialog.getByRole('button', { name: '明确批准本次数值执行', exact: true }).click()
    const approvedAck = await approving; expect(approvedAck.status()).toBe(202)
    const numericAck = await approvedAck.json(); expect(numericAck.job).not.toBeNull()
    let numeric!: NumericCheckView
    await expect.poll(async () => { numeric = await page.request.get(`/api/v1/authoring/numeric-checks/${approvedPreview.id}`).then(v => v.json()); return numeric.result !== null }, { timeout: 15_000 }).toBe(true)
    expect(['passed', 'environment_unavailable']).toContain(numeric.result!.outcome)
    expect(numeric.result!.verdict).toBe(numeric.result!.outcome === 'passed' ? 'PASS' : 'BLOCKED')
    await dialog.getByRole('button', { name: '另行读取数值检查当前状态', exact: true }).click()
    await expect(dialog.getByRole('heading', { name: `实际数值结果：${numeric.result!.verdict}`, exact: true })).toBeVisible()
    const finalDraft: AuthoringDraftView = await page.request.get(`/api/v1/authoring/drafts/${candidate!.draft_id}`).then(v => v.json())
    expect(finalDraft.candidate).toEqual(draft.candidate); expect(finalDraft.state).toBe('draft')
    expect(finalDraft.payload).toEqual(draft.payload); expect(finalDraft.numeric_check_ids).toEqual([rejectedPreview.id, approvedPreview.id])
    writeFileSync(info.outputPath('actual-authoring-execution-before-layout.json'), JSON.stringify({ scope: 'Actual authoring and numeric HTTP/worker results before viewport and role checks; subsequent test outcome is separate.', completed: current, draft: finalDraft, declined_preview: rejectedPreview, approved_preview: approvedPreview, actual_numeric: numeric, runtime: runtime.control() }, null, 2))
    const wide = await screenshot(page, dialog, 1440, dialog.getByLabel('完整候选正文', { exact: true }), 'authoring-candidate-1440.png', info)
    const narrow = await screenshot(page, dialog, 390, dialog.getByLabel('完整候选正文', { exact: true }), 'authoring-candidate-390.png', info)
    await screenshot(page, dialog, 390, dialog.getByRole('region', { name: '实际数值结果', exact: true }), 'authoring-actual-numeric-390.png', info)
    await expect.poll(() => runtime.control().validated_request_count).toBe(1)
    expect(runtime.control().received_request_count).toBe(1); expect(runtime.control().invalid_request_count).toBe(0); expect(prepares).toBe(1)
    await role(page, runtime.origin, 'learner')
    await page.locator('.command-trigger').click()
    await page.getByRole('dialog', { name: '命令面板', exact: true }).getByRole('button', { name: /^创作/ }).click()
    const control = dialog.getByRole('region', { name: '创作任务安全控制', exact: true })
    await expect(control.getByText('例题候选生成任务', { exact: true })).toBeVisible()
    await expect(control.getByText('独立数值检查任务', { exact: true })).toBeVisible()
    await expect(control.getByRole('button', { name: `明确取消任务 ${numericAck.job.id}`, exact: true })).toBeDisabled()
    await expect(dialog.getByLabel('完整候选正文', { exact: true })).toHaveCount(0)
    await expect(dialog.getByRole('region', { name: '独立数值执行批准', exact: true })).toHaveCount(0)
    const safe: AuthoringJobPage = await page.request.get('/api/v1/authoring/jobs').then(v => v.json())
    expect(new Set(safe.items.map(v => v.kind))).toEqual(new Set(['authoring', 'authoring_numeric_check']))
    expect(JSON.stringify(safe)).not.toContain(candidate!.draft_id); expect(JSON.stringify(safe)).not.toContain(approvedPreview.id)
    expect(errors).toEqual([])
    writeFileSync(info.outputPath('actual-authoring-loopback.json'), JSON.stringify({ scope: 'Actual test-only loopback full-byte protocol and native UI. One original authoring Job and one actual provider dispatch. Draft remains unpublished and unreviewed. Numeric decline has no Job; separate approve records actual environment verdict, BLOCKED is not arithmetic PASS. Both safe kinds discoverable after real learner role change.', prepares, proposal_id: proposal.id, completed: current, draft: finalDraft, declined_preview: rejectedPreview, approved_preview: approvedPreview, actual_numeric: numeric, safe_controls: safe, runtime: runtime.control(), viewport_bounds: { wide, narrow }, page_errors: errors }, null, 2))
  } finally { await runtime.close() }
})
