import { expect, test } from '../../apps/web/node_modules/@playwright/test/index.mjs'
import { bootstrap } from './helpers'
import { importReaderPackage, originalReaderPackage } from './readerTestData'

test('actual historical block r1/r2 comparison is read-only and remains contained at desktop and narrow widths', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await bootstrap(page)
  const current = originalReaderPackage('nativecompare', 2, true), old = originalReaderPackage('nativecompare', 1)
  const imported = await importReaderPackage(page, current)
  await imported.dialog.getByRole('button', { name: '关闭导入', exact: true }).click()
  await page.goto(`/?reader=${encodeURIComponent(JSON.stringify({ course: current.course, lesson: current.lessons[0], block: current.blocks[0], view: 'lesson' }))}`)
  const block = page.locator(`#block-${current.blocks[0].id}-r2`)
  await expect(block.locator('.reader-markdown')).toContainText('第二修订选文')
  const requests: { method: string; path: string }[] = []
  page.on('request', request => { const path = new URL(request.url()).pathname; if (path.startsWith('/api/v1/')) requests.push({ method: request.method(), path }) })
  const before = await page.request.get('/api/v1/learning/progress').then(response => response.json())
  const panel = block.getByRole('region', { name: '块修订比较', exact: true })
  await panel.getByRole('button', { name: '比较此块的两个修订', exact: true }).click()
  await expect(panel.getByRole('option', { name: /修订 1/ }).first()).toBeAttached()
  await expect(panel.getByRole('button', { name: '读取所选两个修订', exact: true })).toBeDisabled()
  await panel.getByRole('combobox', { name: '左侧修订', exact: true }).selectOption(old.blocks[0].sha256)
  await panel.getByRole('combobox', { name: '右侧修订', exact: true }).selectOption(current.blocks[0].sha256)
  await panel.getByRole('button', { name: '读取所选两个修订', exact: true }).click()
  const left = panel.getByLabel('左侧完整原文', { exact: true }), right = panel.getByLabel('右侧完整原文', { exact: true })
  await expect(left).toHaveText(old.bodies[old.blocks[0].id], { useInnerText: false })
  await expect(right).toHaveText(current.bodies[current.blocks[0].id], { useInnerText: false })
  expect(await left.textContent()).toBe(old.bodies[old.blocks[0].id])
  expect(await right.textContent()).toBe(current.bodies[current.blocks[0].id])
  await expect(panel.getByLabel('逐行文字差异')).toContainText('选文甲')
  await expect(panel.getByLabel('逐行文字差异')).toContainText('第二修订选文')
  await expect(panel).toContainText(old.blocks[0].sha256)
  await expect(panel).toContainText(current.blocks[0].sha256)
  const geometry = async () => panel.evaluate(node => ({ width: node.clientWidth, scroll: node.scrollWidth, readerWidth: node.closest('.reader-scroll')!.clientWidth, readerScroll: node.closest('.reader-scroll')!.scrollWidth }))
  const desktop = await geometry(); expect(desktop.scroll).toBeLessThanOrEqual(desktop.width + 1); expect(desktop.readerScroll).toBeLessThanOrEqual(desktop.readerWidth + 1)
  await panel.screenshot({ path: info.outputPath('block-compare-1440.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  const narrow = await geometry(); expect(narrow.scroll).toBeLessThanOrEqual(narrow.width + 1); expect(narrow.readerScroll).toBeLessThanOrEqual(narrow.readerWidth + 1)
  await panel.getByRole('button', { name: '收起修订比较', exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath('block-compare-controls-390.png') })
  await left.scrollIntoViewIfNeeded()
  expect(await left.evaluate(node => getComputedStyle(node).overflowX)).toBe('auto')
  expect(await left.evaluate(node => node.scrollWidth > node.clientWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('block-compare-original-390.png') })
  await panel.getByRole('button', { name: '收起修订比较', exact: true }).click()
  await panel.getByRole('button', { name: '比较此块的两个修订', exact: true }).click()
  await expect(panel.getByRole('combobox', { name: '左侧修订', exact: true })).toHaveValue(old.blocks[0].sha256)
  await expect(panel.getByRole('combobox', { name: '右侧修订', exact: true })).toHaveValue(current.blocks[0].sha256)
  expect(await page.request.get('/api/v1/learning/progress').then(response => response.json())).toEqual(before)
  const contentReads = requests.filter(request => request.path.includes(`/blocks/${old.blocks[0].id}`) || request.path === `/api/v1/objects/${old.blocks[0].id}/revisions`)
  expect(contentReads.length).toBeGreaterThanOrEqual(5)
  expect(contentReads.every(request => request.method === 'GET')).toBe(true)
  expect(requests.filter(request => request.method !== 'GET' && !request.path.startsWith('/api/v1/workbench/'))).toEqual([])
  await info.attach('comparison-http-readback', { body: JSON.stringify({ old: old.blocks[0], current: current.blocks[0], desktop, narrow, contentReads, learningUnchanged: true }), contentType: 'application/json' })
  expect(errors).toEqual([])
})
