import { expect, test, type Page } from '../../apps/web/node_modules/@playwright/test/index.mjs'
import { bootstrap } from './helpers'
import { importPracticePackage, originalPracticePackage, type PracticePackage } from './practiceTestData'
import type { PracticeSession } from '../../packages/contracts/generated/api-types'
async function openSession(page: Page, prefix: string, profile: PracticePackage['profile'] = 'author') {
  await bootstrap(page)
  const fixture = originalPracticePackage(prefix, profile)
  const imported = await importPracticePackage(page, fixture)
  await imported.dialog.getByRole('button', { name: '关闭导入', exact: true }).click()
  await page.goto(`/?reader=${encodeURIComponent(JSON.stringify({ course: fixture.course, lesson: fixture.lesson }))}`)
  await expect(page.locator('.real-reader > h1')).toBeVisible()
  await page.getByRole('button', { name: '本节习题', exact: true }).click()
  await page.getByRole('dialog', { name: '本节习题', exact: true }).getByRole('button', { name: /五类参考练习/ }).click()
  const creating = page.waitForResponse(value => value.request().method() === 'POST' && value.url().endsWith('/api/v1/practice/sessions'))
  await page.getByRole('button', { name: '开始此练习', exact: true }).click()
  const created = await creating
  expect(created.status()).toBe(201)
  const session: PracticeSession = await created.json()
  await expect(page.getByText('服务端作答已保存', { exact: true })).toBeVisible()
  return { fixture, id: session.id, session }
}
async function read(page: Page, id: string): Promise<PracticeSession> { const response = await page.request.get(`/api/v1/practice/sessions/${id}`); expect(response.status()).toBe(200); return response.json() }
async function question(page: Page, number: number) { await page.getByRole('navigation', { name: '本次练习题目', exact: true }).getByRole('button', { name: new RegExp(`^第 ${number} 题`) }).click() }
async function saved(page: Page) { await expect(page.getByText('服务端作答已保存', { exact: true })).toBeVisible(); await expect(page.getByText('本机草稿存储可用', { exact: true })).toBeVisible() }

test('five real question kinds save and refresh; hints and solutions require explicit exposure; submit is ungraded', async ({ page }, info) => {
  const errors: string[] = [], reveals: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', value => { if (/\/practice\/sessions\/[^/]+\/solutions$/.test(value.url())) reveals.push(value.method()) })
  const { fixture, id } = await openSession(page, 'nativepracticeall')
  await page.getByRole('radio', { name: '5', exact: true }).check()
  await page.getByLabel('第 1 题推导步骤').fill('将两个数量相加。')
  for (const [number, answer] of [[2, '加法交换律'], [3, '0.5 m'], [4, '2 + 3 = 5'], [5, 'x+x']] as const) {
    await question(page, number)
    await page.getByLabel(`第 ${number} 题答案`, { exact: true }).fill(answer)
    await page.getByLabel(`第 ${number} 题推导步骤`, { exact: true }).fill(`原创合成步骤 ${number} 🧠 é`)
  }
  await expect.poll(async () => (await read(page, id)).responses.length).toBe(5)
  await saved(page)
  const before = await read(page, id)
  expect(before.responses.map(item => item.question_id).sort()).toEqual(fixture.questions.map(item => item.id).sort())
  expect(before.results).toBeNull(); expect(before.exposure_event_ids).toEqual([]); expect(before.assisted).toBe(false)
  expect(reveals).toEqual([])
  await page.reload()
  await saved(page)
  await expect(page.getByLabel('第 5 题答案', { exact: true })).toHaveValue('x+x')
  expect(reveals).toEqual([])
  await question(page, 1)
  const hinting = page.waitForResponse(value => value.url().endsWith(`/practice/sessions/${id}/hints`))
  await page.getByRole('button', { name: '获取 2 级规则提示', exact: true }).click()
  expect((await hinting).status()).toBe(200)
  await expect(page.getByRole('heading', { name: '本机规则提示 · 2 级', exact: true })).toBeVisible()
  await saved(page)
  expect((await read(page, id)).assistance[0].highest_hint_level).toBe(2)
  const revealing = page.waitForResponse(value => value.url().endsWith(`/practice/sessions/${id}/solutions`))
  await page.getByRole('button', { name: '明确展开参考解答并记录暴露', exact: true }).click()
  expect((await revealing).status()).toBe(200)
  await expect(page.getByRole('heading', { name: '参考解答 · 需审查', exact: true })).toBeVisible()
  await expect(page.locator('.practice-solution svg').first()).toBeVisible()
  await saved(page)
  expect((await read(page, id)).assistance[0].solution_revealed).toBe(true)
  expect(reveals).toEqual(['POST'])
  await page.locator('.practice-solution').scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath('practice-real-assisted-1440.png') })
  await page.getByRole('button', { name: '收起参考解答', exact: true }).click()
  await page.reload(); await saved(page)
  expect(reveals).toEqual(['POST'])
  await expect(page.getByRole('heading', { name: '参考解答 · 需审查', exact: true })).toHaveCount(0)
  const submitting = page.waitForResponse(value => value.url().endsWith(`/practice/sessions/${id}/submit`))
  await page.getByRole('button', { name: '提交本次练习', exact: true }).click()
  expect((await submitting).status()).toBe(200)
  await expect(page.getByRole('heading', { name: '提交结果', exact: true })).toBeVisible()
  const submitted = await read(page, id)
  expect(submitted.status).toBe('submitted'); expect(submitted.responses).toEqual(before.responses)
  expect(submitted.results).toHaveLength(5)
  for (const result of submitted.results!) { expect(result.status).toBe('needs_review'); expect(result.score).toBeNull(); expect(result.solution_markdown).toBeNull() }
  await expect(page.getByRole('radio', { name: '5', exact: true })).toBeDisabled()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.locator('.practice-scroll').evaluate(node => node.scrollWidth - node.clientWidth)).toBeLessThanOrEqual(1)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.getByRole('heading', { name: '提交结果', exact: true }).scrollIntoViewIfNeeded()
  await expect(page.getByText('未评分 · 分数为空').first()).toBeInViewport()
  await page.screenshot({ path: info.outputPath('practice-real-submitted-390.png') })
  expect(errors).toEqual([])
})

test('offline recovery keeps the local candidate when session GET was also unavailable and reconnect compares its base', async ({ page }) => {
  const { id } = await openSession(page, 'nativepracticeoffline')
  await question(page, 2)
  await page.getByLabel('第 2 题答案', { exact: true }).fill('原基准')
  await saved(page)
  const before = await read(page, id)
  await page.route(`**/api/v1/practice/sessions/${id}/responses`, route => route.abort('internetdisconnected'))
  await page.getByLabel('第 2 题答案', { exact: true }).fill('断网本机候选 🧠')
  await expect(page.getByText('作答尚未确认同步', { exact: true })).toBeVisible()
  await expect(page.getByText('本机草稿存储可用', { exact: true })).toBeVisible()
  await page.route(`**/api/v1/practice/sessions/${id}`, route => route.abort('internetdisconnected'))
  await page.reload()
  await expect(page.getByRole('heading', { name: '发现本机未同步作答', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '恢复这份本机作答', exact: true }).click()
  await expect(page.locator('.practice-content')).toContainText('断网本机候选 🧠')
  await page.unroute(`**/api/v1/practice/sessions/${id}`)
  await page.getByRole('button', { name: '重新读取练习状态', exact: true }).click()
  await expect(page.getByLabel('第 2 题答案', { exact: true })).toHaveValue('断网本机候选 🧠')
  await expect(page.getByText('作答尚未确认同步', { exact: true })).toBeVisible()
  expect(await read(page, id)).toEqual(before)
  await page.unroute(`**/api/v1/practice/sessions/${id}/responses`)
  await page.getByRole('button', { name: '立即保存作答', exact: true }).click()
  await saved(page)
  expect((await read(page, id)).responses[0].answer).toBe('断网本机候选 🧠')
})

test('two real browser profiles produce a server CAS conflict with base local and remote before explicit choice', async ({ page, browser }) => {
  const { id } = await openSession(page, 'nativepracticecas')
  await question(page, 2); await page.getByLabel('第 2 题答案', { exact: true }).fill('共同基准'); await saved(page)
  await expect(page.getByText('✓ UI 会话已保存')).toBeVisible()
  const other = await browser.newContext({ storageState: await page.context().storageState() })
  let release!: () => void
  try {
    const second = await other.newPage(); await second.goto(page.url()); await saved(second); await question(second, 2)
    let entered!: () => void
    const held = new Promise<void>(resolve => { release = resolve }), started = new Promise<void>(resolve => { entered = resolve })
    await page.route(`**/api/v1/practice/sessions/${id}/responses`, async route => { entered(); await held; await route.continue() })
    await page.getByLabel('第 2 题答案', { exact: true }).fill('A本页候选'); await started
    await second.getByLabel('第 2 题答案', { exact: true }).fill('B服务端候选'); await saved(second)
    const rejected = page.waitForResponse(value => value.url().endsWith(`/practice/sessions/${id}/responses`))
    release(); expect((await rejected).status()).toBe(412)
    const comparison = page.locator('.practice-comparison')
    await expect(comparison).toContainText('共同基准'); await expect(comparison).toContainText('A本页候选'); await expect(comparison).toContainText('B服务端候选')
    expect((await read(page, id)).responses[0].answer).toBe('B服务端候选')
    await page.unroute(`**/api/v1/practice/sessions/${id}/responses`)
    await page.getByRole('button', { name: '保留本页作答并采用新基准', exact: true }).click()
    await saved(page)
    expect((await read(page, id)).responses[0].answer).toBe('A本页候选')
  } finally { release?.(); await other.close() }
})

test('missing private solution fails closed and a forged same-identity parent never replaces the existing practice tab', async ({ page }) => {
  const { fixture, id, session } = await openSession(page, 'nativepracticemissing', 'learner')
  const revealing = page.waitForResponse(value => value.url().endsWith(`/practice/sessions/${id}/solutions`))
  await page.getByRole('button', { name: '明确展开参考解答并记录暴露', exact: true }).click()
  expect((await revealing).status()).toBe(409)
  await expect(page.getByRole('alert').first()).toBeVisible()
  const after = await read(page, id)
  expect(after.exposure_event_ids).toEqual([]); expect(after.revision).toBe(session.revision)
  await expect(page.getByText('✓ UI 会话已保存')).toBeVisible()
  const base = await page.request.get('/api/v1/workbench/session').then(value => value.json())
  const target = { practice_ref: fixture.practice, lesson_ref: fixture.lesson, course_ref: { ...fixture.course, sha256: '0'.repeat(64) }, session_id: id }
  await page.evaluate(search => { history.pushState(null, '', search); dispatchEvent(new PopStateEvent('popstate')) }, `/?practice=${encodeURIComponent(JSON.stringify(target))}`)
  await expect(page.getByRole('heading', { name: '无法打开此精确链接', exact: true })).toBeVisible()
  const current = await page.request.get('/api/v1/workbench/session').then(value => value.json())
  expect(current.tabs).toEqual(base.tabs); expect(current.course_ref).toEqual(base.course_ref)
  await expect(page.locator('.practice-content')).toHaveCount(0)
  await page.getByRole('button', { name: '返回原标签', exact: true }).click()
  await saved(page)
})


test('two pages keep their durable local candidates and closing an unsynced practice requires explicit retention', async ({ page, context }, info) => {
  const { id } = await openSession(page, 'nativepracticelocal')
  await question(page, 2); await page.getByLabel('第 2 题答案', { exact: true }).fill('本机冲突共同基准'); await saved(page)
  const before = await read(page, id)
  const pattern = `**/api/v1/practice/sessions/${id}/responses`
  await page.route(pattern, route => route.abort('internetdisconnected'))
  await page.getByLabel('第 2 题答案', { exact: true }).fill('A保留在本机的候选')
  await expect(page.getByText('作答尚未确认同步', { exact: true })).toBeVisible()
  await expect(page.getByText('本机草稿存储可用', { exact: true })).toBeVisible()
  const second = await context.newPage()
  await second.route(pattern, route => route.abort('internetdisconnected'))
  try {
    await second.goto(page.url())
    await expect(second.getByRole('heading', { name: '发现本机未同步作答', exact: true })).toBeVisible()
    await second.getByRole('button', { name: '恢复这份本机作答', exact: true }).click()
    await expect(second.getByLabel('第 2 题答案', { exact: true })).toHaveValue('A保留在本机的候选')
    await expect(second.getByText('作答尚未确认同步', { exact: true })).toBeVisible()
    await second.getByLabel('第 2 题答案', { exact: true }).fill('B保留在本机的候选')
    await expect(page.getByRole('heading', { name: '本机作答草稿冲突', exact: true })).toBeVisible()
    const comparison = page.locator('.practice-comparison')
    await expect(comparison).toContainText('本机冲突共同基准')
    await expect(comparison).toContainText('A保留在本机的候选')
    await expect(comparison).toContainText('B保留在本机的候选')
    expect(await read(page, id)).toEqual(before)
    // A live peer must retain its own unsynced branch. Make the peer's
    // durable retention and close explicit before choosing with one writer.
    await expect(second.getByText('本机草稿存储可用', { exact: true })).toBeVisible()
    await second.locator('.object-tab.active .tab-close').click()
    await second.getByRole('dialog', { name: '保留未同步作答', exact: true }).getByRole('button', { name: '保留本机作答并关闭', exact: true }).click()
    await expect(second.locator('.practice-content')).toHaveCount(0)
    await second.close()
    const choice = page.locator('.practice-recovery details').filter({ hasText: 'A保留在本机的候选' }).first()
    await choice.getByRole('button', { name: /采用本机候选/ }).click()
    await expect(page.getByRole('heading', { name: '本机作答草稿冲突', exact: true })).toHaveCount(0)
    await expect(page.getByText('本机草稿存储可用', { exact: true })).toBeVisible()
    const href = page.url()
    await page.locator('.object-tab.active .tab-close').click()
    const closing = page.getByRole('dialog', { name: '保留未同步作答', exact: true })
    await expect(closing.getByRole('button', { name: '保留本机作答并关闭', exact: true })).toBeEnabled()
    await closing.getByRole('button', { name: '返回练习', exact: true }).click()
    await expect(page.getByLabel('第 2 题答案', { exact: true })).toHaveValue('A保留在本机的候选')
    await page.locator('.object-tab.active .tab-close').click()
    await page.getByRole('button', { name: '保留本机作答并关闭', exact: true }).click()
    await expect(page.locator('.practice-content')).toHaveCount(0)
    await second.close()
    // Workbench layout has its own real CAS; explicitly resolve it separately
    // from the already verified practice response and IndexedDB candidates.
    await expect.poll(async () => await page.getByText('✓ UI 会话已保存').count() > 0 || await page.getByRole('button', { name: '采用本地会话并重新保存', exact: true }).count() > 0).toBe(true)
    if (await page.getByRole('button', { name: '采用本地会话并重新保存', exact: true }).count()) await page.getByRole('button', { name: '采用本地会话并重新保存', exact: true }).click()
    await expect(page.getByText('✓ UI 会话已保存')).toBeVisible()
    await page.goto(href)
    await expect(page.getByRole('heading', { name: '发现本机未同步作答', exact: true })).toBeVisible()
    await expect(page.locator('.practice-recovery').first()).toContainText('A保留在本机的候选')
    expect(await read(page, id)).toEqual(before)
    await page.screenshot({ path: info.outputPath('practice-local-recovery-1440.png') })
  } finally { await second.close() }
})
