import { expect, test, type Page } from '../../apps/web/node_modules/@playwright/test/index.mjs'
import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { resolve } from 'node:path'
import { readFileSync } from 'node:fs'
import { bootstrap } from './helpers'
import { importReaderPackage, originalReaderPackage, type ReaderPackage } from './readerTestData'
import type { Note } from '../../packages/contracts/generated/types'

async function openActual(page: Page, prefix: string): Promise<ReaderPackage> {
  await bootstrap(page)
  const fixture = originalReaderPackage(prefix)
  const { dialog } = await importReaderPackage(page, fixture)
  await dialog.getByRole('button', { name: '打开已导入课程', exact: true }).click()
  await page.getByRole('button', { name: '继续阅读 →', exact: true }).click()
  await expect(page.locator('.real-reader > h1')).toHaveText('从定义到证明与例题的完整推导')
  await expect(page.locator('.real-reader svg').first()).toBeVisible()
  return fixture
}

async function selectRepeat(page: Page, fixture: ReaderPackage) {
  const root = page.locator(`#block-${fixture.blocks[0].id}-r1 .reader-markdown`)
  await root.evaluate(element => {
    const leaves = [...element.querySelectorAll<HTMLElement>('[data-source-start]')].filter(node => node.textContent === '重复句子用于选择定位。')
    if (leaves.length !== 2) throw new Error(`Expected two exact render leaves, received ${leaves.length}`)
    const range = document.createRange(); range.selectNodeContents(leaves[1])
    getSelection()!.removeAllRanges(); getSelection()!.addRange(range)
  })
  await expect(page.getByRole('button', { name: '为当前选文记笔记', exact: true })).toBeEnabled()
}

test('real imported directory, title search, worked-example link, long formula and frozen original download', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  const fixture = await openActual(page, 'nativedirectory')
  await page.screenshot({ path: info.outputPath('reader-real-overview-1440.png') })
  const progress = await page.request.get('/api/v1/learning/progress').then(value => value.json())
  expect(progress.readings.some((item: {ref:{id:string}}) => item.ref.id === fixture.lessons[0].id)).toBe(false)
  await page.getByLabel('搜索当前目录').fill('逐项计算')
  const hits = page.getByRole('navigation', { name: '目录搜索结果' })
  await expect(hits.getByRole('link', { name: '例题：逐项计算与边界', exact: true })).toBeVisible()
  await expect(hits).toContainText('从定义到证明与例题的完整推导')
  await hits.getByRole('link', { name: '例题：逐项计算与边界', exact: true }).click()
  const example = page.locator(`#block-${fixture.blocks[2].id}-r1`)
  await expect(example).toBeInViewport()
  await expect.poll(async () => { const value = await page.request.get('/api/v1/workbench/session').then(response => response.json()); return value.tabs.find((tab: {id:string}) => tab.id === value.active_tab_id)?.context.active_ref }).toEqual(fixture.blocks[2])
  const session = await page.request.get('/api/v1/workbench/session').then(value => value.json())
  expect(session.tabs.find((tab: {id:string}) => tab.id === session.active_tab_id).context).toMatchObject({ view_kind: 'worked_example', active_ref: fixture.blocks[2] })
  const formula = example.locator('.formula[data-tex^="v="]')
  await info.attach('actual-math-attributes', { body: JSON.stringify(await example.locator('.formula').evaluateAll(nodes => nodes.map(node => ({ tex: node.getAttribute('data-tex'), text: node.textContent })))), contentType: 'application/json' })
  await expect(formula.locator('svg[role=img]').last()).toBeVisible()
  expect(await formula.evaluate(node => node.scrollWidth > node.clientWidth)).toBe(true)
  expect(await formula.evaluate(node => getComputedStyle(node).overflowX)).toBe('auto')
  await formula.focus()
  await page.keyboard.press('ArrowRight')
  await expect.poll(() => formula.evaluate(node => node.scrollLeft)).toBeGreaterThan(0)
  await example.getByText('来源与提取诊断', { exact: true }).click()
  await expect(example.locator('.retained-original')).toContainText(createHash('sha256').update(fixture.bytes).digest('hex'))
  const download = page.waitForEvent('download')
  await example.getByRole('button', { name: '下载受控原件', exact: true }).click()
  const saved = await download
  expect(readFileSync((await saved.path())!)).toEqual(fixture.bytes)
  await page.screenshot({ path: info.outputPath('reader-real-example-1440.png') })
  expect(errors).toEqual([])
})

test('second repeated rendered selection preserves exact source codepoints, saves note, edits and soft deletes', async ({ page }) => {
  const fixture = await openActual(page, 'nativenotes')
  await selectRepeat(page, fixture)
  await page.getByRole('button', { name: '为当前选文记笔记', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '笔记', exact: true })
  await dialog.getByRole('button', { name: '用当前选文新建笔记', exact: true }).click()
  await dialog.getByLabel('笔记正文').fill('真实笔记 🧠 中文 café é')
  const response = page.waitForResponse(value => value.request().method() === 'POST' && value.url().endsWith('/api/v1/notes'))
  await dialog.getByRole('button', { name: '保存笔记到服务端', exact: true }).click()
  expect((await response).status()).toBe(201)
  await expect(dialog.getByText('笔记已保存到服务端', { exact: true })).toBeVisible()
  const ref = await (await response).json()
  const note: Note = (await page.request.get('/api/v1/notes').then(value => value.json())).items.find((item: Note) => item.id === ref.id)
  const source = fixture.bodies[fixture.blocks[0].id]
  const offset = source.lastIndexOf('重复句子用于选择定位。')
  expect(note.anchor.start_codepoint).toBe(Array.from(source.slice(0, offset)).length)
  expect(note.anchor.end_codepoint - note.anchor.start_codepoint).toBe(Array.from(note.anchor.exact_quote).length)
  expect(note.anchor.ref).toEqual(fixture.blocks[0])
  await dialog.getByLabel('笔记正文').fill('编辑后仍绑定第二次重复选文')
  await dialog.getByRole('button', { name: '保存笔记到服务端', exact: true }).click()
  await expect(dialog.getByText('笔记已保存到服务端', { exact: true })).toBeVisible()
  await expect(dialog.locator('.note-identity')).toContainText('修订 2')
  await dialog.getByRole('button', { name: '删除此笔记', exact: true }).click()
  await dialog.getByRole('button', { name: '确认软删除笔记', exact: true }).click()
  await expect(dialog.getByText('笔记已从当前视图删除；历史引用保留。')).toBeVisible()
  expect((await page.request.get('/api/v1/notes').then(value => value.json())).items.some((item: Note) => item.id === ref.id)).toBe(false)
  const revisions = await page.request.get(`/api/v1/objects/${ref.id}/revisions`).then(value => value.json())
  expect(revisions.items.length).toBeGreaterThanOrEqual(2)
})


test('native source keyboard selection creates exact Markdown codepoints without rendered-text guessing', async ({ page }, info) => {
  const fixture = await openActual(page, 'nativekeyboard')
  const definition = page.locator(`#block-${fixture.blocks[0].id}-r1`)
  await definition.getByText('原始 Markdown 与精确选文', { exact: true }).click()
  const source = definition.getByLabel('原始 Markdown：定义：残差与损失')
  await source.focus()
  await expect(source).toBeFocused()
  // Chromium readonly textareas support Ctrl+A; Ctrl+Home + Shift+End leaves a collapsed caret.
  await page.keyboard.press('Control+A')

  await info.attach('native-textarea-selection', { body: JSON.stringify(await source.evaluate(node => ({ start: (node as HTMLTextAreaElement).selectionStart, end: (node as HTMLTextAreaElement).selectionEnd, focused: document.activeElement === node }))), contentType: 'application/json' })
  await expect(page.getByRole('button', { name: '为当前选文记笔记', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '为当前选文记笔记', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '笔记', exact: true })
  await dialog.getByRole('button', { name: '用当前选文新建笔记', exact: true }).click()
  await expect(dialog.locator('blockquote')).toHaveText(fixture.bodies[fixture.blocks[0].id])
  await page.setViewportSize({ width: 390, height: 844 })
  const close = dialog.getByRole('button', { name: '关闭笔记', exact: true })
  await expect(close).toBeVisible()
  const geometry = await dialog.evaluate(node => ({ width: node.clientWidth, scrollWidth: node.scrollWidth }))
  expect(geometry.scrollWidth).toBeLessThanOrEqual(geometry.width + 1)
  expect(await close.evaluate(node => { const box = node.getBoundingClientRect(); return node.contains(document.elementFromPoint(box.x + box.width / 2, box.y + box.height / 2)) })).toBe(true)
  await page.screenshot({ path: info.outputPath('reader-exact-note-390.png') })
})

test('offline local note recovery and a real concurrent server revision show three-way comparison before CAS save', async ({ page }) => {
  const fixture = await openActual(page, 'nativeconflict')
  await selectRepeat(page, fixture)
  await page.getByRole('button', { name: '为当前选文记笔记', exact: true }).click()
  let dialog = page.getByRole('dialog', { name: '笔记', exact: true })
  await dialog.getByRole('button', { name: '用当前选文新建笔记', exact: true }).click()
  await dialog.getByLabel('笔记正文').fill('原基准笔记')
  const created = page.waitForResponse(value => value.request().method() === 'POST' && value.url().endsWith('/api/v1/notes'))
  await dialog.getByRole('button', { name: '保存笔记到服务端', exact: true }).click()
  const baseRef = await (await created).json()
  await expect(dialog.getByText('笔记已保存到服务端', { exact: true })).toBeVisible()
  const base: Note = (await page.request.get('/api/v1/notes').then(value => value.json())).items.find((item: Note) => item.id === baseRef.id)
  await dialog.getByLabel('笔记正文').fill('本页离线编辑，必须保留')
  await expect(dialog.getByText('本机草稿已保留；尚未同步为服务端笔记。')).toBeVisible()
  await page.route('**/api/v1/notes**', route => route.abort('internetdisconnected'))
  await page.route(`**/api/v1/objects/${base.id}/current`, route => route.abort('internetdisconnected'))
  await page.reload()
  await expect(page.locator('.real-reader > h1')).toBeVisible()
  await page.getByRole('button', { name: '查看笔记', exact: true }).click()
  dialog = page.getByRole('dialog', { name: '笔记', exact: true })
  await dialog.getByRole('button', { name: `恢复本机笔记草稿 ${base.id}`, exact: true }).click()
  await expect(dialog.getByLabel('笔记正文')).toHaveValue('本页离线编辑，必须保留')
  await expect(dialog.getByRole('alert').first()).toBeVisible()
  await page.unroute('**/api/v1/notes**')
  await page.unroute(`**/api/v1/objects/${base.id}/current`)
  const changed = await page.evaluate(async ({ base, baseRef }) => {
    const auth = await fetch('/api/v1/session').then(value => value.json())
    const response = await fetch(`/api/v1/notes/${base.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json', 'X-CSRF-Token': auth.csrf_token, 'Idempotency-Key': crypto.randomUUID(), 'If-Match': `"${baseRef.sha256}"` }, body: JSON.stringify({ ...base, revision: 2, markdown: '另一写入者的服务端笔记' }) })
    return { status: response.status, ref: await response.json() }
  }, { base, baseRef })
  expect(changed.status).toBe(200)
  const rejected = page.waitForResponse(value => value.request().method() === 'PATCH' && value.url().endsWith(`/api/v1/notes/${base.id}`))
  await dialog.getByRole('button', { name: '保存笔记到服务端', exact: true }).click()
  expect((await rejected).status()).toBe(412)
  await expect(dialog.getByRole('heading', { name: '笔记版本冲突', exact: true })).toBeVisible()
  const comparison = dialog.locator('.note-conflict')
  await expect(comparison).toContainText('原基准笔记')
  await expect(comparison).toContainText('本页离线编辑，必须保留')
  await expect(comparison).toContainText('另一写入者的服务端笔记')
  await dialog.getByRole('button', { name: '保留本地内容并采用新基准', exact: true }).click()
  await dialog.getByRole('button', { name: '保存笔记到服务端', exact: true }).click()
  await expect(dialog.getByText('笔记已保存到服务端', { exact: true })).toBeVisible()
  await expect(dialog.locator('.note-identity')).toContainText('修订 3')
  const actual: Note = (await page.request.get('/api/v1/notes').then(value => value.json())).items.find((item: Note) => item.id === base.id)
  expect(actual.markdown).toBe('本页离线编辑，必须保留')
  expect(actual.anchor).toEqual(base.anchor)
})

test('historical course revisions stay in separate exact tabs and hash-mismatched links preserve unresolved reference', async ({ page }) => {
  await bootstrap(page)
  const current = originalReaderPackage('nativehistory', 2, true)
  const old = originalReaderPackage('nativehistory', 1)
  const imported = await importReaderPackage(page, current)
  await imported.dialog.getByRole('button', { name: '关闭导入', exact: true }).click()
  const target = { course: current.course, lesson: current.lessons[0], block: current.blocks[0], view: 'lesson' }
  await page.goto(`/?reader=${encodeURIComponent(JSON.stringify(target))}`)
  await expect(page.locator('.real-reader')).toContainText('第二修订选文')
  const oldTarget = { course: old.course, lesson: old.lessons[0], block: old.blocks[0], view: 'lesson' }
  await expect(page.getByText('✓ UI 会话已保存')).toBeVisible()
  await page.goto(`/?reader=${encodeURIComponent(JSON.stringify(oldTarget))}`)
  await expect(page.locator('.real-reader')).toContainText('正在阅读旧修订')
  await expect(page.locator('.real-reader')).toContainText('选文甲')
  await expect(page.getByRole('tab', { name: /定义：残差与损失 · r1/ })).toBeVisible()
  await expect(page.getByRole('tab', { name: /block_nativehistory_definition · r2/ })).toBeVisible()
  await page.getByRole('tab', { name: /block_nativehistory_definition · r2/ }).click()
  await expect(page.locator('.real-reader')).toContainText('第二修订选文')
  await page.getByRole('button', { name: '查看教材修订', exact: true }).click()
  const revisions = page.getByRole('dialog', { name: '教材修订', exact: true })
  await expect(revisions.getByRole('button', { name: /教材修订 1/ })).toBeVisible()
  await expect(revisions.getByRole('button', { name: /教材修订 2/ })).toBeVisible()
  await revisions.getByRole('button', { name: '关闭教材修订', exact: true }).click()
  await expect(page.getByText('✓ UI 会话已保存')).toBeVisible()
  const invalid = { ...oldTarget, block: { ...oldTarget.block, sha256: 'b'.repeat(64) } }
  await page.goto(`/?reader=${encodeURIComponent(JSON.stringify(invalid))}`)
  await expect(page.getByRole('heading', { name: '无法打开此精确链接', exact: true })).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('不一致')
  await expect.poll(async () => { const value = await page.request.get('/api/v1/workbench/session').then(response => response.json()); return value.tabs.find((tab: {id:string}) => tab.id === value.active_tab_id)?.context.active_ref }).toEqual(current.blocks[0])
})


test('a private original authorized before a cross-profile role decrease cannot trigger a late browser download', async ({ page, browser }) => {
  test.setTimeout(60_000)
  await bootstrap(page)
  const root = resolve(import.meta.dirname, '../..')
  const bytes = execFileSync(`${root}/.venv/bin/python`, ['-B', '-c', 'import sys;from tests.document_fixtures import docx_fixture;sys.stdout.buffer.write(docx_fixture())'], { cwd: root })
  await page.getByRole('button', { name: '导入', exact: true }).click()
  const imported = page.getByRole('dialog', { name: '导入', exact: true })
  await imported.getByLabel('解析格式').selectOption('docx')
  await imported.getByLabel('选择导入文件').setInputFiles({ name: 'synthetic-reader-source.docx', mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', buffer: bytes })
  await imported.getByRole('button', { name: '上传并生成预览', exact: true }).click()
  await expect(imported.getByText('预览已就绪，等待确认', { exact: true })).toBeVisible()
  for (const checkbox of await imported.getByRole('checkbox', { name: /接受警告/ }).all()) await checkbox.check()
  await imported.getByRole('checkbox', { name: /我已核对本次候选/ }).check()
  await imported.getByRole('button', { name: '确认导入当前候选', exact: true }).click()
  await imported.getByRole('button', { name: '打开已导入课程', exact: true }).click()
  await page.getByRole('button', { name: '继续阅读 →', exact: true }).click()
  const panel = page.locator('.reader-sources').first()
  await panel.locator('summary').click()
  await expect(panel.getByText('原件需要作者角色。', { exact: false })).toBeVisible()
  await panel.getByRole('button', { name: '切换为作者以读取原件', exact: true }).click()
  await expect(panel.getByRole('button', { name: '下载受控原件', exact: true })).toBeVisible()
  const alternate = await browser.newContext({ storageState: await page.context().storageState() })
  let release!: () => void
  try {
    const second = await alternate.newPage()
    await second.goto('/')
    await expect(second.getByText('✓ UI 会话已保存')).toBeVisible()
    await second.getByRole('button', { name: '导入', exact: true }).click()
    const secondDialog = second.getByRole('dialog', { name: '导入', exact: true })
    await expect(secondDialog.getByText('操作角色：作者', { exact: true })).toBeVisible()
    let loaded!: () => void
    const responseLoaded = new Promise<void>(resolve => { loaded = resolve })
    const held = new Promise<void>(resolve => { release = resolve })
    let artifactUrl = ''
    await page.route('**/api/v1/artifacts/*/download', async route => { const response = await route.fetch(); expect(response.status()).toBe(200); artifactUrl = route.request().url(); loaded(); await held; await route.fulfill({ response }) })
    const downloads: string[] = []; page.on('download', value => downloads.push(value.suggestedFilename()))
    await panel.getByRole('button', { name: '下载受控原件', exact: true }).click()
    await responseLoaded
    const changed = second.waitForResponse(value => value.request().method() === 'POST' && value.url().endsWith('/api/v1/session/role'))
    await secondDialog.getByRole('button', { name: '切换为学习者角色', exact: true }).click()
    expect((await changed).status()).toBe(200)
    expect((await page.request.get(artifactUrl)).status()).toBe(403)
    release()
    await expect(panel.getByRole('alert')).toBeVisible()
    await expect(panel.getByRole('button', { name: '下载受控原件', exact: true })).toBeEnabled()
    expect(downloads).toEqual([])
  } finally { release?.(); await alternate.close() }
})
