-- CodexBroker-owned control facts. No baseline schema or Provider grants change.
CREATE TABLE codex_bootstrap_preparations(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),actor_session_id TEXT NOT NULL REFERENCES local_sessions(id),operation_json TEXT NOT NULL CHECK(json_valid(operation_json)),operation_sha256 TEXT NOT NULL);
CREATE TABLE codex_bootstrap_memberships(preparation_id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),actor_session_id TEXT NOT NULL REFERENCES local_sessions(id),operation_sha256 TEXT NOT NULL);
CREATE TABLE codex_bootstrap_heads(preparation_id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),event_count INTEGER NOT NULL CHECK(event_count BETWEEN 0 AND 4),head_sha256 TEXT NOT NULL);
CREATE TABLE codex_bootstrap_events(preparation_id TEXT NOT NULL,workspace_id TEXT NOT NULL REFERENCES workspace(id),sequence INTEGER NOT NULL CHECK(sequence BETWEEN 1 AND 4),previous_sha256 TEXT NOT NULL,record_json TEXT NOT NULL CHECK(json_valid(record_json)),record_sha256 TEXT NOT NULL,PRIMARY KEY(preparation_id,sequence));
CREATE TABLE codex_bootstrap_event_memberships(preparation_id TEXT NOT NULL,workspace_id TEXT NOT NULL REFERENCES workspace(id),sequence INTEGER NOT NULL,record_sha256 TEXT NOT NULL,PRIMARY KEY(preparation_id,sequence));
CREATE TABLE codex_bootstrap_commands(workspace_id TEXT NOT NULL REFERENCES workspace(id),actor_session_id TEXT NOT NULL REFERENCES local_sessions(id),route TEXT NOT NULL,command_key TEXT NOT NULL,preparation_id TEXT NOT NULL,sequence INTEGER NOT NULL,command_sha256 TEXT NOT NULL,record_sha256 TEXT NOT NULL,PRIMARY KEY(workspace_id,actor_session_id,route,command_key),UNIQUE(preparation_id,sequence));
CREATE TABLE codex_bootstrap_session_memberships(session_id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspace(id),actor_session_id TEXT NOT NULL REFERENCES local_sessions(id),preparation_id TEXT NOT NULL UNIQUE,operation_sha256 TEXT NOT NULL,owner_id TEXT NOT NULL);

CREATE TRIGGER codex_bootstrap_preparations_insert BEFORE INSERT ON codex_bootstrap_preparations WHEN EXISTS(SELECT 1 FROM codex_bootstrap_preparations WHERE id=NEW.id) BEGIN SELECT RAISE(ABORT,'immutable codex preparation'); END;
CREATE TRIGGER codex_bootstrap_preparations_update BEFORE UPDATE ON codex_bootstrap_preparations BEGIN SELECT RAISE(ABORT,'immutable codex preparation'); END;
CREATE TRIGGER codex_bootstrap_preparations_delete BEFORE DELETE ON codex_bootstrap_preparations BEGIN SELECT RAISE(ABORT,'immutable codex preparation'); END;
CREATE TRIGGER codex_bootstrap_memberships_insert BEFORE INSERT ON codex_bootstrap_memberships WHEN EXISTS(SELECT 1 FROM codex_bootstrap_memberships WHERE preparation_id=NEW.preparation_id) BEGIN SELECT RAISE(ABORT,'immutable codex membership'); END;
CREATE TRIGGER codex_bootstrap_memberships_update BEFORE UPDATE ON codex_bootstrap_memberships BEGIN SELECT RAISE(ABORT,'immutable codex membership'); END;
CREATE TRIGGER codex_bootstrap_memberships_delete BEFORE DELETE ON codex_bootstrap_memberships BEGIN SELECT RAISE(ABORT,'immutable codex membership'); END;
CREATE TRIGGER codex_bootstrap_events_insert BEFORE INSERT ON codex_bootstrap_events WHEN EXISTS(SELECT 1 FROM codex_bootstrap_events WHERE preparation_id=NEW.preparation_id AND sequence=NEW.sequence) BEGIN SELECT RAISE(ABORT,'immutable codex event'); END;
CREATE TRIGGER codex_bootstrap_events_update BEFORE UPDATE ON codex_bootstrap_events BEGIN SELECT RAISE(ABORT,'immutable codex event'); END;
CREATE TRIGGER codex_bootstrap_events_delete BEFORE DELETE ON codex_bootstrap_events BEGIN SELECT RAISE(ABORT,'immutable codex event'); END;
CREATE TRIGGER codex_bootstrap_event_memberships_insert BEFORE INSERT ON codex_bootstrap_event_memberships WHEN EXISTS(SELECT 1 FROM codex_bootstrap_event_memberships WHERE preparation_id=NEW.preparation_id AND sequence=NEW.sequence) BEGIN SELECT RAISE(ABORT,'immutable codex event membership'); END;
CREATE TRIGGER codex_bootstrap_event_memberships_update BEFORE UPDATE ON codex_bootstrap_event_memberships BEGIN SELECT RAISE(ABORT,'immutable codex event membership'); END;
CREATE TRIGGER codex_bootstrap_event_memberships_delete BEFORE DELETE ON codex_bootstrap_event_memberships BEGIN SELECT RAISE(ABORT,'immutable codex event membership'); END;
CREATE TRIGGER codex_bootstrap_commands_insert BEFORE INSERT ON codex_bootstrap_commands WHEN EXISTS(SELECT 1 FROM codex_bootstrap_commands WHERE workspace_id=NEW.workspace_id AND actor_session_id=NEW.actor_session_id AND route=NEW.route AND command_key=NEW.command_key OR preparation_id=NEW.preparation_id AND sequence=NEW.sequence) BEGIN SELECT RAISE(ABORT,'immutable codex command'); END;
CREATE TRIGGER codex_bootstrap_commands_update BEFORE UPDATE ON codex_bootstrap_commands BEGIN SELECT RAISE(ABORT,'immutable codex command'); END;
CREATE TRIGGER codex_bootstrap_commands_delete BEFORE DELETE ON codex_bootstrap_commands BEGIN SELECT RAISE(ABORT,'immutable codex command'); END;
CREATE TRIGGER codex_bootstrap_session_memberships_insert BEFORE INSERT ON codex_bootstrap_session_memberships WHEN EXISTS(SELECT 1 FROM codex_bootstrap_session_memberships WHERE session_id=NEW.session_id OR preparation_id=NEW.preparation_id) BEGIN SELECT RAISE(ABORT,'immutable codex session membership'); END;
CREATE TRIGGER codex_bootstrap_session_memberships_update BEFORE UPDATE ON codex_bootstrap_session_memberships BEGIN SELECT RAISE(ABORT,'immutable codex session membership'); END;
CREATE TRIGGER codex_bootstrap_session_memberships_delete BEFORE DELETE ON codex_bootstrap_session_memberships BEGIN SELECT RAISE(ABORT,'immutable codex session membership'); END;
CREATE TRIGGER codex_bootstrap_heads_insert BEFORE INSERT ON codex_bootstrap_heads WHEN EXISTS(SELECT 1 FROM codex_bootstrap_heads WHERE preparation_id=NEW.preparation_id) BEGIN SELECT RAISE(ABORT,'immutable codex head identity'); END;
CREATE TRIGGER codex_bootstrap_heads_delete BEFORE DELETE ON codex_bootstrap_heads BEGIN SELECT RAISE(ABORT,'immutable codex head identity'); END;
