-- Aggregate commands and complete membership; Import owns its distinct 0033 facts.
CREATE TABLE codex_artifact_import_heads(workspace_id TEXT NOT NULL REFERENCES workspace(id),job_id TEXT PRIMARY KEY REFERENCES jobs(id),event_count INTEGER NOT NULL CHECK(event_count>0),head_sha256 TEXT NOT NULL);
CREATE TABLE codex_artifact_import_events(workspace_id TEXT NOT NULL REFERENCES workspace(id),job_id TEXT NOT NULL REFERENCES jobs(id),seq INTEGER NOT NULL CHECK(seq>0),record_json TEXT NOT NULL CHECK(json_valid(record_json)),record_sha256 TEXT NOT NULL,PRIMARY KEY(job_id,seq));
CREATE TABLE codex_artifact_import_members(workspace_id TEXT NOT NULL REFERENCES workspace(id),job_id TEXT NOT NULL REFERENCES jobs(id),seq INTEGER NOT NULL,record_sha256 TEXT NOT NULL,PRIMARY KEY(job_id,seq));
CREATE TABLE codex_artifact_import_commands(workspace_id TEXT NOT NULL REFERENCES workspace(id),actor_session_id TEXT NOT NULL REFERENCES local_sessions(id),route TEXT NOT NULL,target_id TEXT NOT NULL,command_key TEXT NOT NULL,job_id TEXT NOT NULL REFERENCES jobs(id),seq INTEGER NOT NULL,command_sha256 TEXT NOT NULL,PRIMARY KEY(workspace_id,actor_session_id,route,target_id,command_key),UNIQUE(job_id,seq));
CREATE TRIGGER codex_artifact_import_heads_delete BEFORE DELETE ON codex_artifact_import_heads BEGIN SELECT RAISE(ABORT,'immutable Codex artifact import'); END;
CREATE TRIGGER codex_artifact_import_heads_replace BEFORE INSERT ON codex_artifact_import_heads WHEN EXISTS(SELECT 1 FROM codex_artifact_import_heads WHERE job_id=NEW.job_id) BEGIN SELECT RAISE(ABORT,'immutable Codex artifact import'); END;
CREATE TRIGGER codex_artifact_import_events_delete BEFORE DELETE ON codex_artifact_import_events BEGIN SELECT RAISE(ABORT,'immutable Codex artifact import'); END;
CREATE TRIGGER codex_artifact_import_events_update BEFORE UPDATE ON codex_artifact_import_events BEGIN SELECT RAISE(ABORT,'immutable Codex artifact import'); END;
CREATE TRIGGER codex_artifact_import_events_replace BEFORE INSERT ON codex_artifact_import_events WHEN EXISTS(SELECT 1 FROM codex_artifact_import_events WHERE job_id=NEW.job_id AND seq=NEW.seq) BEGIN SELECT RAISE(ABORT,'immutable Codex artifact import'); END;
CREATE TRIGGER codex_artifact_import_members_delete BEFORE DELETE ON codex_artifact_import_members BEGIN SELECT RAISE(ABORT,'immutable Codex artifact import'); END;
CREATE TRIGGER codex_artifact_import_members_update BEFORE UPDATE ON codex_artifact_import_members BEGIN SELECT RAISE(ABORT,'immutable Codex artifact import'); END;
CREATE TRIGGER codex_artifact_import_members_replace BEFORE INSERT ON codex_artifact_import_members WHEN EXISTS(SELECT 1 FROM codex_artifact_import_members WHERE job_id=NEW.job_id AND seq=NEW.seq) BEGIN SELECT RAISE(ABORT,'immutable Codex artifact import'); END;
CREATE TRIGGER codex_artifact_import_commands_delete BEFORE DELETE ON codex_artifact_import_commands BEGIN SELECT RAISE(ABORT,'immutable Codex artifact import'); END;
CREATE TRIGGER codex_artifact_import_commands_update BEFORE UPDATE ON codex_artifact_import_commands BEGIN SELECT RAISE(ABORT,'immutable Codex artifact import'); END;
CREATE TRIGGER codex_artifact_import_commands_replace BEFORE INSERT ON codex_artifact_import_commands WHEN EXISTS(SELECT 1 FROM codex_artifact_import_commands WHERE job_id=NEW.job_id AND seq=NEW.seq OR workspace_id=NEW.workspace_id AND actor_session_id=NEW.actor_session_id AND route=NEW.route AND target_id=NEW.target_id AND command_key=NEW.command_key) BEGIN SELECT RAISE(ABORT,'immutable Codex artifact import'); END;
