import { spawn, execFileSync } from 'node:child_process'
import { createServer } from 'node:net'
import { mkdtempSync, readFileSync, writeFileSync, chmodSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'
import { createHash } from 'node:crypto'
import { setTimeout as pause } from 'node:timers/promises'
import assert from 'node:assert/strict'
import { chromium, expect as baseExpect } from '<LOCAL_HOME>/.cache/learning-workbench-acceptance/m63-codex-artifact-ui-4353-owner-oct04/apps/web/node_modules/@playwright/test/index.mjs'
const expect=baseExpect.configure({timeout:15000}), root='<LOCAL_HOME>/.cache/learning-workbench-acceptance/m63-codex-artifact-ui-4353-owner-oct04', out=import.meta.dirname, head='422fdbcaadcfbe4b6e59f54cd192b545345347c8'
const sha=b=>createHash('sha256').update(b).digest('hex'), git=(...args)=>execFileSync('git',args,{cwd:root,encoding:'utf8',maxBuffer:16*1024*1024}).trim()
function inputs(){assert.equal(git('rev-parse','HEAD'),head);assert.equal(git('status','--porcelain'),'');const files={};for(const row of execFileSync('git',['ls-tree','-rz',head],{cwd:root,maxBuffer:16*1024*1024}).toString().split('\0').filter(Boolean)){const [meta,path]=row.split('\t');if(path.startsWith('progress/'))continue;const bytes=readFileSync(resolve(root,path)),[mode,type,oid]=meta.split(' ');assert.equal(createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex'),oid);files[path]={mode,type,git_blob:oid,sha256:sha(bytes),bytes:bytes.length}}return{head,count:Object.keys(files).length,files}}
const before=inputs();writeFileSync(resolve(out,'before.json'),JSON.stringify(before,null,2)+'\n')
const tmp=process.env.TMPDIR;assert.ok(tmp.startsWith('<LOCAL_HOME>/.cache/lwa422-'));chmodSync(tmp,0o700)
const data=mkdtempSync(resolve(tmp,'data-')),profile=mkdtempSync(resolve(tmp,'profile-'));writeFileSync(resolve(out,'private-paths.json'),JSON.stringify({tmp,data,profile},null,2)+'\n')
const socket=createServer();await new Promise((ok,no)=>{socket.once('error',no);socket.listen(0,'127.0.0.1',ok)});const port=socket.address().port;await new Promise(ok=>socket.close(ok));const origin=`http://127.0.0.1:${port}`
const env={...process.env,TMPDIR:tmp,LEARNING_DATA_DIR:data,LEARNING_PORT:String(port),LEARNING_HOST:'127.0.0.1',LEARNING_CODEX_EXECUTABLE:resolve(data,'missing-real-cli'),PYTHONPATH:`${out}:${root}`,PYTHONDONTWRITEBYTECODE:'1'}
let api,browser;const calls=[],errors=[],facts={source:head,started_at:new Date().toISOString(),screenshots:[],assertions:[],actual_CLI:'NOT_RUN',actual_remote_model:'NOT_RUN',actual_tool_process:'NOT_RUN'}
const db='learning-workbench.codex-artifact-commands.v1',formdb='learning-workbench.codex-artifact-forms.v1'
async function stored(page,name){return page.evaluate(name=>new Promise((ok,no)=>{const r=indexedDB.open(name,1);r.onerror=()=>no(Error('IDB open'));r.onsuccess=()=>{const d=r.result,t=d.transaction('drafts','readonly'),q=t.objectStore('drafts').getAll();q.onerror=()=>no(Error('IDB read'));q.onsuccess=()=>{ok(q.result.map(v=>JSON.parse(v.text)));d.close()}}}),name)}
async function panels(page){await page.getByRole('button',{name:'创作',exact:true}).click();const p=page.getByRole('region',{name:'Codex 产物清单与回导',exact:true});await p.getByRole('button',{name:'读取产物记录与权限',exact:true}).click();await expect(p.getByText('产物本机记录已读取；只恢复原事实，没有自动 POST。',{exact:true})).toBeVisible();return p}
async function capture(page,region,label){for(const width of [1440,390]){await page.setViewportSize({width,height:900});await region.scrollIntoViewIfNeeded();const geometry=await page.getByRole('dialog',{name:'创作',exact:true}).evaluate(e=>({client:e.clientWidth,scroll:e.scrollWidth,viewport:innerWidth,document:document.documentElement.scrollWidth}));assert.ok(geometry.scroll<=geometry.client+1&&geometry.document<=geometry.viewport);const file=`${label}-${width}.png`;await page.screenshot({path:resolve(out,file)});facts.screenshots.push({file,sha256:sha(readFileSync(resolve(out,file))),geometry})}await page.setViewportSize({width:1440,height:900})}
const postCount=()=>calls.filter(v=>v.startsWith('POST ')).length
try{
 api=spawn(`${root}/.venv/bin/python`,['-B','-m','uvicorn','controlled_api:create_app','--factory','--host','127.0.0.1','--port',String(port),'--no-access-log'],{cwd:root,env,detached:true,stdio:['ignore','pipe','pipe']});let tail='';for(const s of [api.stdout,api.stderr])s.on('data',b=>{tail=(tail+b).slice(-8192)});let ready=false;for(let n=0;n<400;n++){if(api.exitCode!==null)throw Error('Owned fixture server exited: '+tail);try{if((await fetch(origin+'/health',{signal:AbortSignal.timeout(500)})).ok){ready=true;break}}catch{}await pause(50)}assert.ok(ready,'Owned loopback readiness')
 const fixture=JSON.parse(readFileSync(resolve(data,'private-fixture.json'),'utf8'));facts.synthetic_memory_requests=fixture.synthetic_memory_requests;facts.synthetic_bootstrap_calls=fixture.synthetic_bootstrap_calls
 browser=await chromium.launchPersistentContext(profile,{executablePath:'/usr/bin/google-chrome',headless:true,baseURL:origin,viewport:{width:1440,height:900}});await browser.addCookies(fixture.cookies);const page=browser.pages()[0];page.setDefaultTimeout(15000);page.on('dialog',d=>d.accept());page.on('pageerror',()=>errors.push('PAGE_ERROR'));page.on('request',r=>{const u=new URL(r.url());if(u.pathname.startsWith('/api/')){assert.equal(u.origin,origin);calls.push(`${r.method()} ${u.pathname}`)}})
 await page.goto(origin);await expect(page.getByText('✓ UI 会话已保存',{exact:true})).toBeVisible();let p=await panels(page)
 await p.getByLabel('产物来源 session ID',{exact:true}).fill(fixture.session_id);await p.getByLabel('产物来源 turn ID',{exact:true}).fill(fixture.turn_id)
 await p.getByRole('button',{name:'独立读取当前产物清单',exact:true}).click();const m=p.getByRole('region',{name:'当前产物清单 GET',exact:true});await expect(m).toContainText('failed');await expect(m).toContainText('数学审校 NOT_RUN；来源核验 NOT_RUN；独立教学审校 NOT_RUN。');await capture(page,m,'manifest-failed-unreviewed')
 const entry=fixture.manifest.manifest.entries[0],download=page.waitForEvent('download');await p.getByRole('button',{name:`受控下载 ${entry.logical_path}`,exact:true}).click();const file=await download;const path=await file.path();assert.equal(sha(readFileSync(path)),entry.sha256);facts.assertions.push('controlled existing download returns exact manifest bytes')
 await p.getByRole('button',{name:'使用此清单建立新选择',exact:true}).click();await p.getByLabel(`选择产物 ${entry.logical_path}`,{exact:true}).check()
 const target=`/api/v1/codex/sessions/${fixture.session_id}/artifacts/import`;let lost
 await page.route(`**${target}`,async route=>{const req=route.request();assert.equal(req.method(),'POST');const key=await req.headerValue('idempotency-key'),body=req.postDataJSON(),original=(await stored(page,db)).find(c=>c.command_id===key);assert.ok(original);assert.equal(original.actor_session_id,fixture.actor);assert.deepEqual(original.body,body);assert.deepEqual(original.basis,fixture.manifest);assert.equal(original.ack,null);const r=await route.fetch();assert.equal(r.status(),202);lost={key,body,original,ack:await r.json(),bytes:await r.body()};await route.abort('failed')},{times:1})
 await p.getByRole('button',{name:'明确新建所选产物的回导预览',exact:true}).click();await expect(p.getByText('产物结果或本机保存未知；原命令保留，只能显式回放原 key。',{exact:true})).toBeVisible();assert.ok(lost);const prior=postCount(),forms=await stored(page,formdb)
 await page.reload();await expect(page.getByText('✓ UI 会话已保存',{exact:true})).toBeVisible();p=await panels(page);assert.equal(postCount(),prior);assert.deepEqual(await stored(page,formdb),forms)
 const replayResponse=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname===target);await p.getByRole('button',{name:`显式回放回导原 key ${lost.key}`,exact:true}).click();const replay=await replayResponse;assert.equal(replay.status(),202);assert.equal(await replay.request().headerValue('idempotency-key'),lost.key);assert.deepEqual(replay.request().postDataJSON(),lost.body);assert.deepEqual(await replay.body(),lost.bytes)
 await expect(p.getByText('回导原 202 ACK 已保存；聚合和 Import 子项状态须独立 GET，未自动确认入库。',{exact:true})).toBeVisible();assert.deepEqual((await stored(page,db)).find(c=>c.command_id===lost.key),{...lost.original,ack:lost.ack})
 await p.getByRole('button',{name:`读取回导当前子项 ${lost.ack.id}`,exact:true}).click();const aggregate=p.getByRole('region',{name:'回导聚合当前 GET',exact:true});await expect(aggregate).toContainText('completed');const response=await page.request.get(`/api/v1/codex/artifact-imports/${lost.ack.id}`);assert.equal(response.status(),200);const current=await response.json();assert.equal(current.job.status,'completed');assert.equal(lost.ack.status,'queued');assert.equal(current.items[0].source_sha256,entry.sha256);assert.equal(current.items[0].job.status,'awaiting_approval');await capture(page,aggregate,'aggregate-current-original-ack')
 await p.getByRole('button',{name:`打开普通 Import 预览 ${current.items[0].import_id}`,exact:true}).click();await p.getByRole('button',{name:`读取指定回导预览 ${current.items[0].import_id}`,exact:true}).click();const preview=p.getByRole('region',{name:'候选正文预览',exact:true});await expect(preview).toBeVisible();await expect(p).toContainText('未审');await capture(page,preview,'ordinary-import-preview')
 assert.equal(postCount(),prior+1);const imported=await page.request.get(`/api/v1/imports/${current.items[0].import_id}`).then(r=>r.json());assert.equal(imported.status,'preview_ready');assert.equal(imported.input_sha256,entry.sha256);assert.ok(imported.warnings.some(v=>v.code==='CODEX_IMPORTED_MATERIAL_UNREVIEWED'))
 const durable=await stored(page,db);await page.reload();await expect(page.getByText('✓ UI 会话已保存',{exact:true})).toBeVisible();p=await panels(page);assert.equal(postCount(),prior+1);assert.deepEqual(await stored(page,db),durable)
 const s=await page.request.get('/api/v1/session').then(r=>r.json());const role=await page.request.post('/api/v1/session/role',{headers:{Origin:origin,'X-CSRF-Token':s.csrf_token,'Idempotency-Key':'native-artifact-learner'},data:{role:'learner'}});assert.equal(role.status(),200);await p.getByRole('button',{name:'读取产物记录与权限',exact:true}).click();await expect(p.getByLabel('产物来源 turn ID',{exact:true})).toHaveCount(0);assert.equal((await page.request.get(`/api/v1/codex/sessions/${fixture.session_id}/turns/${fixture.turn_id}/artifacts`)).status(),403)
 assert.deepEqual(errors,[]);facts.assertions.push('real original selected body/actor/key/full manifest durable before POST; lost actual202; reload zero automatic POST; explicit same-key full ACK replay durable; independent current completed versus original queued; exact ordinary Import preview SHA/warning and no commit/review/publish; learner hides subject UI and actualGET403; second reload retains full ACK')
 const after=inputs();assert.deepEqual(after,before);writeFileSync(resolve(out,'after.json'),JSON.stringify(after,null,2)+'\n');facts.status='CONTROLLED_ARTIFACT_UI_NATIVE_PASS';facts.finished_at=new Date().toISOString();facts.before_after_exact=true;facts.complete_nonprogress_inputs=before.count;facts.calls=calls;facts.original_command_sha256=sha(JSON.stringify(lost.original));facts.ack_sha256=sha(lost.bytes);facts.browser=await browser.browser().version();facts.boundary='Real Chrome + loopback HTTP owners/SQLite/IndexedDB; fixture executed one explicit memory protocol response and checked local answer materialization. No real CLI, remote model, tool process or host sandbox guarantee.';writeFileSync(resolve(out,'receipt.json'),JSON.stringify(facts,null,2)+'\n');console.log(facts.status)
}catch(e){writeFileSync(resolve(out,'failure.json'),JSON.stringify({source:head,name:e.name,message:e.message,at:new Date().toISOString()},null,2)+'\n');throw e}
finally{await browser?.close();if(api?.pid){const exit=new Promise(ok=>api.once('close',ok));try{process.kill(-api.pid,'SIGTERM')}catch(e){if(e.code!=='ESRCH')throw e}let timer;await Promise.race([exit,new Promise(ok=>{timer=setTimeout(()=>{try{process.kill(-api.pid,'SIGKILL')}catch(e){if(e.code!=='ESRCH')throw e}ok()},5000)})]);clearTimeout(timer)}}
