import { lazy, Suspense, useEffect, useLayoutEffect, useRef, useState } from 'react'
import type { PracticeTarget } from './target'
import type { ReaderTarget } from '../reader/target'
import type { SavedTab } from '../../../../../packages/contracts/generated/types'
import { readPracticeTarget } from './practiceClient'
import { usePracticeSession } from './usePracticeSession'
import { decodePracticeEnvelope } from './practiceDrafts'
import { ResponseComparison, ResponseText } from './ResponseComparison'
import { QuestionEditor } from './QuestionEditor'
import { readLocal, writeLocal, readReaderView, saveReaderView } from '../../workbench/uiCache'
import './practice.css'
const Markdown = lazy(() => import('../../shared/Markdown').then(value => ({ default: value.Markdown })))
export type PracticeViewState = { dirty: boolean; safe: boolean; summary: string; question: string; response: string; assistance: string; questionId: string | null; questions: { id: string; label: string }[] }
const saveLabels = { loading: '正在读取练习会话', saved: '服务端作答已保存', dirty: '作答待同步', saving: '作答保存中…', offline: '作答尚未确认同步', conflict: '作答版本冲突' }
export function PracticeView({ workspace, target, tab, reader, loaded, onScroll, onState, requestedQuestion }: { workspace: string; target: PracticeTarget & { session_id: string }; tab: SavedTab; reader: (target: ReaderTarget) => void; loaded: (title: string, resolved: boolean) => void; onScroll: (offset: number) => void; onState: (state: PracticeViewState) => void; requestedQuestion?: { id: string; sequence: number } }) {
  const session = usePracticeSession(workspace, target)
  const [data, setData] = useState<Awaited<ReturnType<typeof readPracticeTarget>> | null>(null)
  const [referenceError, setReferenceError] = useState('')
  const [viewError, setViewError] = useState('')
  const [markdownReady, setMarkdownReady] = useState(false)
  useEffect(() => { let live = true; void import('../../shared/Markdown').then(() => { if (live) setMarkdownReady(true) }); return () => { live = false } }, [])
  const questionKey = `learning-workbench.${workspace}.${tab.id}.practice-question.v1`
  const [questionId, setQuestion] = useState(readLocal(questionKey))
  const scroll = useRef<HTMLDivElement>(null), ready = useRef(false), offset = useRef(tab.scroll_offset ?? 0)
  const view = useRef(readReaderView(workspace, tab.id))
  const callbacks = useRef({ loaded, onState }); callbacks.current = { loaded, onState }
  useEffect(() => { let live = true; callbacks.current.loaded('', false); void readPracticeTarget(target).then(value => { if (live) { setData(value); callbacks.current.loaded(value.summary.title, true) } }).catch(reason => { if (live) setReferenceError((reason as Error).message) }); return () => { live = false } }, [workspace, JSON.stringify(target)])
  const index = Math.max(0, session.snapshot?.questions.findIndex(question => question.id === questionId) ?? 0)
  const question = session.snapshot?.questions[index]
  const assistance = question && session.snapshot?.assistance.find(item => item.question_id === question.id)
  const answer = session.responses.find(item => item.question_id === question?.id)
  const summary = !session.snapshot ? '练习 · 帮助记录待读取' : session.snapshot.assisted ? '练习 · 已获辅助' : '练习 · 尚无帮助暴露'
  useEffect(() => { callbacks.current.onState({ dirty: session.dirty, safe: session.safe, summary, question: question?.stem_markdown ?? '', response: question?.kind === 'single_choice' ? question.choices?.find(choice => choice.id === answer?.answer)?.text_markdown ?? answer?.answer ?? '' : answer?.answer ?? '', questionId: question?.id ?? null, questions: session.snapshot?.questions.map((item, number) => ({ id: item.id, label: `第 ${number + 1} 题` })) ?? [], assistance: assistance ? `最高提示 ${assistance.highest_hint_level} 级；解答${assistance.solution_revealed ? '已暴露' : '尚未展开'}` : '尚未读取帮助记录' }) }, [session.dirty, session.safe, summary, question?.id, answer?.answer, assistance?.highest_hint_level, assistance?.solution_revealed])
  const saveView = () => { if (!saveReaderView(workspace, tab.id, view.current)) setViewError('练习展开或焦点位置未保存，本页状态仍保留。') }
  useEffect(() => {
    const element = scroll.current
    const toggle = (event: Event) => { if (!ready.current || !(event.target instanceof HTMLDetailsElement) || !event.target.dataset.viewKey) return; view.current.expandedDetails = [...(element?.querySelectorAll<HTMLDetailsElement>('details[data-view-key][open]') ?? [])].map(item => item.dataset.viewKey!); saveView() }
    element?.addEventListener('toggle', toggle, true); return () => element?.removeEventListener('toggle', toggle, true)
  }, [])
  const restoreView = () => { if (!scroll.current || ready.current || !markdownReady) return; for (const detail of scroll.current.querySelectorAll<HTMLDetailsElement>('details[data-view-key]')) detail.open = view.current.expandedDetails.includes(detail.dataset.viewKey!); scroll.current.scrollTop = offset.current; if (view.current.focusKey && !document.querySelector('dialog[open]')) scroll.current.querySelector<HTMLElement>(`[data-focus-key="${CSS.escape(view.current.focusKey)}"]`)?.focus({ preventScroll: true }); ready.current = true }
  const selectQuestion = (id: string) => { setQuestion(id); if (!writeLocal(questionKey, id)) setViewError('当前题号尚未保存到本机；作答草稿独立保留。'); if (scroll.current) scroll.current.scrollTop = 0 }
  useEffect(() => { if (requestedQuestion && session.snapshot?.questions.some(item => item.id === requestedQuestion.id)) selectQuestion(requestedQuestion.id) }, [requestedQuestion?.sequence])
  const disabled = !data || !!referenceError || !session.localReady || session.snapshot?.status !== 'active' || session.busy || !!session.conflict || session.needsRecovery || !!session.localConflicts.length || !!session.localError
  return <div ref={scroll} className="reader-scroll practice-scroll" onScroll={event => { if (ready.current) { offset.current = event.currentTarget.scrollTop; onScroll(offset.current) } }}><article className="reader-content practice-content" onFocusCapture={event => { const element = event.target as HTMLElement; const focusKey = element.dataset.focusKey; if (ready.current && focusKey) { view.current.focusKey = focusKey; saveView() } }}>
    <div className="eyebrow">习题 · 作答会话</div><h1>{data?.summary.title ?? '精确练习会话'}</h1><p className="breadcrumbs">{data ? `${data.course.title} › ${data.lesson.title}` : '正在核验准确教材与小节'}</p><div className="practice-status"><strong>{summary}</strong><span role="status">{session.needsRecovery || session.localConflicts.length ? '本机作答待选择，尚未同步' : saveLabels[session.state]}</span><span>{session.localSaving ? '本机草稿保存中…' : session.safe ? '本机草稿存储可用' : '本机草稿尚未安全保存'}</span></div><p className="muted">会话修订 {session.snapshot?.revision ?? '…'} · {!session.snapshot ? '状态待读取' : session.snapshot.status === 'submitted' ? '已提交' : session.snapshot?.status === 'abandoned' ? '已结束' : '进行中'}。练习不作为独立测试证据；已审且可判定的项按规则评分，未审或无法判定的项保留空分数。</p>
    <div className="reader-actions"><button onClick={() => reader({ course: target.course_ref, lesson: target.lesson_ref })}>返回对应教材</button><button disabled={session.busy || session.state === 'saving'} onClick={() => void session.retry()}>重新读取练习状态</button><button disabled={disabled || session.state === 'saving'} onClick={() => void session.save()}>立即保存作答</button></div>
    {[referenceError, session.error, session.localError, viewError].filter(Boolean).map((text, i) => <p role="alert" className="practice-error" key={i}>{text}</p>)}{session.localError && <button onClick={session.retryLocal}>重试本机作答保存</button>}
    {session.needsRecovery && session.storedEnvelope && <section className="practice-recovery"><h2>发现本机未同步作答</h2><p>先核对原基准与服务端版本；不会自动覆盖现有作答。</p><ResponseText values={session.storedEnvelope.candidate_responses} /><button disabled={session.busy || session.localSaving} onClick={() => void session.restore(session.storedEnvelope!)}>恢复这份本机作答</button></section>}
    {!!session.localConflicts.length && <section className="practice-recovery"><h2>本机作答草稿冲突</h2><p>不同页面的候选均已保留。明确选择后仍会检查服务端基准。</p>{(() => { try { return <ResponseComparison base={session.storedEnvelope?.base_responses ?? null} local={session.responses} remote={decodePracticeEnvelope(session.localConflicts[0].text, workspace).candidate_responses} remoteLabel="其他页面的已存草稿" /> } catch { return <p>已存候选无法解析，保留原记录。</p> } })()}{[session.stored?.text, ...session.localConflicts.map(item => item.text)].filter((text): text is string => !!text).map((text, candidateIndex) => { try { const value = decodePracticeEnvelope(text, workspace); return <details open key={text}><summary>本机候选 {candidateIndex + 1} · 服务基准 r{value.base_revision}</summary><ResponseText values={value.candidate_responses} /><button disabled={session.busy || session.localSaving} onClick={() => void session.resolveLocal(text)}>采用本机候选 {candidateIndex + 1}</button></details> } catch { return <p role="alert" key={candidateIndex}>候选 {candidateIndex + 1} 无法安全解析，原记录保留。</p> } })}</section>}
    {session.conflict && <section className="practice-recovery"><h2>服务端作答冲突 · 三方比较</h2><p>服务端 r{session.conflict.remote.revision}；不会自动覆盖任何一方。</p><ResponseComparison base={session.conflict.base} local={session.conflict.local} remote={session.conflict.remote.responses} /><button disabled={session.busy} onClick={() => session.resolveServer(true)}>保留本页作答并采用新基准</button><button disabled={session.busy} onClick={() => session.resolveServer(false)}>采用服务端作答</button></section>}
    {!session.snapshot && <><p>题面尚未读取。以下只显示本机作答，不推测题目或评分。</p><ResponseText values={session.responses} /></>}
    {session.snapshot && <><nav className="practice-question-nav" aria-label="本次练习题目">{session.snapshot.questions.map((item, number) => <button key={item.id} data-focus-key={`question-nav-${item.id}`} aria-current={question?.id === item.id ? 'step' : undefined} onClick={() => selectQuestion(item.id)}>第 {number + 1} 题{session.responses.some(value => value.question_id === item.id && (value.answer || value.steps_markdown)) ? ' · 已填写' : ''}</button>)}</nav>{question && <><QuestionEditor key={question.id} question={question} response={answer} index={index} disabled={disabled} update={session.update} /><section className="practice-help"><h2>提示与参考解答</h2><p>此题最高提示等级：{assistance?.highest_hint_level ?? 0} · 参考解答{assistance?.solution_revealed ? '已暴露' : '未展开'}。明确请求会留下练习辅助记录。</p><div className="reader-actions">{([1, 2, 3] as const).map(level => <button disabled={!session.commandReady || !!referenceError} key={level} onClick={() => void session.hint(question.id, level)}>获取 {level} 级规则提示</button>)}</div>{session.hints[question.id] && <section><h3>本机规则提示 · {session.hints[question.id].level} 级</h3><p>来源：规则 · {session.hints[question.id].rule_version}</p><Suspense fallback={<p>正在排版已取得的提示…</p>}><Markdown>{session.hints[question.id].markdown}</Markdown></Suspense></section>}{session.solutions[question.id] ? <section className="practice-solution"><h3>参考解答 · {session.solutions[question.id].review_status === 'approved' ? '已审核' : session.solutions[question.id].review_status === 'needs_review' ? '需审查' : '草稿'}</h3><p>这是已明确展开的参考内容；不会因此成为你的独立作答证据。</p><Suspense fallback={<p>正在排版已释放的参考解答…</p>}><Markdown>{session.solutions[question.id].solution_markdown}</Markdown></Suspense><button onClick={() => session.hideSolution(question.id)}>收起参考解答</button></section> : <button disabled={!session.commandReady || !!referenceError} onClick={() => void session.reveal(question.id)}>{assistance?.solution_revealed ? '重新获取已释放的参考解答' : '明确展开参考解答并记录暴露'}</button>}</section></>}
      <section className="practice-submit"><h2>{session.snapshot.status === 'submitted' ? '提交结果' : '提交本次练习'}</h2>{session.snapshot.status === 'active' ? <><p>保存全部作答后可明确提交。提交将冻结作答快照并按支持的确定性规则评分；参考未审、缺失或不支持的项仍待复核且分数为空。</p><button className="primary-button" disabled={!session.commandReady || !!referenceError} onClick={() => void session.submit()}>提交本次练习</button></> : <p>本次作答快照已结束，编辑已停用；未同步候选仍可在本机保留。</p>}{session.snapshot.results && <ul className="practice-results">{session.snapshot.results.map((result, i) => <li key={result.question_ref.id}><strong>第 {i + 1} 题 · {result.status === 'needs_review' ? '需审查' : '已评分'}</strong><span>{result.status === 'needs_review' || result.score == null ? '未评分 · 分数为空' : `分数 ${result.score} / ${result.max_score}`}</span><Suspense fallback={result.feedback_markdown}><Markdown>{result.feedback_markdown}</Markdown></Suspense></li>)}</ul>}</section>
      <details data-view-key="practice-frozen"><summary data-focus-key="practice-frozen">本次练习的冻结引用</summary><p>会话：{target.session_id}</p><code>{target.practice_ref.id} · r{target.practice_ref.revision}<br />SHA-256 {target.practice_ref.sha256}</code><p>已记录帮助事件：{session.snapshot.exposure_event_ids.length} 项。</p></details>{markdownReady && <PracticeReady ready={restoreView} />}</>}
  </article></div>
}
function PracticeReady({ ready }: { ready: () => void }) { useLayoutEffect(ready); return null }
