import { describe, expect, it } from 'vitest'
import { decodePracticeEnvelope, normalizeResponses, practiceDirty, sameResponses, type PracticeEnvelope } from './practiceDrafts'
const value: PracticeEnvelope = { version: 1, workspace_id: 'workspace_original', session_id: 'practice_session_original', practice_ref: { entity: 'practice_set', id: 'practice_original', revision: 1, sha256: 'a'.repeat(64) }, base_revision: 9, base_responses: [{ question_id: 'question_one', answer: '前值' }], candidate_responses: [{ question_id: 'question_one', answer: '🧠é', steps_markdown: '' }] }
describe('practice draft envelopes keep local CAS independent of server revision', () => {
  it('normalizes optional fields and preserves exact session and source base', () => { const decoded = decodePracticeEnvelope(JSON.stringify(value), value.workspace_id); expect(decoded.base_revision).toBe(9); expect(decoded.base_responses[0].steps_markdown).toBe(''); expect(decoded.practice_ref).toEqual(value.practice_ref); expect(practiceDirty(decoded)).toBe(true) })
  it('compares the whole response snapshot regardless of list order, including steps', () => { const a = [{ question_id: 'question_one', answer: '1' }, { question_id: 'question_two', answer: '2', steps_markdown: 'why' }]; expect(sameResponses(a, [...a].reverse())).toBe(true); expect(sameResponses(a, [{ ...a[0], steps_markdown: 'new' }, a[1]])).toBe(false); expect(sameResponses([], a)).toBe(false) })
  it.each(['workspace', 'session', 'revision', 'hash', 'unknown', 'duplicate', 'oversize', 'surrogate'])('rejects %s corruption without silently restoring or truncating', kind => { const input = structuredClone(value); if (kind === 'workspace') input.workspace_id = 'other'; if (kind === 'session') input.session_id = ''; if (kind === 'revision') input.base_revision = 0; if (kind === 'hash') input.practice_ref.sha256 = 'x'; if (kind === 'unknown') Object.assign(input.candidate_responses[0], { accepted_answer: 'secret' }); if (kind === 'duplicate') input.candidate_responses.push(input.candidate_responses[0]); if (kind === 'oversize') input.candidate_responses[0].answer = '字'.repeat(4001); if (kind === 'surrogate') input.candidate_responses[0].answer = '\ud800'; expect(() => decodePracticeEnvelope(JSON.stringify(input), value.workspace_id)).toThrow() })
  it('permits an explicit empty whole response snapshot and Unicode codepoint bounds', () => { expect(normalizeResponses([])).toEqual([]); expect(normalizeResponses([{ question_id: 'question_one', answer: '🧠'.repeat(4000) }])[0].answer).toHaveLength(8000) })
})
