import { useEffect, useState } from 'react'
import type { ContentRef } from '../../../../../packages/contracts/generated/types'
import type { OutlineResponse, PracticeSetSummary } from '../../../../../packages/contracts/generated/api-types'
import { sameRef } from '../reader/target'
import { listPracticeSets } from './practiceClient'
import { practiceHref, type PracticeTarget } from './target'
export function PracticeDirectory({ course, outline, open, expanded, toggle, selection }: { course: ContentRef; outline: OutlineResponse; open: (target: PracticeTarget, pinned?: boolean) => void; expanded: (id: string) => boolean; toggle: (id: string) => void; selection?: { ref: ContentRef; current: string | null; questions: { id: string; label: string }[]; select: (id: string) => void } }) {
  const [items, setItems] = useState<PracticeSetSummary[]>([])
  const [error, setError] = useState(''), [loading, setLoading] = useState(true), [query, setQuery] = useState('')
  useEffect(() => { let live = true; setLoading(true); setItems([]); setError(''); void listPracticeSets(course).then(value => { if (live) setItems(value) }).catch(reason => { if (live) setError((reason as Error).message) }).finally(() => { if (live) setLoading(false) }); return () => { live = false } }, [course.id, course.revision, course.sha256])
  const valid = items.filter(item => outline.sections.some(section => section.lessons.some(lesson => sameRef(lesson.ref, item.lesson_ref))))
  return <nav className="practice-directory" aria-label="习题上下文目录"><label className="directory-search"><span className="sr-only">搜索习题目录标题</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索习题集标题" /></label>{loading && <p role="status">正在读取实际习题目录…</p>}{error && <p role="alert">{error}</p>}{!loading && !error && !valid.length && <p className="directory-empty">尚无已审核习题。此课程修订尚无可匹配的习题集。可导入含习题的学习包；没有创建练习会话。</p>}<ul className="chapters">{outline.sections.map(section => {
    const lessons = section.lessons.map(lesson => ({ ...lesson, sets: valid.filter(item => sameRef(item.lesson_ref, lesson.ref) && item.title.toLocaleLowerCase().includes(query.toLocaleLowerCase())) })).filter(lesson => lesson.sets.length)
    return !!lessons.length && <li key={section.id}><div className="chapter-row"><button className="disclosure" aria-expanded={!!query || expanded(section.id)} onClick={() => toggle(section.id)} aria-label={`展开习题章：${section.title}`}>{expanded(section.id) ? '⌄' : '›'}</button><span>{section.title}</span></div>{(!!query || expanded(section.id)) && <ul className="lessons">{lessons.map(lesson => <li key={lesson.ref.id}><strong>{lesson.title}</strong><ul className="block-links">{lesson.sets.map(item => { const target = { practice_ref: item.ref, course_ref: course, lesson_ref: item.lesson_ref }; return <li key={`${item.ref.id}:${item.ref.revision}`}><a href={practiceHref(target)} onClick={event => { event.preventDefault(); open(target) }} onDoubleClick={() => open(target, true)}>{item.title}</a><small> {item.question_count} 题 · r{item.ref.revision} · 含需审查内容</small>{selection && sameRef(selection.ref, item.ref) && <ul className="practice-directory-questions">{selection.questions.map(question => <li key={question.id}><button aria-current={selection.current === question.id ? 'step' : undefined} onClick={() => selection.select(question.id)}>{question.label}</button></li>)}</ul>}</li> })}</ul></li>)}</ul>}</li>
  })}</ul>{query && !loading && !valid.some(item => item.title.toLocaleLowerCase().includes(query.toLocaleLowerCase())) && <p>没有匹配的习题集标题。</p>}</nav>
}
