import { lazy, Suspense } from 'react'
import type { QuestionPublic, ResponseDraft } from '../../../../../packages/contracts/generated/types'
const Markdown = lazy(() => import('../../shared/Markdown').then(value => ({ default: value.Markdown })))
const skills: Record<QuestionPublic['skill'], string> = { recall: '概念回忆', compute: '计算', derive: '推导', explain: '解释', transfer: '迁移' }
const labels: Record<QuestionPublic['kind'], string> = { single_choice: '单选题', text_blank: '文本填空', numeric: '数值填空', calculation: '计算与证明', expression: '表达式' }
export function QuestionEditor({ question, response, index, disabled, update }: { question: QuestionPublic; response?: ResponseDraft; index: number; disabled: boolean; update: (response: ResponseDraft) => void }) {
  const answer = response?.answer ?? '', steps = response?.steps_markdown ?? ''
  return <section className="practice-question" data-question-id={question.id}><h2>第 {index + 1} 题 · {labels[question.kind]}</h2><p className="muted">修订 {question.revision} · {skills[question.skill]} · 导入内容尚需审查</p><details data-view-key={`question-identity-${question.id}`}><summary data-focus-key={`question-identity-${question.id}`}>题目引用与概念</summary><code>{question.id} · r{question.revision}</code><p>概念：{question.concept_ids.join('、')}</p></details><Suspense fallback={<p role="status">正在排版题面…</p>}><div className="practice-stem"><Markdown sourceKey={`question-${question.id}`}>{question.stem_markdown}</Markdown></div></Suspense><p className="practice-instructions">作答格式：{question.input_instructions}</p>
    <fieldset disabled={disabled}><legend>第 {index + 1} 题作答</legend>{question.kind === 'single_choice' ? <div className="practice-choices">{question.choices?.map(choice => <label key={choice.id}><input type="radio" name={`answer-${question.id}`} value={choice.id} checked={answer === choice.id} onChange={() => update({ question_id: question.id, answer: choice.id, steps_markdown: steps })} /><span><Suspense fallback={choice.text_markdown}><Markdown>{choice.text_markdown}</Markdown></Suspense></span></label>)}<button type="button" onClick={() => update({ question_id: question.id, answer: '', steps_markdown: steps })}>清除此题选择</button></div> : <label className="practice-input">答案<textarea aria-label={`第 ${index + 1} 题答案`} value={answer} rows={question.kind === 'calculation' ? 4 : 2} onChange={event => update({ question_id: question.id, answer: event.target.value, steps_markdown: steps })} /></label>}<label className="practice-input">推导步骤（可选）<textarea aria-label={`第 ${index + 1} 题推导步骤`} value={steps} rows={4} onChange={event => update({ question_id: question.id, answer, steps_markdown: event.target.value })} /></label><small>答案最多 4,000 个字符；步骤最多 20,000 个字符。表达式按原文保存，尚不做评分判定。</small></fieldset>
  </section>
}
