import { describe, expect, it } from 'vitest'
import { emptySession, tabIdentity } from '../../workbench/model'
import { openPractice, practiceContext, practiceHref, readPracticeTarget, type PracticeTarget } from './target'
const target: PracticeTarget = { practice_ref: { entity: 'practice_set', id: 'practice_original', revision: 1, sha256: 'a'.repeat(64) }, course_ref: { entity: 'course', id: 'course_original', revision: 1, sha256: 'b'.repeat(64) }, lesson_ref: { entity: 'lesson', id: 'lesson_original', revision: 1, sha256: 'c'.repeat(64) } }
describe('practice targets use frozen references and actual session mode', () => {
  it('separates preview, two real practice sessions and revisions without adding hash to identity', () => { const preview = practiceContext(target), first = practiceContext({ ...target, session_id: 'practice_session_one' }), second = practiceContext({ ...target, session_id: 'practice_session_two' }); expect(new Set([preview, first, second].map(tabIdentity)).size).toBe(3); const bad = { ...first, active_ref: { ...first.active_ref, sha256: 'd'.repeat(64) } }; expect(tabIdentity(first)).toBe(tabIdentity(bad)) })
  it('rejects a frozen parent conflict without changing course or existing responses tab', () => { const initial = openPractice(emptySession(), { ...target, session_id: 'practice_session_one' }, true, () => true).session; const changed = { ...target, session_id: 'practice_session_one', lesson_ref: { ...target.lesson_ref, sha256: 'd'.repeat(64) } }; const result = openPractice(initial, changed, true, () => true); expect(result.kind).toBe('conflict'); expect(result.session).toBe(initial) })
  it('round-trips exact deep links and rejects unknown or assessment masquerading fields', () => { expect(readPracticeTarget(practiceHref(target).slice(1))).toEqual(target); expect(() => readPracticeTarget('?practice=' + encodeURIComponent(JSON.stringify({ ...target, independent: true })))).toThrow(); expect(() => readPracticeTarget('?practice=' + encodeURIComponent(JSON.stringify({ ...target, practice_ref: { ...target.practice_ref, entity: 'assessment' } })))).toThrow() })
})
