import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, expect, test, vi } from 'vitest'
import { ReviewMaterialLinks } from './ReviewMaterialLinks'
import { reviewResult, course, lesson, block } from './review.testdata'
const source = vi.hoisted(() => ({ course: vi.fn(), lesson: vi.fn(), block: vi.fn(), generation: 0 }))
vi.mock('../../api/client', () => ({ getSessionGeneration: () => source.generation }))
vi.mock('../reader/contentClient', () => ({ readCourse: (...args: unknown[]) => source.course(...args), readLesson: (...args: unknown[]) => source.lesson(...args), readBlock: (...args: unknown[]) => source.block(...args) }))
afterEach(cleanup)
beforeEach(() => { source.generation = 0; source.course.mockReset().mockResolvedValue({ lesson_refs: [lesson] }); source.lesson.mockReset().mockResolvedValue({ block_refs: [block] }); source.block.mockReset().mockResolvedValue({ block: { kind: 'definition' } }) })
test('verifies the exact parent membership and preserves all full references when opening a definition anchor', async () => { const open = vi.fn(); render(<ReviewMaterialLinks group={reviewResult().review_materials[0]} allowed open={open} />); fireEvent.click(screen.getByRole('button')); await waitFor(() => expect(open).toHaveBeenCalledWith({ course, lesson, block, view: 'lesson' }, true)); expect(source.course).toHaveBeenCalledWith(course); expect(source.block).toHaveBeenCalledWith(block) })
test('does not navigate when exact membership fails or permission changes while the body read is in flight', async () => { source.lesson.mockResolvedValueOnce({ block_refs: [{ ...block, sha256: '0'.repeat(64) }] }); const open = vi.fn(); const view = render(<ReviewMaterialLinks group={reviewResult().review_materials[0]} allowed open={open} />); fireEvent.click(screen.getByRole('button')); await screen.findByRole('alert'); expect(open).not.toHaveBeenCalled(); expect(source.block).not.toHaveBeenCalled(); view.unmount(); let finish!: (value: unknown) => void; source.block.mockImplementation(() => new Promise(resolve => { finish = resolve })); render(<ReviewMaterialLinks group={reviewResult().review_materials[0]} allowed open={open} />); fireEvent.click(screen.getByRole('button')); await waitFor(() => expect(finish).toBeTypeOf('function')); source.generation++; finish({ block: { kind: 'worked_example' } }); await waitFor(() => expect(screen.queryByRole('status')).toBeNull()); expect(open).not.toHaveBeenCalled() })
