import { useEffect, useState } from 'react'
import type { ContentRef, ImpactObjectDecisionReceipt as Receipt, ImpactObjectDecisionWrite as Write } from '../../../../../packages/contracts/generated/api-types'
import { Dialog } from '../../workbench/Controls'
import { sameValue } from '../providers/providerSchema'
import { useContentImpacts } from './useContentImpacts'
import { artifacts, classification, type Basis } from './schema'
import { discard } from './memory'
import type { ImpactPort } from './client'
import './impacts.css'
export type ImpactState = { dirty: boolean; safe: boolean; isolated: boolean }
const labels = { no_revision_needed: '本事件下不需修订', new_revision_required: '需要另行修订' }
function Ref({ value }: { value: ContentRef }) { return <code>{value.entity} · {value.id} · 修订 {value.revision}<br />SHA-256 {value.sha256}</code> }
function Decision({ value }: { value: Receipt }) { return <details><summary>{value.target_id} · 决定版本 {value.decision_revision} · {labels[value.decision]}</summary><p>{value.classification === 'exact_ref' ? '冻结的明确引用链关联' : '仅按对象标识列入的保守候选，不证明精确依赖或语义失效'}；记录时间 {value.decided_at}</p><p>原理由：{value.reason}</p><Ref value={value.observed_ref} /><p>当时正文校验值：{value.target_body_sha256 ?? '此对象无独立正文'}。</p><p>操作者 <code>{value.actor_session_id}</code>；回执校验值 <code>{value.receipt_sha256}</code></p>{value.evidence_artifacts.map(item => <p key={item.id}>已核验附件 <code>{item.id} · {item.sha256}</code></p>)}</details> }
function Form({ frozen, busy, submit, cancel, state }: { frozen: Basis; busy: boolean; submit(decision: Write['decision'], reason: string, ids: string[]): Promise<void>; cancel(): void; state(value: boolean): void }) {
  const [decision, setDecision] = useState<Write['decision'] | ''>(''), [reason, setReason] = useState(''), [ids, setIds] = useState(''), [confirmed, setConfirmed] = useState(false), [error, setError] = useState('')
  useEffect(() => { state(true); return () => state(false) }, [state])
  const send = async () => { try { if (!decision || !reason.trim() || !confirmed) return; await submit(decision, reason, artifacts(ids)) } catch (e) { setError(e instanceof Error ? e.message : '表单无效。') } }
  return <fieldset disabled={busy} aria-label="本次人工内容决定"><legend>已明确采用的依据</legend><p>事件 <code>{frozen.view.event_id}</code>；对象 <code>{frozen.target_id}</code>；原决定版本 {frozen.view.target_decision_head}。</p><Ref value={frozen.current_ref} /><p>事件快照校验值 <code>{frozen.view.event_snapshot_sha256}</code></p><p>{classification(frozen.view, frozen.current_ref) === 'exact_ref' ? '这一修订处于冻结的明确引用链中。' : '这一当前修订仅按对象标识关联，不能当作精确依赖。'}</p><label>本次人工决定<select aria-label="本次人工决定" value={decision} onChange={e => { setDecision(e.target.value as typeof decision); setConfirmed(false) }}><option value="">请选择，不默认认可</option><option value="no_revision_needed">本事件下不需修订</option><option value="new_revision_required">需要另行修订</option></select></label><label>决定理由<textarea value={reason} onChange={e => { setReason(e.target.value); setConfirmed(false) }} /></label><p>理由须为 1–2000 个字符。决定仅针对这一事件与对象，不批准草稿，不替其他复核完成。</p><label>已授权证据附件标识（可空，每行一个）<textarea value={ids} onChange={e => { setIds(e.target.value); setConfirmed(false) }} /></label><p>最多 32 个且不能重复；服务端会核验工作区、读取权限和原件字节。</p><label><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />我已比对原变更、当前对象和冻结依据，明确追加这次人工判断。</label><button disabled={!confirmed || !decision || !reason.trim() || Array.from(reason).length > 2000} onClick={() => void send()}>明确保存内容决定</button><button onClick={cancel}>丢弃未提交表单与冻结依据</button>{error && <p role="alert">{error}</p>}</fieldset>
}
export function ContentImpactsPanel({ workspace, paused, onState, port }: { workspace: string; paused: boolean; onState?(value: ImpactState): void; port?: ImpactPort }) {
  const data = useContentImpacts(workspace, paused, port), [filter, setFilter] = useState(''), [limit, setLimit] = useState('20'), [formDirty, setFormDirty] = useState(false), [discarding, setDiscarding] = useState(false)
  const dirty = formDirty || data.pendingMemory || data.commands.some(c => !c.ack && !c.rejection), safe = !data.busy && !data.pendingMemory
  useEffect(() => { onState?.({ dirty, safe, isolated: data.pendingMemory && !data.busy }) }, [dirty, safe, data.pendingMemory, data.busy, onState])
  useEffect(() => { const protect = (e: BeforeUnloadEvent) => { if (formDirty) { e.preventDefault(); e.returnValue = '' } }; addEventListener('beforeunload', protect); return () => removeEventListener('beforeunload', protect) }, [formDirty])
  const value = data.reading?.value, listed = data.listing
  const targets = value ? [...new Set([...value.pending_target_ids, ...value.action_required_target_ids, ...data.reading!.history.map(x => x.target_id)])].sort() : []
  const newList = () => { if (!/^[1-9][0-9]*$/.test(limit) || Number(limit) > 100) return; void data.discover(filter.trim() || null, Number(limit)) }
  return <section className="content-impacts" aria-label="内容变更影响复核"><h3>内容变更影响复核</h3><p>查看已发布修订造成的影响，逐个对象记录人工判断。内容决定不会代替笔记重锚、学习证据适用性复核或索引重建；“需要另行修订”仍是待办，不会自动发布或改变父级引用。</p><button disabled={data.busy || formDirty} onClick={() => void data.refresh()}>重新核验内容复核权限</button>{!data.ready && <p>仅当前作者且测试策略允许时可以读取。权限变化时保护内容会收起，原决定仍保留。</p>}{data.busy && <p role="status">正在读取或保存…</p>}{data.error && <p role="status">{data.error}</p>}
    {data.pendingMemory && <div role="alert"><p>原决定或已收到的回执尚未安全保存到本机，已留在本页隔离内存。请保持页面打开；当前权限不足时仅显示这一恢复提示。</p><button disabled={!data.canSaveMemory || data.busy} onClick={() => void data.saveMemory()}>只保存原会话的内容决定内存</button><button disabled={data.busy} onClick={() => setDiscarding(true)}>明确放弃未保存的内容决定内存</button></div>}
    {data.ready && <><section aria-label="发现已发布内容变更"><label>按原变更对象标识筛选（留空查看全部）<input value={filter} onChange={e => setFilter(e.target.value)} /></label><label>每页事件数<input value={limit} inputMode="numeric" onChange={e => setLimit(e.target.value)} /></label><button disabled={data.busy || !/^[1-9][0-9]*$/.test(limit) || Number(limit) > 100} onClick={newList}>从第一页读取内容变更</button><p>筛选只匹配原变更对象，不按标题或受影响对象扩大范围。翻页沿用原筛选与事件范围；新发布的事件须从第一页重新读取。</p>
      {listed && <><p>本轮已采用筛选：<code>{listed.filter ?? '全部对象'}</code>；每页 {listed.limit}。各页状态按各自读取时的当前对象计算。</p>{listed.items.length === 0 && <p>这一筛选下没有返回可读内容变更；首次创建也可能没有影响事件。</p>}{listed.items.map(item => <article key={item.event_id}><h4>{item.old_ref.id} · 修订 {item.old_ref.revision} → {item.new_ref.revision}</h4><p>事件 <code>{item.event_id}</code>；{item.evidence_version === 'legacy_unverified' ? '旧事件，精确依据未验证，仅可查看' : '发布时已冻结引用依据'}。</p><p>待人工复核 {item.pending_target_ids.length} 个；需要另行修订 {item.action_required_target_ids.length} 个。两个数字均为零也不表示其他业务已完成。</p><button disabled={data.busy} onClick={() => void data.read(item.event_id)}>查看影响详情 {item.event_id}</button></article>)}{listed.next_cursor && <button disabled={data.busy} onClick={() => void data.discover(listed.filter, listed.limit, true)}>沿原筛选读取下一页事件</button>}</>}
    </section></>}
    {value && <section aria-label="本次读取的内容影响详情"><h4>本次读取的对象状态</h4><p>事件 <code>{value.event_id}</code>。这次读取与历史决定回执分别保留；保存决定后须重新读取才能查看当前状态。</p><dl><dt>原变更修订</dt><dd><Ref value={value.old_ref} /></dd><dt>新发布修订</dt><dd><Ref value={value.new_ref} /></dd></dl>{value.evidence_version === 'legacy_unverified' && <p role="alert">这是迁移前旧事件：未保存可验证的精确引用依据，只能查看保守影响范围，不能提交决定。</p>}<p>待复核：{value.pending_target_ids.join('、') || '无'}；需另行修订：{value.action_required_target_ids.join('、') || '无'}。</p><details><summary>原影响范围与引用依据</summary><p>保守对象范围：{value.affected_ids.join('、')}。原变更对象已由新修订处理，不在逐对象决定目标中；笔记、路线等其他业务仍保留自己的处理状态。</p><p>仅按标识列入的候选：{value.conservative_only_ids.join('、') || '无'}。</p>{value.exact_dependency_refs.map(ref => <p key={`${ref.entity}:${ref.id}:${ref.revision}`}><Ref value={ref} /></p>)}<p>事件快照校验值 <code>{value.event_snapshot_sha256 ?? '旧事件未验证'}</code></p></details>
      <h4>选择实际返回的内容对象</h4>{targets.map(id => <button key={id} disabled={data.busy} onClick={() => void data.read(value.event_id, id)}>读取对象当前依据 {id}</button>)}<p>已处理的对象可从下面已读历史记录再次选择；更多历史须继续翻页。</p>{data.reading?.target && data.reading.current_ref && <div aria-label="所选对象当前依据"><p>对象 <code>{data.reading.target}</code>；当前决定版本 {value.target_decision_head}。</p><Ref value={data.reading.current_ref} />{!data.canAdopt && <p>已有提交尝试，请重新读取此对象后再采用依据；历史读取仍保留供比对。</p>}<button disabled={data.busy || data.pendingMemory || formDirty || !data.canAdopt || value.evidence_version === 'legacy_unverified'} onClick={data.adopt}>采用本次对象依据准备决定</button></div>}
      {data.frozen && (data.frozen.target_id !== data.reading?.target || !sameValue(data.frozen.current_ref, data.reading?.current_ref) || data.frozen.view.target_decision_head !== value.target_decision_head || data.frozen.view.event_id !== value.event_id) && <p role="alert">新读取与已采用依据不同。下方表单仍保留原依据；需先明确丢弃表单，再采用新依据，不能自动替换。</p>}<h4>原人工决定历史</h4>{data.reading!.history.map(item => <Decision key={`${item.target_id}:${item.decision_revision}`} value={item} />)}{value.next_cursor && <button disabled={data.busy} onClick={() => void data.read(value.event_id, data.reading!.target, true)}>继续读取决定历史</button>}<button disabled={data.busy} onClick={() => void data.read(value.event_id, data.reading!.target)}>重新读取此事件当前状态</button>
    </section>}
    {data.frozen && <Form key={data.basisVersion} frozen={data.frozen} busy={data.busy || data.pendingMemory} submit={data.submit} cancel={data.clearBasis} state={setFormDirty} />}
    {data.ready && <section aria-label="本机保留的内容决定"><h4>原决定与历史回执</h4>{data.commands.length === 0 && <p>暂无本机原决定。</p>}{data.commands.map(command => <details key={command.command_id}><summary>{command.ack ? '原决定回执已保存' : command.rejection ? `原决定被拒绝（${command.rejection.status}）` : '决定结果未知，原提交内容已保留'} · {command.command_id}</summary><p>事件 <code>{command.basis.view.event_id}</code>；对象 <code>{command.body.target_id}</code>；原决定版本 {command.body.expected_decision_revision}。</p><p>{labels[command.body.decision]}；原理由：{command.body.reason}</p><p>附件标识：{command.body.evidence_artifact_ids.join('、') || '无'}。</p><Ref value={command.body.observed_ref} />{command.ack && <Decision value={command.ack} />}<button disabled={!data.canReplay(command) || data.busy || data.pendingMemory} onClick={() => void data.execute(command)}>按原提交内容重试 {command.command_id}</button><button disabled={data.busy} onClick={() => void data.read(command.basis.view.event_id, command.body.target_id)}>另行读取原决定对象 {command.command_id}</button>{!data.canReplay(command) && <p>页面或授权状态已改变，这份原决定只读保留，不能换身份或更换提交标识盲目重发。</p>}</details>)}</section>}
    {discarding && <Dialog title="放弃未保存的内容决定内存" close={() => setDiscarding(false)}><p>明确删除本工作区全部尚未保存的内容决定或回执内存，不能撤销已发生的服务端决定，也不能确认未知结果。已经保存的原决定不删除。</p><button onClick={() => { discard(workspace); setDiscarding(false) }}>确认放弃内容决定隔离内存</button><button onClick={() => setDiscarding(false)}>继续保留</button></Dialog>}
  </section>
}
