import { beforeEach, expect, test, vi } from 'vitest'
import type { AttemptSnapshot } from '../../../../../packages/contracts/generated/api-types'
import { readAttempt } from './assessmentClient'
import type { AssessmentTarget } from './target'
const transport = vi.hoisted(() => vi.fn())
vi.mock('../../api/client', () => ({ request: (...args: unknown[]) => transport(...args) }))
const target: AssessmentTarget & { attempt_id: string } = { assessment_ref: { entity: 'assessment', id: 'assessment_probe', revision: 1, sha256: 'a'.repeat(64) }, course_ref: { entity: 'course', id: 'course_probe', revision: 1, sha256: 'b'.repeat(64) }, attempt_id: 'attempt_probe' }
// Deliberately synthetic typed application data for client coherence checks;
// actual repository/reference validation is covered by the native HTTP cases.
function snapshot(revision: number): AttemptSnapshot { return { id: target.attempt_id, workspace_id: 'workspace_probe', assessment_ref: target.assessment_ref, revision, created_at: '2026-09-14T00:00:00Z', status: 'active', policy: { mode: 'independent', tutor_scope: 'operation_help_only', allow_web: false, allow_materials: false, solution_release: 'after_submit' }, questions: [{ id: 'question_probe', revision: 1, kind: 'text_blank', stem_markdown: '原创测试文本', concept_ids: ['concept_probe'], skill: 'recall', exposure_group: 'exposure_probe', input_instructions: '填写文本' }], preflight: { course_refs: [target.course_ref!], question_kinds: [{ kind: 'text_blank', count: 1 }], target_concept_refs: [{ entity: 'concept', id: 'concept_probe', revision: 1, sha256: 'c'.repeat(64) }], grading: { status: 'unreviewed', approved_count: 0, draft_count: 0, needs_review_count: 1, missing_count: 0, damaged_count: 0, reason_codes: [] }, prior_seen: { status: 'known', questions: [{ question_ref: { entity: 'question', id: 'question_probe', revision: 1, sha256: 'd'.repeat(64) }, state: 'unseen', reason_codes: [] }] }, startable: true, start_block_reason_codes: [] }, grading_status: 'not_graded' } }
beforeEach(() => { transport.mockReset() })
test('a changed revision between reads is retried before exposing a combined snapshot', async () => { transport.mockResolvedValueOnce(snapshot(1)).mockResolvedValueOnce({ revision: 2, responses: [], saved_at: null }).mockResolvedValueOnce(snapshot(2)).mockResolvedValueOnce({ revision: 2, responses: [{ question_id: 'question_probe', answer: '实际同版' }], saved_at: null }); const value = await readAttempt('workspace_probe', target); expect(value.snapshot.revision).toBe(2); expect(value.responses[0].answer).toBe('实际同版'); expect(transport).toHaveBeenCalledTimes(4) })
test('continuous concurrent changes stop at a bounded count instead of mixing revisions', async () => { transport.mockImplementation(async (route: string) => route.endsWith('/responses') ? { revision: 2, responses: [], saved_at: null } : snapshot(1)); await expect(readAttempt('workspace_probe', target)).rejects.toThrow('尚未读到同一版本'); expect(transport).toHaveBeenCalledTimes(8) })
test('a forged parent is rejected before fetching answers', async () => { transport.mockResolvedValueOnce(snapshot(1)); await expect(readAttempt('workspace_probe', { ...target, course_ref: { ...target.course_ref!, sha256: '0'.repeat(64) } })).rejects.toThrow('冻结父链'); expect(transport).toHaveBeenCalledTimes(1) })
test('another workspace or unassigned response never enters the visible snapshot', async () => { transport.mockResolvedValueOnce({ ...snapshot(1), workspace_id: 'workspace_other' }); await expect(readAttempt('workspace_probe', target)).rejects.toThrow(); transport.mockResolvedValueOnce(snapshot(1)).mockResolvedValueOnce({ revision: 1, responses: [{ question_id: 'question_other', answer: '不属于本实例' }], saved_at: null }); await expect(readAttempt('workspace_probe', target)).rejects.toThrow('未分配的题号') })
