import { useEffect, useRef, useState } from 'react'
import type { AssessmentSummary, AttemptSnapshot } from '../../../../../packages/contracts/generated/api-types'
import { request } from '../../api/client'
import { navigationItems, type Navigation, type Session } from '../../workbench/model'
import { sameRef } from '../reader/target'
import { listAssessments } from './assessmentClient'
import type { AssessmentTarget } from './target'
import type { AssessmentViewState } from './AssessmentView'
import { modeLabels, statusLabels } from './PreflightFacts'
export function AssessmentNavigation({ session, workspace, locked, known, open, resume, navigate, aux, selection, select, set }: { session: Session; workspace: string | null; locked: string | null; known: boolean; open: (target: AssessmentTarget, pinned?: boolean) => void; resume: (value: AttemptSnapshot) => void; navigate: (key: Navigation) => void; aux: (name: string) => void; selection?: AssessmentViewState; select: (id: string) => void; set: (change: (old: Session) => Session) => void }) {
  const [items, setItems] = useState<AssessmentSummary[]>([]), [error, setError] = useState(''), [loading, setLoading] = useState(false), [global, setGlobal] = useState(false), [version, setVersion] = useState(0)
  const scroll = useRef<HTMLDivElement>(null), ready = useRef(false)
  const expansionKey = (item: AssessmentSummary) => `assessment:${session.course_ref?.id ?? 'global'}:${item.ref.id}:${item.ref.revision}`
  const latest = useRef(resume); latest.current = resume
  useEffect(() => {
    if (!workspace || !known || locked) { setItems([]); return }
    let live = true; setLoading(true); setError('')
    void listAssessments(global ? undefined : session.course_ref ?? undefined).then(value => { if (live) setItems(value) }).catch(reason => { if (live) setError((reason as Error).message) }).finally(() => { if (live) setLoading(false) })
    return () => { live = false }
  }, [workspace, session.course_ref?.sha256, global, version, locked, known])
  useEffect(() => { ready.current = false }, [session.course_ref?.sha256, global])
  useEffect(() => { if (!loading && scroll.current && !ready.current) { scroll.current.scrollTop = session.directory_scroll; ready.current = true } }, [loading, items, locked])
  useEffect(() => { const ref = session.tabs.find(tab => tab.id === session.active_tab_id)?.context.active_ref; const item = items.find(item => sameRef(item.ref, ref)); if (item && !session.expanded_keys.includes(expansionKey(item))) set(old => ({ ...old, expanded_keys: [...old.expanded_keys, expansionKey(item)] })) }, [items, session.active_tab_id])
  const resumeActive = async () => { if (!locked) return; setError(''); try { const value = await request('GET /api/v1/attempts/{id}', undefined, undefined, { path: { id: locked } }); if (value.workspace_id !== workspace || value.id !== locked) throw new Error('作答实例与当前工作区不同。'); latest.current(value) } catch (reason) { setError((reason as Error).message) } }
  const target = (item: AssessmentSummary): AssessmentTarget => ({ assessment_ref: item.ref, ...(session.course_ref && item.preflight.course_refs.some(ref => sameRef(ref, session.course_ref)) ? { course_ref: session.course_ref } : {}) })
  return <div className="navigation-content"><section className="course-summary"><div className="eyebrow">测试工作区</div><h2>{locked ? '独立测试进行中' : '测试与作答记录'}</h2><p>{locked ? '工作区学科材料暂受限制；自己的测试可继续、提交或放弃。' : session.course_ref && !global ? `所选课程修订 ${session.course_ref.revision} 的准确关联测试` : '所有可访问测试，包括尚未关联课程的测试。'}</p>{!locked && <button onClick={() => aux('课程切换')}>选择课程</button>}</section><nav aria-label="学习主导航" className="primary-navigation">{navigationItems.map(item => <button key={item.id} aria-current={session.navigation === item.id ? 'page' : undefined} onClick={() => navigate(item.id)}><span className="nav-icon" aria-hidden="true">{item.glyph}</span><span>{item.label}</span></button>)}</nav><section className="directory-section assessment-directory"><div className="directory-heading"><h2>测试上下文目录</h2></div><div ref={scroll} className="directory-scroll" onScroll={event => { if (ready.current) { const value = event.currentTarget.scrollTop; set(old => old.directory_scroll === value ? old : { ...old, directory_scroll: value }) } }}>{!known && <p role="status">正在核验工作区测试策略…</p>}{error && <p role="alert">{error}</p>}{locked ? <><button onClick={() => void resumeActive()}>返回进行中的独立测试</button>{selection?.questions.length ? <nav aria-label="测试题号目录">{selection.questions.map(item => <button key={item.id} aria-current={selection.questionId === item.id ? 'step' : undefined} onClick={() => select(item.id)}>{item.label}</button>)}</nav> : null}</> : <><button onClick={() => setGlobal(value => !value)}>{global ? '仅看当前课程测试' : '查看全部测试（含未关联课程）'}</button><button onClick={() => setVersion(value => value + 1)}>刷新测试目录与记录</button>{loading && <p role="status">正在读取真实测试目录…</p>}{!loading && !items.length && <p>尚无已发布测试。可导入包含真实测试的学习包；未审核内容将明确标注。</p>}{items.map(item => <details key={`${item.ref.id}:${item.ref.revision}`} open={session.expanded_keys.includes(expansionKey(item))}><summary onClick={event => { event.preventDefault(); const key = expansionKey(item); set(old => ({ ...old, expanded_keys: old.expanded_keys.includes(key) ? old.expanded_keys.filter(value => value !== key) : [...old.expanded_keys, key] })) }}>{item.title} · r{item.ref.revision}</summary><p>{item.question_count} 题 · {item.preflight.grading.status === 'reviewed' ? '参考已审核' : item.preflight.grading.status === 'unavailable' ? '当前不可开始' : '参考需审查'}</p><button onClick={() => open(target(item), true)}>查看测试范围：{item.title}</button><ul className="assessment-records">{item.recent_attempts.map(attempt => <li key={attempt.id}><button onClick={() => open({ ...target(item), attempt_id: attempt.id }, true)}>{modeLabels[attempt.mode]} · {statusLabels[attempt.status]} · {new Date(attempt.created_at).toLocaleString()}</button></li>)}</ul>{item.recent_attempts_truncated && <p>仅显示最近 10 次记录，更早实例仍可用其准确链接恢复。</p>}{!item.recent_attempts.length && <p>尚无作答记录。</p>}</details>)}</>}</div></section><footer className="navigation-tools">{['笔记', '创作', '设置'].map(name => <button key={name} onClick={() => aux(name)}>{name}</button>)}</footer></div>
}
