import { expect, test } from 'vitest'
import { assessmentDirty, decodeAssessmentEnvelope, type AssessmentEnvelope } from './assessmentDrafts'
import { sameResponses } from '../../shared/responses'
const envelope = (): AssessmentEnvelope => ({ version: 1, workspace_id: 'workspace_original', attempt_id: 'attempt_original', assessment_ref: { entity: 'assessment', id: 'assessment_original', revision: 2, sha256: 'a'.repeat(64) }, course_ref: { entity: 'course', id: 'course_original', revision: 1, sha256: 'b'.repeat(64) }, policy: { policy_version: '1.0.0', mode: 'independent', allow_web: false, allow_materials: false, tutor_scope: 'operation_help_only', solution_release: 'after_submit' }, base_revision: 3, base_status: 'active', base_responses: [], candidate_responses: [{ question_id: 'question_original', answer: '🧠é', steps_markdown: '' }] })
const decode = (value: unknown) => decodeAssessmentEnvelope(JSON.stringify(value), 'workspace_original')
test('keeps server revision separate from durable record revision and preserves codepoints', () => { const value = decode(envelope()); expect(value.base_revision).toBe(3); expect(value.candidate_responses[0].answer).toBe('🧠é'); expect(assessmentDirty(value)).toBe(true) })
test.each(['workspace_id', 'attempt_id', 'assessment_ref', 'policy', 'base_revision', 'candidate_responses'])('rejects a missing %s without replacing the raw candidate', field => { const value: Record<string, unknown> = { ...envelope() }; delete value[field]; expect(() => decode(value)).toThrow() })
test('does not trust another workspace, unknown fields, hash substitutes or silently elevated policy', () => { expect(() => decode({ ...envelope(), workspace_id: 'workspace_other' })).toThrow(); expect(() => decode({ ...envelope(), accepted_answers: ['private'] })).toThrow(); expect(() => decode({ ...envelope(), assessment_ref: { ...envelope().assessment_ref, sha256: 'bad' } })).toThrow(); expect(() => decode({ ...envelope(), policy: { ...envelope().policy, allow_web: true } })).toThrow() })
test('terminal envelopes retain unsynced candidates but do not become active', () => { const value = decode({ ...envelope(), base_status: 'submitted' }); expect(value.base_status).toBe('submitted'); expect(assessmentDirty(value)).toBe(true) })
test('whole-response snapshots reject duplicate questions and invalid Unicode', () => { const value = envelope(); expect(() => decode({ ...value, candidate_responses: [...value.candidate_responses, ...value.candidate_responses] })).toThrow(); expect(() => decode({ ...value, candidate_responses: [{ question_id: 'question_original', answer: '\ud800' }] })).toThrow(); expect(sameResponses([{ question_id: 'question_original', answer: '' }], [{ question_id: 'question_original', answer: '', steps_markdown: '' }])).toBe(true) })
