import { expect, test } from 'vitest'
import { assessmentContext, assessmentHref, assessmentTarget, openAssessment, readAssessmentTarget, type AssessmentTarget } from './target'
import { emptySession, tabIdentity } from '../../workbench/model'
const target: AssessmentTarget = { assessment_ref: { entity: 'assessment', id: 'assessment_original', revision: 1, sha256: 'a'.repeat(64) }, course_ref: { entity: 'course', id: 'course_original', revision: 1, sha256: 'b'.repeat(64) }, attempt_id: 'attempt_original' }
test('round-trips a global unassociated or course-frozen attempt without current guesses', () => { expect(readAssessmentTarget(assessmentHref(target).slice(1))).toEqual(target); const global = { assessment_ref: target.assessment_ref, attempt_id: target.attempt_id }; expect(assessmentTarget(assessmentContext(global))).toEqual(global) })
test('preview and actual instances have distinct prescribed identities; hashes do not change identity', () => { expect(tabIdentity(assessmentContext(target))).not.toBe(tabIdentity(assessmentContext({ ...target, attempt_id: undefined }))); expect(tabIdentity(assessmentContext(target))).not.toBe(tabIdentity(assessmentContext({ ...target, attempt_id: 'attempt_two' }))); expect(tabIdentity(assessmentContext(target))).toBe(tabIdentity(assessmentContext({ ...target, assessment_ref: { ...target.assessment_ref, sha256: 'c'.repeat(64) } }))) })
test('conflicting frozen child or parent is rejected atomically without replacing an existing tab or course', () => { const original = openAssessment(emptySession(), target, true, () => false).session; for (const bad of [{ ...target, assessment_ref: { ...target.assessment_ref, sha256: 'c'.repeat(64) } }, { ...target, course_ref: { ...target.course_ref!, sha256: 'd'.repeat(64) } }]) { const result = openAssessment(original, bad, true, () => false); expect(result.kind).toBe('conflict'); expect(result.session).toBe(original) } })
test('rejects unknown deep-link metadata and non-assessment references', () => { expect(() => readAssessmentTarget(`?assessment=${encodeURIComponent(JSON.stringify({ ...target, mode: 'independent' }))}`)).toThrow(); expect(() => readAssessmentTarget(`?assessment=${encodeURIComponent(JSON.stringify({ ...target, assessment_ref: target.course_ref }))}`)).toThrow() })

test('review is an explicit view of the same frozen attempt with a distinct prescribed tab identity', () => { const review = { ...target, view: 'review' as const }; expect(readAssessmentTarget(assessmentHref(review).slice(1))).toEqual(review); expect(assessmentTarget(assessmentContext(review))).toEqual(review); expect(tabIdentity(assessmentContext(review))).not.toBe(tabIdentity(assessmentContext(target))); const session = openAssessment(emptySession(), target, true, () => false).session; const both = openAssessment(session, review, true, () => false); expect(both.session.tabs).toHaveLength(2); expect(() => readAssessmentTarget(`?assessment=${encodeURIComponent(JSON.stringify({ assessment_ref: target.assessment_ref, view: 'review' }))}`)).toThrow() })
