import { spawn, execFileSync } from 'node:child_process'
import { createServer } from 'node:net'
import { mkdtempSync, readFileSync, writeFileSync, chmodSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'
import { createHash } from 'node:crypto'
import { setTimeout as pause } from 'node:timers/promises'
import assert from 'node:assert/strict'
import { chromium, expect as baseExpect } from '<LOCAL_HOME>/.cache/learning-workbench-acceptance/m63-generic-approval-safe-decline-oct05/apps/web/node_modules/@playwright/test/index.mjs'
const expect=baseExpect.configure({timeout:15000}), root='<LOCAL_HOME>/.cache/learning-workbench-acceptance/m63-generic-approval-safe-decline-oct05', out=import.meta.dirname, head='43c70d660d98904903bd607a4661b3b95710293e'
const sha=b=>createHash('sha256').update(b).digest('hex'), git=(...args)=>execFileSync('git',args,{cwd:root,encoding:'utf8',maxBuffer:16*1024*1024}).trim()
function inputs(){assert.equal(git('rev-parse','HEAD'),head);assert.equal(git('status','--porcelain'),'');const files={};for(const row of execFileSync('git',['ls-tree','-rz',head],{cwd:root,maxBuffer:16*1024*1024}).toString().split('\0').filter(Boolean)){const [meta,path]=row.split('\t');if(path.startsWith('progress/'))continue;const bytes=readFileSync(resolve(root,path)),[mode,type,oid]=meta.split(' ');assert.equal(createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex'),oid);files[path]={mode,type,git_blob:oid,sha256:sha(bytes),bytes:bytes.length}}return{head,count:Object.keys(files).length,files}}
const before=inputs();writeFileSync(resolve(out,'before.json'),JSON.stringify(before,null,2)+'\n')
const tmp=process.env.TMPDIR;assert.ok(tmp.startsWith('<LOCAL_HOME>/.cache/lwap43-'));chmodSync(tmp,0o700)
const data=mkdtempSync(resolve(tmp,'data-')),profile=mkdtempSync(resolve(tmp,'profile-'));writeFileSync(resolve(out,'private-paths.json'),JSON.stringify({tmp,data,profile},null,2)+'\n')
const socket=createServer();await new Promise((ok,no)=>{socket.once('error',no);socket.listen(0,'127.0.0.1',ok)});const port=socket.address().port;await new Promise(ok=>socket.close(ok));const origin=`http://127.0.0.1:${port}`
const env={...process.env,TMPDIR:tmp,LEARNING_DATA_DIR:data,LEARNING_PORT:String(port),LEARNING_HOST:'127.0.0.1',LEARNING_CODEX_EXECUTABLE:resolve(data,'missing-real-cli'),PYTHONPATH:`${out}:${root}`,PYTHONDONTWRITEBYTECODE:'1'}
let api,browser;const calls=[],errors=[],facts={source:head,started_at:new Date().toISOString(),screenshots:[],assertions:[],actual_CLI:'NOT_RUN',actual_remote_model:'NOT_RUN',actual_tool_process:'NOT_RUN'}
const db='learning-workbench.codex-operation-commands.v1',formdb='learning-workbench.codex-approval-forms.v1'
async function stored(page,name){return page.evaluate(name=>new Promise((ok,no)=>{const r=indexedDB.open(name,1);r.onerror=()=>no(Error('IDB open'));r.onsuccess=()=>{const d=r.result,t=d.transaction('drafts','readonly'),q=t.objectStore('drafts').getAll();q.onerror=()=>no(Error('IDB read'));q.onsuccess=()=>{ok(q.result.map(v=>JSON.parse(v.text)));d.close()}}}),name)}
async function panels(page){await page.getByRole('button',{name:'创作',exact:true}).click();const p=page.getByRole('region',{name:'Codex 逐操作审批',exact:true});await p.getByRole('button',{name:'读取审批记录与权限',exact:true}).click();await expect(p.getByText('审批本机记录已读取；只恢复原事实，没有自动 POST。',{exact:true})).toBeVisible();return p}
async function capture(page,region,label){for(const width of [1440,390]){await page.setViewportSize({width,height:900});await region.scrollIntoViewIfNeeded();const geometry=await page.getByRole('dialog',{name:'创作',exact:true}).evaluate(e=>({client:e.clientWidth,scroll:e.scrollWidth,viewport:innerWidth,document:document.documentElement.scrollWidth}));assert.ok(geometry.scroll<=geometry.client+1&&geometry.document<=geometry.viewport);const file=`${label}-${width}.png`;await page.screenshot({path:resolve(out,file)});facts.screenshots.push({file,sha256:sha(readFileSync(resolve(out,file))),geometry})}await page.setViewportSize({width:1440,height:900})}
const decisions=()=>calls.filter(v=>/^POST \/api\/v1\/approvals\//.test(v)).length
async function waitFile(file){for(let n=0;n<200;n++){if(existsSync(file))return JSON.parse(readFileSync(file,'utf8'));await pause(25)}throw Error('Private fixture approval missing')}
try{
 api=spawn(`${root}/.venv/bin/python`,['-B','-m','uvicorn','controlled_api:create_app','--factory','--host','127.0.0.1','--port',String(port),'--no-access-log'],{cwd:root,env,detached:true,stdio:['ignore','pipe','pipe']});let tail='';for(const s of [api.stdout,api.stderr])s.on('data',b=>{tail=(tail+b).slice(-8192)});let ready=false;for(let n=0;n<400;n++){if(api.exitCode!==null)throw Error('Owned fixture server exited: '+tail);try{if((await fetch(origin+'/health',{signal:AbortSignal.timeout(500)})).ok){ready=true;break}}catch{}await pause(50)}assert.ok(ready,'Owned loopback readiness')
 const fixture=JSON.parse(readFileSync(resolve(data,'private-fixture.json'),'utf8')), first=await waitFile(resolve(data,'approval-1.json'));facts.synthetic_bootstrap_calls=fixture.synthetic_bootstrap_calls
 browser=await chromium.launchPersistentContext(profile,{executablePath:'/usr/bin/google-chrome',headless:true,baseURL:origin,viewport:{width:1440,height:900}});await browser.addCookies(fixture.cookies);const page=browser.pages()[0];page.setDefaultTimeout(15000);page.on('dialog',d=>d.accept());page.on('pageerror',()=>errors.push('PAGE_ERROR'));page.on('request',r=>{const u=new URL(r.url());if(u.pathname.startsWith('/api/')){assert.equal(u.origin,origin);calls.push(`${r.method()} ${u.pathname}`)}})
 await page.goto(origin);await expect(page.getByText('✓ UI 会话已保存',{exact:true})).toBeVisible();let p=await panels(page)
 await p.getByLabel('审批来源 turn ID',{exact:true}).fill(first.turn_id);await p.getByRole('button',{name:'独立读取审批安全控制',exact:true}).click();await expect(p.getByRole('region',{name:'审批安全控制 GET',exact:true})).toContainText(first.id)
 await p.getByRole('button',{name:`独立读取完整操作 ${first.id}`,exact:true}).click();const detail=p.getByRole('region',{name:'审批当前详情 GET',exact:true});await expect(detail.getByLabel('完整实际命令',{exact:true})).toContainText('Synthetic approved memory α');await expect(detail).toContainText('网络 denied');await capture(page,detail,'complete-memory-operation')
 const target=`/api/v1/approvals/${first.id}/decision`;let lost
 await page.route(`**${target}`,async route=>{const req=route.request(),key=await req.headerValue('idempotency-key'),body=req.postDataJSON(),original=(await stored(page,db)).find(c=>c.command_id===key);assert.equal(req.method(),'POST');assert.ok(original);assert.equal(original.actor_session_id,fixture.actor);assert.deepEqual(original.body,body);assert.equal(original.basis.kind,'approve');assert.equal(original.basis.view.id,first.id);assert.equal(body.expected_revision,original.basis.view.revision);assert.equal(body.operation_sha256,original.basis.view.operation_sha256);assert.equal(original.ack,null);const r=await route.fetch();assert.equal(r.status(),200);lost={key,body,original,ack:await r.json(),bytes:await r.body()};await route.abort('failed')},{times:1})
 await p.getByRole('button',{name:`明确仅批准这一次完整操作 ${first.id}`,exact:true}).click();await expect(p.getByText('审批结果或本机保存未知；原命令保留，只能显式回放原 key。',{exact:true})).toBeVisible();assert.ok(lost);const prior=decisions(),forms=await stored(page,formdb)
 await page.reload();await expect(page.getByText('✓ UI 会话已保存',{exact:true})).toBeVisible();p=await panels(page);assert.equal(decisions(),prior);assert.deepEqual(await stored(page,formdb),forms)
 const replayResponse=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname===target);await p.getByRole('button',{name:`显式回放审批原 key ${lost.key}`,exact:true}).click();const replay=await replayResponse;assert.equal(replay.status(),200);assert.equal(await replay.request().headerValue('idempotency-key'),lost.key);assert.deepEqual(replay.request().postDataJSON(),lost.body);assert.deepEqual(await replay.body(),lost.bytes)
 await expect(p.getByText('审批原 ACK 已保存：仅是决定事实；执行状态须独立 GET，拒绝也不证明远端已经停止。',{exact:true})).toBeVisible();const durable={...lost.original,ack:lost.ack};assert.deepEqual((await stored(page,db)).find(c=>c.command_id===lost.key),durable)
 await p.getByRole('button',{name:`独立读取原审批当前事实 ${first.id}`,exact:true}).click();await expect(p.getByRole('region',{name:'审批当前详情 GET',exact:true})).toContainText('执行 not_started');assert.ok(!existsSync(resolve(data,'literal-operation-completed.json')))
 writeFileSync(resolve(data,'execute-release'),'explicit memory-only release\n');await waitFile(resolve(data,'literal-operation-completed.json'))
 let current;for(let n=0;n<100;n++){const r=await page.request.get(`/api/v1/approvals/${first.id}`);assert.equal(r.status(),200);current=await r.json();if(current.execution==='completed')break;await pause(25)}assert.equal(current.execution,'completed');assert.equal(current.revision,4)
 await p.getByRole('button',{name:`独立刷新操作执行事实 ${first.id}`,exact:true}).click();await expect(p.getByRole('region',{name:'审批当前详情 GET',exact:true})).toContainText('执行 completed');assert.deepEqual((await stored(page,db)).find(c=>c.command_id===lost.key),durable);await capture(page,p.getByRole('region',{name:'审批当前详情 GET',exact:true}),'independent-completed-original-ack')
 const s=await page.request.get('/api/v1/session').then(r=>r.json()), headers={Origin:origin,'X-CSRF-Token':s.csrf_token}
 async function post(path,body,key,status){const r=await page.request.post(path,{headers:{...headers,'Idempotency-Key':key},data:body});assert.equal(r.status(),status);return r.json()}
 let session;for(let n=0;n<100;n++){session=await page.request.get(`/api/v1/codex/sessions/${fixture.session_id}`).then(r=>r.json());if(session.active_turn_id===null)break;await pause(25)}assert.equal(session.active_turn_id,null)
 const prep=await post(`/api/v1/codex/sessions/${fixture.session_id}/turn-preparations`,{message:'Explicit second synthetic turn for safe decline only.',context_refs:[],expected_session_revision:session.revision,provider_id:'codex_peer',tools:{max_tool_calls:1,wall_seconds:30}},'native-second-prepare',202)
 const proposal=await post('/api/v1/codex/consent-previews',{preparation_id:prep.id,preparation_sha256:prep.preparation_sha256,expected_job_revision:1,expected_provider_revision:2,budget:{max_input_tokens:1000000,max_output_tokens:64,max_provider_calls:1,max_search_calls:0,max_cost_usd:null},expires_at:new Date(Date.now()+300000).toISOString()},'native-second-preview',201)
 const consent=await post('/api/v1/codex/consents',{proposal_id:proposal.id,proposal_sha256:proposal.proposal_sha256},'native-second-grant',201)
 await post(`/api/v1/codex/sessions/${fixture.session_id}/turns`,{preparation_id:prep.id,preparation_sha256:prep.preparation_sha256,consent_id:consent.id,expected_session_revision:prep.session_revision},'native-second-start',202)
 const second=await waitFile(resolve(data,'approval-2.json'));await p.getByLabel('审批来源 turn ID',{exact:true}).fill(second.turn_id);await p.getByRole('button',{name:'独立读取审批安全控制',exact:true}).click();await expect(p.getByRole('region',{name:'审批安全控制 GET',exact:true})).toContainText(second.id)
 await p.getByRole('button',{name:`独立读取完整操作 ${second.id}`,exact:true}).click();await expect(p.getByRole('region',{name:'审批当前详情 GET',exact:true})).toContainText('不支持的操作');await expect(p.getByRole('button',{name:`明确仅批准这一次完整操作 ${second.id}`,exact:true})).toBeDisabled()
 await post('/api/v1/session/role',{role:'learner'},'native-approval-learner',200);await p.getByRole('button',{name:'读取审批记录与权限',exact:true}).click();await expect(p.getByText('审批本机记录已读取；只恢复原事实，没有自动 POST。',{exact:true})).toBeVisible();await expect(p.getByRole('region',{name:'审批当前详情 GET',exact:true})).toHaveCount(0)
 await p.getByLabel('审批来源 turn ID',{exact:true}).fill(second.turn_id);await p.getByRole('button',{name:'独立读取审批安全控制',exact:true}).click();const safe=p.getByRole('region',{name:'审批安全控制 GET',exact:true});await expect(safe).toContainText(second.id);await expect(p.getByRole('button',{name:`独立读取完整操作 ${second.id}`,exact:true})).toBeDisabled();const readBefore=calls.filter(v=>v===`GET /api/v1/approvals/${second.id}`).length
 await p.getByRole('button',{name:`明确拒绝这一次操作 ${second.id}`,exact:true}).click();await expect(p.getByText('审批原 ACK 已保存：仅是决定事实；执行状态须独立 GET，拒绝也不证明远端已经停止。',{exact:true})).toBeVisible();assert.equal(calls.filter(v=>v===`GET /api/v1/approvals/${second.id}`).length,readBefore)
 const declined=(await stored(page,db)).find(c=>c.target_id===second.id);assert.equal(declined.body.decision,'decline');assert.equal(declined.basis.kind,'decline');assert.equal(declined.body.expected_revision,declined.basis.control.approval_controls[0].revision);assert.equal(declined.ack.actor_session_id,fixture.actor);await capture(page,safe,'learner-safe-decline-empty-registry')
 const beforeReload=decisions(),all=await stored(page,db);await page.reload();await expect(page.getByText('✓ UI 会话已保存',{exact:true})).toBeVisible();p=await panels(page);assert.equal(decisions(),beforeReload);assert.deepEqual(await stored(page,db),all);assert.equal(decisions(),3)
 assert.equal(readFileSync(resolve(data,'synthetic-memory-count.txt'),'utf8'),'request\nrequest\n');const execution=JSON.parse(readFileSync(resolve(data,'literal-operation-completed.json'),'utf8'));assert.equal(execution.provider_requests,0);assert.equal(execution.host_actions,0);assert.equal(execution.files_written,0);assert.deepEqual(errors,[])
 const after=inputs();assert.deepEqual(after,before);writeFileSync(resolve(out,'after.json'),JSON.stringify(after,null,2)+'\n');facts.status='CONTROLLED_GENERIC_APPROVAL_UI_NATIVE_PASS';facts.finished_at=new Date().toISOString();facts.before_after_exact=true;facts.complete_nonprogress_inputs=before.count;facts.calls=calls;facts.synthetic_memory_requests=2;facts.synthetic_literal_operations=1;facts.first_original_ack_sha256=sha(lost.bytes);facts.browser=await browser.browser().version();facts.assertions.push('full operation display; durable original command before POST; lost actual200; reload zero automatic POST; explicit same-key/full-body/full-ACK replay durable; approval ACK separate from later completed GET; second empty-operation-registry unsupported and learner safe-control-only decline; no operation replay or additional per-turn model request');facts.boundary='Real Chrome and loopback HTTP owners/SQLite/IndexedDB. Two explicitly prepared memory-protocol turns, one explicitly released pure literal operation, no host action. No actual Codex CLI, remote Provider or physical command/file execution claim.';writeFileSync(resolve(out,'receipt.json'),JSON.stringify(facts,null,2)+'\n');console.log(facts.status)
}catch(e){writeFileSync(resolve(out,'failure.json'),JSON.stringify({source:head,name:e.name,message:e.message,at:new Date().toISOString()},null,2)+'\n');throw e}
finally{writeFileSync(resolve(out,'terminal-source.json'),JSON.stringify(inputs(),null,2)+'\n');await browser?.close();if(api?.pid){const exit=new Promise(ok=>api.once('close',ok));try{process.kill(-api.pid,'SIGTERM')}catch(e){if(e.code!=='ESRCH')throw e}let timer;await Promise.race([exit,new Promise(ok=>{timer=setTimeout(()=>{try{process.kill(-api.pid,'SIGKILL')}catch(e){if(e.code!=='ESRCH')throw e}ok()},5000)})]);clearTimeout(timer)}}
