import { useEffect, useRef, useState } from 'react'
import type { AssessmentGradingResult } from '../../../../../packages/contracts/generated/api-types'
import type { ContentRef, JobRef } from '../../../../../packages/contracts/generated/types'
import { Dialog } from '../../workbench/Controls'
import { useGradingReview } from './useGradingReview'
import type { ReviewBaseline } from './reviewDrafts'
import { ReviewComparison } from './ReviewComparison'
export function AssessmentReview({ workspace, assessment, attempt, result, authorized, onJob, onState, fallback = null, revalidate, pendingJob = false }: { workspace: string; assessment: ContentRef; attempt: string; result: AssessmentGradingResult | null; authorized: boolean; onJob: (job: JobRef) => void; onState: (state: { dirty: boolean; safe: boolean }) => void; fallback?: ReviewBaseline | null; revalidate: () => void; pendingJob?: boolean }) {
  const review = useGradingReview(workspace, assessment, attempt, result, authorized, onJob, fallback, revalidate), editor = review.editor
  const [confirm, setConfirm] = useState(false)
  const callback = useRef(onState); callback.current = onState
  useEffect(() => { callback.current({ dirty: review.dirty, safe: review.safe }) }, [review.dirty, review.safe])
  const blocked = pendingJob || review.busy || review.journal.saving || !review.journal.ready || !review.safe || !!review.journal.error || !!review.decodeError || !!review.conflicts.length
  if (!authorized) return <p>人工复核需要当前作者角色；本机已有复核草稿保留，重新核验权限后才能显示与继续编辑。</p>
  return <section className="grading-review" aria-label="人工复核"><h2>人工复核</h2><p>填写分数、理由与逐题依据，生成签名记录及新的评分版本。原作答与旧评分保留；参考审核和独立证据资格不随之升级。</p>
    <p role="status">{pendingJob && '本次评分任务尚未结束，复核草稿保留，暂不提交另一项复核。'}{review.journal.saving ? '本机复核草稿保存中…' : review.safe ? '本机复核草稿存储可用' : '本机复核草稿尚未安全保存'}</p>{[review.error, review.decodeError, review.journal.error].filter(Boolean).map((text, index) => <p key={index} role="alert">{text}</p>)}{review.journal.error && <button onClick={review.retryLocal}>重试本机复核草稿保存</button>}
    {(review.needsRecovery || !!review.conflicts.length) && <section className="practice-recovery"><h3>发现本机人工复核候选</h3><p>每份草稿保存自己的评分基准；恢复不会自动提交或覆盖服务端评分。</p>{review.candidates.map((candidate, index) => <details key={candidate.text} open><summary>复核候选 {index + 1} · 评分基准 v{candidate.value.base.grading_revision}</summary><p>{candidate.value.reason || '复核理由尚未填写'}</p>{candidate.value.items.filter(item => item.selected).map(item => <p key={item.question_id}>第 {candidate.value.base.items.findIndex(base => base.question_ref.id === item.question_id) + 1} 题：{item.score || '分数尚未填写'}；{item.feedback_markdown || '依据尚未填写'}</p>)}<button disabled={review.busy || review.journal.saving} onClick={() => void review.restore(candidate)}>恢复复核候选 {index + 1}</button></details>)}</section>}
    {(!editor || editor.submitted_job) && <button disabled={!(result ?? fallback) || blocked || review.needsRecovery} onClick={review.begin}>{editor ? '按当前评分新建复核草稿' : '填写人工复核'}</button>}
    {editor && <>{editor.submitted_job ? <p role="status">人工复核命令已被接收，任务 {editor.submitted_job.id}。结果以服务端读回为准；这份回执不代表评分已完成。</p> : <><p>{editor.base.grading_revision === 0 ? '尚无已完成评分；本次人工复核以冻结题目和原提交作答为依据。' : `本次复核基于评分版本 ${editor.base.grading_revision}。`}</p><fieldset disabled={pendingJob || review.busy || !review.journal.ready || !!review.conflicts.length}><legend>人工评分与依据</legend><label>复核理由<textarea aria-label="人工复核理由" value={editor.reason} onChange={event => review.edit({ reason: event.target.value })} rows={3} /></label>{editor.items.map((item, index) => <div className="grading-review-item" key={item.question_id}><label className="assessment-ack"><input type="checkbox" checked={item.selected} onChange={event => review.item(item.question_id, { selected: event.target.checked })} />复核第 {index + 1} 题</label>{item.selected && <><label>分数（0–{editor.base.items[index].max_score}）<input aria-label={`第 ${index + 1} 题人工分数`} inputMode="decimal" value={item.score} onChange={event => review.item(item.question_id, { score: event.target.value })} /></label><label>逐题复核依据<textarea aria-label={`第 ${index + 1} 题复核依据`} value={item.feedback_markdown} rows={4} onChange={event => review.item(item.question_id, { feedback_markdown: event.target.value })} /></label></>}</div>)}</fieldset>{review.changed && result && <><ReviewComparison editor={editor} result={result} /><button disabled={blocked} onClick={review.rebase}>保留本页复核并采用当前评分基准</button><p>若上一次提交回执丢失，可重试原命令；同一命令不会生成两次评分。</p><button disabled={blocked} onClick={() => void review.submit()}>重试原人工复核命令</button></>}<button className="primary-button" disabled={blocked || review.changed} onClick={() => setConfirm(true)}>提交人工复核</button></>}</>}
    {confirm && editor && <Dialog title="确认提交人工复核" close={() => setConfirm(false)}><p>将基于评分版本 {editor.base.grading_revision} 复核 {editor.items.filter(item => item.selected).length} 题，生成新的评分与签名记录；原作答和旧评分不会覆盖。</p><p>{editor.reason || '尚未填写理由，服务端操作不会成功。'}</p><button className="primary-button" disabled={blocked || review.changed} onClick={() => { setConfirm(false); void review.submit() }}>确认提交人工分数与依据</button><button onClick={() => setConfirm(false)}>返回复核草稿</button></Dialog>}
  </section>
}
