import { expect, test } from 'vitest'
import type { GradingResult } from '../../../../../packages/contracts/generated/types'
import { gradingTotals, validateGrading } from './gradingModel'
const question = { entity: 'question' as const, id: 'question_original', revision: 1, sha256: 'a'.repeat(64) }
const result = (): GradingResult => ({ attempt_id: 'attempt_original', grading_revision: 1, grading_rules_version: 'synthetic-test', status: 'needs_review', finalized_at: '2026-09-14T00:00:00Z', items: [{ question_ref: question, status: 'needs_review', max_score: 2, score: null, feedback_markdown: '未审参考，暂无分数。' }] })
test('unknown grades remain null and are excluded from any scored subtotal', () => { const value = validateGrading(result(), 'attempt_original', [question]); expect(value.items[0].score).toBeNull(); expect(gradingTotals(value)).toEqual({ graded: 0, pending: 1, score: 0, maximum: 0, overflow: false, complete: false }) })
test('rejects a same-id substituted revision or hash and an inconsistent summary', () => { expect(() => validateGrading(result(), 'attempt_other', [question])).toThrow(); expect(() => validateGrading(result(), 'attempt_original', [{ ...question, sha256: 'b'.repeat(64) }])).toThrow(); expect(() => validateGrading({ ...result(), status: 'graded' }, 'attempt_original', [question])).toThrow() })
test.each([NaN, Infinity, -1, 3, null])('rejects invalid resolved score %s instead of showing correctness', score => { const value = result(); value.status = 'graded'; value.items[0] = { ...value.items[0], status: 'graded', score }; expect(() => validateGrading(value, 'attempt_original', [question])).toThrow() })
test('rejects replacing unresolved with zero and duplicate frozen questions', () => { const value = result(); value.items[0].score = 0; expect(() => validateGrading(value, 'attempt_original', [question])).toThrow(); value.items[0].score = null; value.items.push({ ...value.items[0] }); expect(() => validateGrading(value, 'attempt_original', [question, question])).toThrow() })

test('finite item values can overflow a sum without becoming an Infinity score or fabricated zero', () => { const value = result(); value.status = 'graded'; value.items = [0, 1].map(index => ({ question_ref: { ...question, id: `question_original_${index}` }, status: 'graded', max_score: 1e308, score: 1e308, feedback_markdown: '合成数值边界' })); expect(gradingTotals(value)).toMatchObject({ graded: 2, pending: 0, score: null, maximum: null, overflow: true, complete: true }); expect(value.items[0].score).toBe(1e308) })
