import { lazy, Suspense } from 'react'
import type { AssessmentGradingResult } from '../../../../../packages/contracts/generated/api-types'
import { gradingTotals } from './gradingModel'
const Markdown = lazy(() => import('../../shared/Markdown').then(module => ({ default: module.Markdown })))
const reviewLabels = { draft: '草稿', needs_review: '待审核', approved: '已审核' }
export function GradingSummary({ result, previous = false, pending = false, questionId, summaryOnly = false }: { result: AssessmentGradingResult; previous?: boolean; pending?: boolean; questionId?: string; summaryOnly?: boolean }) {
  const total = gradingTotals(result)
  return <section className="grading-summary" aria-label={pending ? '上次已完成评分' : previous ? `本页先前读到的评分版本 ${result.grading_revision}` : '当前评分结果'}><h2>{pending ? '上次已完成评分（本次任务尚未完成）' : previous ? '本页先前读到的结果' : result.status === 'needs_review' ? '评分已完成 · 仍有待复核项' : '评分已完成'}</h2><p>评分版本 {result.grading_revision} · 规则 {result.grading_rules_version}</p><p role="status">已评分 {total.graded} 题 · 待复核 {total.pending} 题。{total.overflow ? '汇总超出数值范围，请查看逐题分数。' : total.complete ? `总分 ${total.score} / ${total.maximum}。` : total.graded ? `已评分部分 ${total.score} / ${total.maximum}；不代表完整总分。` : '暂无分数，不将未知项计为零分。'}</p><p>记录时间：<time dateTime={result.finalized_at}>{result.finalized_at}</time>。{result.eligibility_status === 'evaluated' ? '证据资格已逐题记录；已评估不等于每项均有资格。可在复盘中核对原始条件。' : '独立证据资格尚未评估。'}不据分数推断已掌握。</p>
    <ol className="grading-items">{!summaryOnly && result.items.map((item, index) => questionId && item.question_ref.id !== questionId ? null : <li key={item.question_ref.id}><h3>第 {index + 1} 题 · {item.status === 'needs_review' ? '待复核 · 分数为空' : `${item.score} / ${item.max_score}`}</h3><Suspense fallback={<p>正在载入反馈排版…</p>}><Markdown>{item.feedback_markdown}</Markdown></Suspense>{item.solution_markdown != null && <details data-view-key={`grade-solution-${result.grading_revision}-${item.question_ref.id}`}><summary data-focus-key={`grade-solution-${item.question_ref.id}`}>查看服务端已释放的参考解答</summary><p>参考内容状态：{reviewLabels[result.solution_reviews.find(review => review.question_id === item.question_ref.id)?.review_status ?? 'needs_review']}。评分结论不自动升级参考内容的审核状态。</p><Suspense fallback={<p>正在载入解答排版…</p>}><Markdown>{item.solution_markdown}</Markdown></Suspense></details>}<details><summary>核对本题精确引用</summary><code>{item.question_ref.id} · r{item.question_ref.revision}<br />SHA-256 {item.question_ref.sha256}</code></details></li>)}</ol>
    {!summaryOnly && !!result.manual_reviews.length && <details className="grading-receipts"><summary>查看已签名的人工复核记录</summary>{result.manual_reviews.map(review => <div key={review.id}><p>作者角色 · {review.signed_at}</p><p>{review.reason}</p><p>涉及题目：{review.question_ids.map(id => `第 ${result.items.findIndex(item => item.question_ref.id === id) + 1} 题`).join('、')}</p><details><summary>核对签名回执</summary><code>{review.id}<br />{review.signature_algorithm}<br />{review.signature}</code></details></div>)}</details>}
  </section>
}
