import { expect, test } from 'vitest'
import type { GradingResult } from '../../../../../packages/contracts/generated/types'
import { decodeReview, newReview, reviewDirty, reviewKey } from './reviewDrafts'
const assessment = { entity: 'assessment' as const, id: 'assessment_original', revision: 2, sha256: 'a'.repeat(64) }
const result: GradingResult = { attempt_id: 'attempt_original', grading_revision: 4, grading_rules_version: 'synthetic-test', status: 'needs_review', finalized_at: '2026-09-14T00:00:00Z', items: [{ question_ref: { entity: 'question', id: 'question_original', revision: 1, sha256: 'b'.repeat(64) }, score: null, max_score: 2, status: 'needs_review', feedback_markdown: '尚待复核', solution_markdown: 'PRIVATE_ORIGINAL_NOT_IN_REVIEW_DRAFT' }] }
const draft = () => newReview('workspace_original', assessment, result)
const decode = (value: unknown) => decodeReview(JSON.stringify(value), 'workspace_original')
test('keeps grading revision separate and excludes private solution from the persisted review baseline', () => { const value = draft(); expect(JSON.stringify(value)).not.toContain('PRIVATE_ORIGINAL'); expect(decode(value).base.grading_revision).toBe(4); expect(reviewKey(value.attempt_id, 4)).toBe('review:attempt_original:4'); expect(reviewDirty(value)).toBe(false) })
test('preserves invalid and unfinished author input as a draft without coercing blank score into zero', () => { const value = draft(); value.reason = '🧠é'; value.items[0] = { ...value.items[0], selected: true, score: 'NaN', feedback_markdown: '' }; expect(decode(value).items[0].score).toBe('NaN'); expect(reviewDirty(value)).toBe(true) })
test('rejects another workspace, unknown secret fields and a mismatched question', () => { expect(() => decode({ ...draft(), workspace_id: 'workspace_other' })).toThrow(); expect(() => decode({ ...draft(), solution: 'private' })).toThrow(); const value = draft(); value.items[0].question_id = 'question_other'; expect(() => decode(value)).toThrow() })
test('retains a real queued acknowledgement without treating it as a finalized grade', () => { const value = draft(); value.reason = '明确复核'; value.submitted_job = { id: 'job_original', status: 'queued' }; expect(decode(value).submitted_job?.status).toBe('queued'); expect(reviewDirty(value)).toBe(false) })
test('rejects corrupt baseline scores and hidden data inserted into baseline records', () => { const value = draft(); value.base.items[0].score = 0; expect(() => decode(value)).toThrow(); expect(() => decode({ ...draft(), base: { ...draft().base, private_pin: 'hidden' } })).toThrow() })
