import { act, cleanup, renderHook, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, expect, test, vi } from 'vitest'
import { gradingJob, gradingResult, gradingSnapshot } from './grading.testdata'
import { useGradingResult } from './useGradingResult'
const access = vi.hoisted(() => ({ generation: 0, listeners: new Set<() => void>(), request: vi.fn() }))
vi.mock('../../api/client', () => ({ getSessionGeneration: () => access.generation, subscribeSessionAccess: (listener: () => void) => { access.listeners.add(listener); return () => access.listeners.delete(listener) }, request: (...args: unknown[]) => access.request(...args) }))
const auth = { workspace_id: 'workspace_original', role: 'learner' }
beforeEach(() => { access.generation = 0; access.request.mockReset() })
afterEach(() => { cleanup(); vi.useRealTimers() })
test('active and abandoned attempts never request a result', async () => { const { rerender } = renderHook(({ status }) => useGradingResult('workspace_original', { ...gradingSnapshot(), status }, vi.fn()), { initialProps: { status: 'active' as 'active' | 'abandoned' } }); rerender({ status: 'abandoned' }); expect(access.request).not.toHaveBeenCalled() })
test('reads the actual job and polls its actual needs-review outcome without turning null into zero', async () => { let reads = 0; access.request.mockImplementation(async (route: string) => route.endsWith('/session') ? auth : route.includes('/jobs/') ? gradingJob() : ++reads === 1 ? { id: 'job_original', status: 'queued', last_completed_result: null, history: [], current_review_policy: { tutor_scope: 'operation_help_only', allow_materials: false, allow_web: false } } : gradingResult()); const completed = vi.fn(); const { result } = renderHook(() => useGradingResult('workspace_original', gradingSnapshot(), completed)); await waitFor(() => expect(result.current.job?.status).toBe('running')); expect(result.current.result).toBeNull(); await waitFor(() => expect(result.current.result?.status).toBe('needs_review')); expect(result.current.result?.items[0].score).toBeNull(); expect(completed).toHaveBeenCalledTimes(1) })
test('failed jobs remain visible failures and stop polling until explicit retry', async () => { access.request.mockImplementation(async (route: string) => route.endsWith('/session') ? auth : route.includes('/jobs/') ? gradingJob('failed') : { id: 'job_original', status: 'failed', last_completed_result: null, history: [], current_review_policy: { tutor_scope: 'operation_help_only', allow_materials: false, allow_web: false } }); const { result } = renderHook(() => useGradingResult('workspace_original', gradingSnapshot(), vi.fn())); await waitFor(() => expect(result.current.error).toContain('合成故障诊断')); expect(result.current.result).toBeNull(); expect(result.current.loading).toBe(false); expect(access.request).toHaveBeenCalledTimes(3) })
test('a late result from the old attempt cannot overwrite a newly mounted identity', async () => { let finish!: (value: ReturnType<typeof gradingResult>) => void; access.request.mockImplementation(async (route: string, _body: unknown, _headers: unknown, params: { path?: { id: string } } | undefined) => route.endsWith('/session') ? auth : params?.path?.id === 'attempt_original' ? new Promise(resolve => { finish = resolve }) : gradingResult('attempt_other')); const { result, rerender } = renderHook(({ id }) => useGradingResult('workspace_original', gradingSnapshot(id), vi.fn()), { initialProps: { id: 'attempt_original' } }); await waitFor(() => expect(finish).toBeTypeOf('function')); rerender({ id: 'attempt_other' }); await waitFor(() => expect(result.current.result?.attempt_id).toBe('attempt_other')); await act(async () => { finish(gradingResult()) }); expect(result.current.result?.attempt_id).toBe('attempt_other') })
test('access-generation changes clear visible result and reject an in-flight old response', async () => { let finish!: (value: ReturnType<typeof gradingResult>) => void; access.request.mockImplementation(async (route: string) => route.endsWith('/session') ? auth : new Promise(resolve => { finish = resolve })); const { result } = renderHook(() => useGradingResult('workspace_original', gradingSnapshot(), vi.fn())); await waitFor(() => expect(finish).toBeTypeOf('function')); const oldFinish = finish; access.request.mockRejectedValue(new Error('当前策略限制')); act(() => { access.generation++; access.listeners.forEach(listener => listener()) }); await act(async () => { oldFinish(gradingResult()) }); await waitFor(() => expect(result.current.error).toContain('当前策略限制')); expect(result.current.result).toBeNull() })
test('every render of a changed identity hides old result and author role before effect cleanup', async () => {
  access.request.mockImplementation(async (route: string, _body: unknown, _headers: unknown, params: { path?: { id: string } } | undefined) => route.endsWith('/session') ? { ...auth, role: 'author' } : gradingResult(params?.path?.id))
  const observed: { requested: string; shown: string | null; role: string | null }[] = []
  const { result, rerender } = renderHook(({ id }) => { const reading = useGradingResult('workspace_original', gradingSnapshot(id), vi.fn()); observed.push({ requested: id, shown: reading.result?.attempt_id ?? null, role: reading.role }); return reading }, { initialProps: { id: 'attempt_original' } })
  await waitFor(() => expect(result.current.result?.attempt_id).toBe('attempt_original'))
  rerender({ id: 'attempt_other' })
  await waitFor(() => expect(result.current.result?.attempt_id).toBe('attempt_other'))
  expect(observed.filter(value => value.requested === 'attempt_other').every(value => value.shown === null || value.shown === 'attempt_other')).toBe(true)
  expect(observed.find(value => value.requested === 'attempt_other')).toEqual({ requested: 'attempt_other', shown: null, role: null })
})
