import { spawn, execFileSync } from 'node:child_process'
import { createServer } from 'node:net'
import { mkdtempSync, readFileSync, writeFileSync, chmodSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'
import { createHash } from 'node:crypto'
import { setTimeout as pause } from 'node:timers/promises'
import assert from 'node:assert/strict'
import { chromium, expect as baseExpect } from '<LOCAL_HOME>/.cache/learning-workbench-acceptance/m63-generic-approval-ui-owner-oct05/apps/web/node_modules/@playwright/test/index.mjs'
const expect=baseExpect.configure({timeout:15000}), root=process.env.SOURCE_TREE, out=import.meta.dirname, head=process.env.SOURCE_SHA
const sha=b=>createHash('sha256').update(b).digest('hex'), git=(...args)=>execFileSync('git',args,{cwd:root,encoding:'utf8',maxBuffer:16*1024*1024}).trim()
function inputs(){assert.equal(git('rev-parse','HEAD'),head);assert.equal(git('status','--porcelain'),'');const files={};for(const row of execFileSync('git',['ls-tree','-rz',head],{cwd:root,maxBuffer:16*1024*1024}).toString().split('\0').filter(Boolean)){const [meta,path]=row.split('\t');if(path.startsWith('progress/'))continue;const bytes=readFileSync(resolve(root,path)),[mode,type,oid]=meta.split(' ');assert.equal(createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex'),oid);files[path]={mode,type,git_blob:oid,sha256:sha(bytes),bytes:bytes.length}}return{head,count:Object.keys(files).length,files}}
const beforeInputs=inputs();writeFileSync(resolve(out,'before.json'),JSON.stringify(beforeInputs,null,2)+'\n')
const tmp=process.env.TMPDIR;assert.ok(tmp.startsWith('<LOCAL_HOME>/.cache/lwapcounter-'));chmodSync(tmp,0o700)
const data=mkdtempSync(resolve(tmp,'data-')),profile=mkdtempSync(resolve(tmp,'profile-'));writeFileSync(resolve(out,'private-paths.json'),JSON.stringify({tmp,data,profile},null,2)+'\n')
const socket=createServer();await new Promise((ok,no)=>{socket.once('error',no);socket.listen(0,'127.0.0.1',ok)});const port=socket.address().port;await new Promise(ok=>socket.close(ok));const origin=`http://127.0.0.1:${port}`
const env={...process.env,TMPDIR:tmp,LEARNING_DATA_DIR:data,LEARNING_PORT:String(port),LEARNING_HOST:'127.0.0.1',LEARNING_CODEX_EXECUTABLE:resolve(data,'missing-real-cli'),PYTHONPATH:`${out}:${root}`,PYTHONDONTWRITEBYTECODE:'1'}
let api,browser;const calls=[],errors=[],facts={source:head,started_at:new Date().toISOString(),screenshots:[],assertions:[],actual_CLI:'NOT_RUN',actual_remote_model:'NOT_RUN',actual_tool_process:'NOT_RUN'}
const db='learning-workbench.codex-operation-commands.v1',formdb='learning-workbench.codex-approval-forms.v1'
async function stored(page,name){return page.evaluate(name=>new Promise((ok,no)=>{const r=indexedDB.open(name,1);r.onerror=()=>no(Error('IDB open'));r.onsuccess=()=>{const d=r.result,t=d.transaction('drafts','readonly'),q=t.objectStore('drafts').getAll();q.onerror=()=>no(Error('IDB read'));q.onsuccess=()=>{ok(q.result.map(v=>JSON.parse(v.text)));d.close()}}}),name)}
async function panels(page){await page.getByRole('button',{name:'创作',exact:true}).click();const p=page.getByRole('region',{name:'Codex 逐操作审批',exact:true});await p.getByRole('button',{name:'读取审批记录与权限',exact:true}).click();await expect(p.getByText('审批本机记录已读取；只恢复原事实，没有自动 POST。',{exact:true})).toBeVisible();return p}
async function capture(page,region,label){for(const width of [1440,390]){await page.setViewportSize({width,height:900});await region.scrollIntoViewIfNeeded();const geometry=await page.getByRole('dialog',{name:'创作',exact:true}).evaluate(e=>({client:e.clientWidth,scroll:e.scrollWidth,viewport:innerWidth,document:document.documentElement.scrollWidth}));assert.ok(geometry.scroll<=geometry.client+1&&geometry.document<=geometry.viewport);const file=`${label}-${width}.png`;await page.screenshot({path:resolve(out,file)});facts.screenshots.push({file,sha256:sha(readFileSync(resolve(out,file))),geometry})}await page.setViewportSize({width:1440,height:900})}
const decisions=()=>calls.filter(v=>/^POST \/api\/v1\/approvals\//.test(v)).length
async function waitFile(file){for(let n=0;n<200;n++){if(existsSync(file))return JSON.parse(readFileSync(file,'utf8'));await pause(25)}throw Error('Private fixture approval missing')}
try{
 api=spawn(`${root}/.venv/bin/python`,['-B','-m','uvicorn','controlled_api:create_app','--factory','--host','127.0.0.1','--port',String(port),'--no-access-log'],{cwd:root,env,detached:true,stdio:['ignore','pipe','pipe']});let tail='';for(const s of [api.stdout,api.stderr])s.on('data',b=>{tail=(tail+b).slice(-8192)});let ready=false;for(let n=0;n<400;n++){if(api.exitCode!==null)throw Error('Owned fixture server exited: '+tail);try{if((await fetch(origin+'/health',{signal:AbortSignal.timeout(500)})).ok){ready=true;break}}catch{}await pause(50)}assert.ok(ready,'Owned loopback readiness')
 const fixture=JSON.parse(readFileSync(resolve(data,'private-fixture.json'),'utf8')), first=await waitFile(resolve(data,'approval-1.json'));facts.synthetic_bootstrap_calls=fixture.synthetic_bootstrap_calls
 browser=await chromium.launchPersistentContext(profile,{executablePath:'/usr/bin/google-chrome',headless:true,baseURL:origin,viewport:{width:1440,height:900}});await browser.addCookies(fixture.cookies);const page=browser.pages()[0];page.setDefaultTimeout(15000);page.on('dialog',d=>d.accept());page.on('request',r=>{const u=new URL(r.url());if(u.pathname.startsWith('/api/')){assert.equal(u.origin,origin);calls.push(`${r.method()} ${u.pathname}`)}})
 await page.goto(origin);await expect(page.getByText('✓ UI 会话已保存',{exact:true})).toBeVisible();let p=await panels(page)
 await p.getByLabel('审批来源 turn ID',{exact:true}).fill(first.turn_id);await p.getByRole('button',{name:'独立读取审批安全控制',exact:true}).click();await expect(p.getByRole('region',{name:'审批安全控制 GET',exact:true})).toContainText(first.id)
 await p.getByRole('button',{name:`独立读取完整操作 ${first.id}`,exact:true}).click();await expect(p.getByLabel('完整实际命令',{exact:true})).toContainText('Synthetic approved memory α')
 const target=`/api/v1/approvals/${first.id}/decision`;let original,key,actualStatus
 await page.route(`**${target}`,async route=>{const req=route.request();key=await req.headerValue('idempotency-key');original=(await stored(page,db)).find(c=>c.command_id===key);assert.equal(original.body.decision,'approve_once');assert.equal(original.ack,null);const session=await page.request.get('/api/v1/session').then(r=>r.json());const role=await page.request.post('/api/v1/session/role',{headers:{Origin:origin,'X-CSRF-Token':session.csrf_token,'Idempotency-Key':'counter-real-role-loss'},data:{role:'learner'}});assert.equal(role.status(),200);const response=await route.fetch();actualStatus=response.status();assert.equal(actualStatus,403);await route.fulfill({response})},{times:1})
 await p.getByRole('button',{name:`明确仅批准这一次完整操作 ${first.id}`,exact:true}).click();await expect(p.getByText('审批当前权限或原 actor 已变化；原命令和表单隔离保留。',{exact:true})).toBeVisible()
 await p.getByRole('button',{name:'读取审批记录与权限',exact:true}).click();await expect(p.getByText('审批本机记录已读取；只恢复原事实，没有自动 POST。',{exact:true})).toBeVisible()
 await p.getByLabel('审批来源 turn ID',{exact:true}).fill(first.turn_id);await p.getByRole('button',{name:'独立读取审批安全控制',exact:true}).click();const safe=p.getByRole('region',{name:'审批安全控制 GET',exact:true});await expect(safe).toContainText('pending')
 const control=await page.request.get(`/api/v1/codex/turns/${first.turn_id}`).then(r=>r.json());assert.equal(control.approval_controls[0].decision,'pending');assert.equal(control.approval_controls[0].revision,1)
 const before=(await stored(page,db)).find(c=>c.command_id===key),button=p.getByRole('button',{name:`明确拒绝这一次操作 ${first.id}`,exact:true}),enabled=await button.isEnabled()
 writeFileSync(resolve(out,'counter-observation.json'),JSON.stringify({source:head,actual_approve_status:actualStatus,approval_pending:control.approval_controls[0].decision,approval_revision:control.approval_controls[0].revision,prior_approve_retained:JSON.stringify(before.body)===JSON.stringify(original.body),safe_decline_enabled:enabled,synthetic_memory_requests:readFileSync(resolve(data,'synthetic-memory-count.txt'),'utf8').split('request').length-1,literal_executed:existsSync(resolve(data,'literal-operation-completed.json'))},null,2)+'\n')
 await capture(page,safe,'safe-decline-after-actual-403');assert.equal(enabled,true,'A retained rejected approve must not disable safe decline of the actual pending approval')
 const reads=calls.filter(v=>v===`GET /api/v1/approvals/${first.id}`).length;await button.click();await expect(p.getByText('审批原 ACK 已保存：仅是决定事实；执行状态须独立 GET，拒绝也不证明远端已经停止。',{exact:true})).toBeVisible()
 const all=await stored(page,db),reduced=all.find(c=>c.body.decision==='decline');assert.ok(reduced);assert.notEqual(reduced.command_id,key);assert.deepEqual(reduced.body,{expected_revision:1,operation_sha256:control.approval_controls[0].operation_sha256,decision:'decline'});assert.deepEqual(all.find(c=>c.command_id===key),before);assert.equal(reduced.ack.decision,'decline');assert.equal(calls.filter(v=>v===`GET /api/v1/approvals/${first.id}`).length,reads)
 assert.equal(readFileSync(resolve(data,'synthetic-memory-count.txt'),'utf8'),'request\n');assert.ok(!existsSync(resolve(data,'literal-operation-completed.json')))
 const after=inputs();assert.deepEqual(after,beforeInputs);writeFileSync(resolve(out,'after.json'),JSON.stringify(after,null,2)+'\n');facts.status='CONTROLLED_SAFE_DECLINE_AFTER_ACTUAL_403_PASS';facts.finished_at=new Date().toISOString();facts.before_after_exact=true;facts.complete_nonprogress_inputs=after.count;facts.calls=calls;facts.synthetic_memory_requests=1;facts.synthetic_literal_operations=0;writeFileSync(resolve(out,'receipt.json'),JSON.stringify(facts,null,2)+'\n');console.log(facts.status)
}catch(e){writeFileSync(resolve(out,'failure.json'),JSON.stringify({source:head,name:e.name,message:e.message,at:new Date().toISOString()},null,2)+'\n');throw e}
finally{writeFileSync(resolve(out,'terminal-source.json'),JSON.stringify(inputs(),null,2)+'\n');await browser?.close();if(api?.pid){const exit=new Promise(ok=>api.once('close',ok));try{process.kill(-api.pid,'SIGTERM')}catch(e){if(e.code!=='ESRCH')throw e}let timer;await Promise.race([exit,new Promise(ok=>{timer=setTimeout(()=>{try{process.kill(-api.pid,'SIGKILL')}catch(e){if(e.code!=='ESRCH')throw e}ok()},5000)})]);clearTimeout(timer)}}
