import { expect, test as base } from '<ACCEPTANCE_CACHE>/m42-4cf13f7/apps/web/node_modules/@playwright/test/index.mjs'
import { writeFileSync } from 'node:fs'
import { RestartRuntime } from '<ACCEPTANCE_CACHE>/m42-4cf13f7/tests/e2e/restartRuntime.ts'
import { originalAssessmentPackage, importAssessmentPackage } from '<ACCEPTANCE_CACHE>/m42-4cf13f7/tests/e2e/assessmentTestData.ts'
import type { PageRoute } from '<ACCEPTANCE_CACHE>/m42-4cf13f7/packages/contracts/generated/api-types.ts'
const test = base.extend<{ runtime: RestartRuntime }>({
  runtime: async ({}, use) => { const runtime = await RestartRuntime.start(); try { await use(runtime) } finally { await runtime.close() } },
  page: async ({ runtime, playwright }, use) => { const context = await runtime.openBrowser(playwright.chromium), page = context.pages()[0]; await runtime.authenticateOnly(page); await use(page) },
})
test('real route creation, reminder, manual false, reordered revision and exact target navigation preserve history', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  const fixture = originalAssessmentPackage('routeuinative', 'learner'), imported = await importAssessmentPackage(page, fixture); await imported.dialog.getByRole('button', { name: '关闭导入', exact: true }).click(); await page.getByRole('navigation', { name: '学习主导航', exact: true }).getByRole('button', { name: '学习路线', exact: true }).click()
  await page.getByRole('button', { name: '创建路线', exact: true }).first().click(); const editor = page.getByRole('dialog', { name: '创建路线', exact: true }); await editor.getByRole('button', { name: '填写新路线', exact: true }).click(); await editor.getByLabel('路线名称', { exact: true }).fill('原创路线与精确任务'); await editor.getByLabel('路线学习目标', { exact: true }).fill('先读再练；提醒不锁定，人工标记不授予能力。')
  const refValue = (ref: typeof fixture.lesson) => `${ref.entity}:${ref.id}:${ref.revision}:${ref.sha256}`
  await expect(editor.getByLabel('添加学习任务').locator(`option[value="${refValue(fixture.lesson)}"]`)).toHaveCount(1); await editor.getByLabel('添加学习任务').selectOption(refValue(fixture.lesson)); await editor.getByLabel('添加学习任务').selectOption(refValue(fixture.practice)); await editor.getByLabel('任务 1 标题').fill('先读精确小节'); await editor.getByLabel('任务 2 标题').fill('练习提醒可跳过')
  const second = editor.locator('.route-editor-steps>li').nth(1); await second.locator('summary').click(); await second.getByRole('checkbox', { name: '先读精确小节', exact: true }).check(); await editor.getByRole('button', { name: '保存路线新修订', exact: true }).click(); await editor.getByRole('button', { name: '打开已保存路线', exact: true }).click(); await expect(page.getByRole('heading', { name: '原创路线与精确任务', exact: true })).toBeVisible()
  const first: PageRoute = await page.request.get('/api/v1/routes?limit=100').then(response => response.json()); expect(first.items).toHaveLength(1); expect(first.items[0].steps.map(step => step.target)).toEqual([fixture.lesson, fixture.practice]); const r1 = first.item_refs[0]
  await expect(page.getByText('先修提醒：先读精确小节尚未完成；仍可打开本任务。', { exact: true })).toBeVisible(); await page.getByRole('button', { name: '打开任务：练习提醒可跳过', exact: true }).click(); await expect.poll(() => new URL(page.url()).searchParams.has('practice')).toBe(true); const practice = JSON.parse(new URL(page.url()).searchParams.get('practice')!); expect(practice.practice_ref).toEqual(fixture.practice); expect(practice.lesson_ref).toEqual(fixture.lesson); expect(practice.course_ref).toEqual(fixture.course)
  await page.getByRole('tab', { name: /原创路线与精确任务/ }).click(); await page.getByRole('button', { name: '手动标为未完成：先读精确小节', exact: true }).click(); await page.getByRole('button', { name: '确认保存人工标记', exact: true }).click(); await expect(page.getByText(/人工未完成优先保留/)).toBeVisible()
  await page.getByRole('button', { name: '编辑路线并保存新修订', exact: true }).click(); const edit = page.getByRole('dialog', { name: '编辑路线', exact: true }); await edit.getByRole('button', { name: '编辑此路线修订', exact: true }).click(); await edit.getByRole('button', { name: '上移任务 2', exact: true }).click(); await edit.getByRole('button', { name: '保存路线新修订', exact: true }).click(); await edit.getByRole('button', { name: '打开已保存路线', exact: true }).click()
  const final: PageRoute = await page.request.get('/api/v1/routes?limit=100').then(response => response.json()); expect(final.items).toHaveLength(2); expect(final.items.find(item => item.revision === 1)).toEqual(first.items[0]); const r2 = final.items.find(item => item.revision === 2)!; expect(r2.steps.map(step => step.id)).toEqual([...first.items[0].steps.map(step => step.id)].reverse()); const progress = await page.request.get('/api/v1/learning/progress').then(response => response.json()); const old = progress.route_steps.find((item: { route_ref: { id: string; revision: number }; step_id: string }) => item.route_ref.id === r1.id && item.route_ref.revision === 1 && item.step_id === first.items[0].steps[0].id); expect(old.manual_override).toBe(false); expect(progress.route_steps.filter((item: { route_ref: { revision: number }; manual_override: boolean | null }) => item.route_ref.revision === 2).every((item: { manual_override: boolean | null }) => item.manual_override === null)).toBe(true)
  await page.screenshot({ path: info.outputPath('route-reordered-1440.png') }); await page.setViewportSize({ width: 390, height: 844 }); await page.getByRole('heading', { name: '原创路线与精确任务', exact: true }).scrollIntoViewIfNeeded(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await page.screenshot({ path: info.outputPath('route-reordered-390.png') }); expect(errors).toEqual([])
  writeFileSync(info.outputPath('actual-route-ui.json'), JSON.stringify({ scope: 'original synthetic actual UI route POST/PUT and manual completion', versions: final.item_refs, original_content_unchanged: true, step_ids_preserved_by_reorder: true, old_manual_false_preserved: true, new_revision_does_not_inherit_manual: true, exact_navigation: practice, runtime_errors: errors }, null, 2))
})

import { startObserver, finishObserver } from './observer'
test.beforeEach(async ({ page }, info) => { startObserver(page, info) })
test.afterEach(async ({ page }, info) => { await finishObserver(page, info) })
