import { describe, expect, it } from 'vitest'
import { ContextBridge, emptySession, freezeContext, navigationItems, openTab, resizeValue, tabIdentity, type ViewContext } from './model'
const context = (id: string, revision = 1): ViewContext => ({ view_kind: 'lesson', active_ref: { entity: 'lesson', id, revision, sha256: 'a'.repeat(64) }, attached_refs: [], selection: null, attempt_id: null })
describe('Workbench invariants', () => {
  it('starts empty, on the four fixed navigation entries', () => { expect(navigationItems.map(item => item.label)).toEqual(['学习路线', '教材', '习题', '测试题']); expect(emptySession()).toMatchObject({ navigation: 'route', tabs: [], course_ref: null }) })
  it('separates same-titled objects, revisions and modes', () => { expect(tabIdentity(context('a'))).not.toBe(tabIdentity(context('b'))); expect(tabIdentity(context('a', 1))).not.toBe(tabIdentity(context('a', 2))); expect(tabIdentity({ ...context('a'), view_kind: 'assessment_help', attempt_id: 'attempt_one' })).not.toBe(tabIdentity({ ...context('a'), view_kind: 'assessment_help', attempt_id: 'attempt_two' })) })
  it('never replaces a preview with an unsent object draft', () => { const first = openTab(emptySession(), context('a'), false, () => false); const second = openTab(first, context('b'), false, id => id === first.active_tab_id); expect(second.tabs).toHaveLength(2); expect(second.tabs[0].context.active_ref.id).toBe('a') })
  it('replaces a clean preview and preserves pinned tabs', () => { const first = openTab(emptySession(), context('a'), true, () => false); const second = openTab(first, context('b'), false, () => false); const third = openTab(second, context('c'), false, () => false); expect(third.tabs.map(tab => tab.context.active_ref.id)).toEqual(['a', 'c']) })
  it('freezes a cloned sending snapshot', () => { const current = context('a'); const frozen = freezeContext(current, 'why'); current.active_ref.id = 'b'; expect(frozen.context.active_ref.id).toBe('a'); expect(Object.isFrozen(frozen.context.active_ref)).toBe(true) })
  it('routes delayed A response to frozen A thread after selection switches to B', async () => { const bridge = new ContextBridge(); let resolve!: (value: string) => void; let active = context('a'); const pending = bridge.send(active, 'A question', () => new Promise<string>(done => { resolve = done })); active = context('b'); const drafts = { [tabIdentity(active)]: 'B unsent draft' }; resolve('Synthetic executor reply: A only'); const threadId = await pending; expect(threadId).toBe(tabIdentity(context('a'))); expect(bridge.replies.get(tabIdentity(active))).toBeUndefined(); expect(bridge.replies.get(threadId)?.[0].request.context.active_ref.id).toBe('a'); expect(drafts[tabIdentity(active)]).toBe('B unsent draft') })
  it('bounds resizing and reserves 480px central content', () => { expect(resizeValue('nav', 999, 1440, 368)).toBe(360); expect(resizeValue('nav', 0, 1440, 368)).toBe(260); expect(resizeValue('agent', 480, 1280, 360)).toBe(428); expect(resizeValue('agent', 100, 1440, 300)).toBe(320) })
})
