import { useState } from 'react'
import type { TutorRequest } from '../../../../packages/contracts/generated/types'
import { useTutor } from '../features/tutor/useTutor'
import type { TutorLocation } from '../features/tutor/tutorContext'
import { TutorWorkflow } from '../features/tutor/TutorWorkflow'
import { TutorControls } from '../features/tutor/TutorControls'
import { OperationHelp } from '../features/assessment/OperationHelp'
import type { ReviewTutorContext } from '../features/review/reviewContext'
import { scoreText } from '../features/review/reviewModel'
import { DraftConflictPreview } from './DraftConflictPreview'
import type { DraftConflict } from './DraftStore'
import type { ViewContext } from './model'
export function Tutor({ workspace = '', location = null, paused = false, independent = false, checking = false, settings = () => {}, context, title, resolved, synthetic = false, draft, onDraft, conflicts, saving, enabled, error, choose, baseDraft, storedDraft, practice, review, route }: { workspace?: string; location?: TutorLocation | null; paused?: boolean; independent?: boolean; checking?: boolean; settings?: () => void; context: ViewContext | null; title: string; resolved: boolean; synthetic?: boolean; draft: string; onDraft: (text: string) => void; conflicts: DraftConflict[]; saving: boolean; enabled: boolean; baseDraft: string | null; storedDraft: string; error: string; choose: (candidate: DraftConflict | null) => void; practice?: { question: string; response: string; assistance: string }; review?: ReviewTutorContext; route?: { goal: string; tasks: number } }) {
  const [intent, setIntent] = useState<TutorRequest['intent']>('explain')
  const sourceRoot = JSON.stringify([context?.view_kind, context?.active_ref, context?.attempt_id])
  const [attachments, setAttachments] = useState<{ root: string; refs: string[] }>({ root: '', refs: [] })
  const selected = attachments.root === sourceRoot ? attachments.refs : []
  const candidates = context?.attached_refs ?? []
  const activeLocation = location && context && resolved && !synthetic ? { ...location, context: { ...context, attached_refs: candidates.filter(ref => selected.includes(JSON.stringify(ref))) } } : null
  const state = useTutor(workspace, activeLocation, paused)
  const canSend = enabled && !saving && !error && !conflicts.length && !!draft.trim() && !!state.thread && !state.messageCursor && !state.busy && state.ready && !state.denied && (!state.run || ['completed', 'failed', 'cancelled'].includes(state.run.run.status))
  if (paused || state.denied) return <><OperationHelp independent={independent} checking={checking} />{!paused && state.denied && <button onClick={() => void state.refreshThreads()}>重新核验学科访问</button>}<TutorControls workspace={workspace} commands={state.commands} known={state.knownRunIds} execute={command => void state.execute(command)} busy={state.busy} /></>
  return <div className="tutor"><header className="tutor-heading"><h2>Agent</h2><span className="connection-state">本地任务 · 明确授权</span></header>
    <details className="context-preview" open><summary>当前上下文</summary><p>{context ? title : '尚未选择学习对象'}</p>{context && <><small>修订 {context.active_ref.revision} · {resolved ? synthetic ? '合成示例引用' : '已解析的准确引用' : '引用待解析'}</small><details><summary>查看引用范围</summary><code>{context.active_ref.id}<br />SHA-256 {context.active_ref.sha256}</code><p>当前导航父链 {candidates.length} 项；默认不作为问答附加材料。</p></details>{practice && <details open><summary>当前练习题与作答</summary><p>{practice.question}</p><p>你的答案：{practice.response || '尚未作答'}</p><p>{practice.assistance}</p><small>当前练习会话的本地上下文；实际发送范围见任务授权与输入记录。</small></details>}{review && <details open><summary>当前测试复盘上下文</summary><p>当前题目：{review.questionText}</p><p>交卷答案：{review.submitted?.answer || '未填写答案'}</p><details><summary>原始推导步骤</summary><p style={{ whiteSpace: 'pre-wrap' }}>{review.submitted?.steps_markdown || '未填写推导步骤'}</p></details><p>评分版本 {review.gradingRevision}：{scoreText(review.historyItem)}</p>{review.feedback ? <details><summary>此版本当前可读的评分反馈</summary><p>{review.feedback}</p></details> : <p>此版本没有当前获准的反馈正文；未使用历史私有反馈。</p>}{review.solution != null ? <details><summary>此版本当前已释放的参考解答</summary><p>原审核状态：{review.solutionReview === 'approved' ? '已审核' : review.solutionReview === 'draft' ? '草稿' : '待审核'}</p><p>{review.solution}</p></details> : <p>此版本没有当前获准的标准答案正文。</p>}<p>已核验对应教材 {review.materials.length} 项。当前本地上下文；实际发送范围见任务授权与输入记录。</p></details>}{context.selection && <blockquote>选文：{context.selection.exact_quote}</blockquote>}</>}</details>
    {route && <section className="context-preview"><h3>当前路线目标与任务</h3><p>{route.goal}</p><p>共 {route.tasks} 个真实任务。先修关系作提醒，完成标记不授予能力证据。实际发送范围与结果以任务记录为准。</p></section>}
    {activeLocation ? <><details><summary>明确选择本次附加范围（默认无）</summary><p>当前精确对象和选文单独核验；选择课程将明确允许在该课程范围取材，不会自动扩展。</p>{candidates.map(ref => <label key={JSON.stringify(ref)}><input type="checkbox" checked={selected.includes(JSON.stringify(ref))} onChange={event => setAttachments({ root: sourceRoot, refs: event.target.checked ? [...selected, JSON.stringify(ref)] : selected.filter(value => value !== JSON.stringify(ref)) })} />{ref.entity}/{ref.id} · r{ref.revision} · {ref.sha256}</label>)}</details><TutorWorkflow workspace={workspace} state={state} settings={settings} /></> : <div className="tutor-messages"><h3>先选择真实学习对象</h3><p>{synthetic ? '此页面是布局合成示例，没有创建真实模型任务。请打开已导入的教材或真实练习。' : '尚无可解析的学习对象；问题草稿仍可保留。'}</p></div>}
    <form className="composer" onSubmit={event => { event.preventDefault(); if (canSend) void state.start(draft, intent) }}><div className="intent-tabs" aria-label="教学意图">{([['explain', '讲解'], ['hint', '提示'], ['derive', '推导'], ['research', '拓展']] as const).map(([value, name]) => <button type="button" key={value} aria-pressed={intent === value} onClick={() => setIntent(value)}>{name}</button>)}</div><div className="draft-feedback" role="status">{error && <p className="draft-error">{error}<button type="button" onClick={() => onDraft(draft)}>重试草稿保存</button></p>}{conflicts.length > 0 && <details open><summary>草稿版本冲突 · 两份文本均已保留</summary><DraftConflictPreview base={baseDraft} local={draft} stored={storedDraft} /><button type="button" disabled={saving || !enabled} onClick={() => choose(null)}>使用已存版本</button>{conflicts.map(candidate => <details key={candidate.id}><summary>查看冲突草稿</summary><p>{candidate.text}</p><button type="button" disabled={saving || !enabled} onClick={() => choose(candidate)}>采用这份草稿</button></details>)}</details>}</div><label className="sr-only" htmlFor="question-draft">问题草稿</label><textarea id="question-draft" disabled={!enabled} value={draft} onChange={event => onDraft(event.target.value)} placeholder={enabled ? "写下问题，草稿按当前对象保留…" : "正在确认本机会话或处理草稿选择…"} rows={4} /><div className="composer-footer"><span>联网：未授权</span><button className="primary-button" disabled={!canSend} title="先建立真实线程，再创建本地任务；授权预览后才允许外发">创建本次问答任务 ↑</button></div><small>{saving ? "草稿保存中…" : error ? "草稿保存失败，当前文本尚未持久化。" : "本机草稿保留；发送与结果以本次任务记录为准。"}</small></form>
  </div>
}
