import { useState } from 'react'
import { DraftConflictPreview } from './DraftConflictPreview'
import type { DraftConflict } from './DraftStore'
import type { ViewContext } from './model'
export function Tutor({ context, title, resolved, synthetic = false, draft, onDraft, conflicts, saving, enabled, error, choose, baseDraft, storedDraft }: { context: ViewContext | null; title: string; resolved: boolean; synthetic?: boolean; draft: string; onDraft: (text: string) => void; conflicts: DraftConflict[]; saving: boolean; enabled: boolean; baseDraft: string | null; storedDraft: string; error: string; choose: (candidate: DraftConflict | null) => void }) {
  const [intent, setIntent] = useState('讲解')
  return <div className="tutor"><header className="tutor-heading"><h2>Agent</h2><span className="connection-state">未配置模型</span></header>
    <details className="context-preview" open><summary>当前上下文</summary><p>{context ? title : '尚未选择学习对象'}</p>{context && <><small>修订 {context.active_ref.revision} · {resolved ? synthetic ? '合成示例引用' : '已解析的准确引用' : '引用待解析'}</small><details><summary>查看引用范围</summary><code>{context.active_ref.id}<br />SHA-256 {context.active_ref.sha256}</code><p>保留当前对象及明确附加的引用；附加材料 {(context.attached_refs ?? []).length} 项。</p></details>{context.selection && <blockquote>选文：{context.selection.exact_quote}</blockquote>}</>}</details>
    <div className="tutor-messages"><div className="assistant-mark" aria-hidden="true">✦</div><h3>围绕当前内容，一起思考</h3><p>模型尚未配置。配置提供商并明确授权后，可以围绕选中的教材提问。</p><p className="muted">现在可以浏览内容、调整工作台并保留问题草稿。尚未调用模型，也未联网检索。</p></div>
    <form className="composer" onSubmit={event => event.preventDefault()}><div className="intent-tabs" aria-label="教学意图">{['讲解', '提示', '推导', '拓展'].map(name => <button type="button" key={name} aria-pressed={intent === name} onClick={() => setIntent(name)}>{name}</button>)}</div><div className="draft-feedback" role="status">{error && <p className="draft-error">{error}<button type="button" onClick={() => onDraft(draft)}>重试草稿保存</button></p>}{conflicts.length > 0 && <details open><summary>草稿版本冲突 · 两份文本均已保留</summary><DraftConflictPreview base={baseDraft} local={draft} stored={storedDraft} /><button type="button" disabled={saving || !enabled} onClick={() => choose(null)}>使用已存版本</button>{conflicts.map(candidate => <details key={candidate.id}><summary>查看冲突草稿</summary><p>{candidate.text}</p><button type="button" disabled={saving || !enabled} onClick={() => choose(candidate)}>采用这份草稿</button></details>)}</details>}</div><label className="sr-only" htmlFor="question-draft">问题草稿</label><textarea id="question-draft" disabled={!enabled} value={draft} onChange={event => onDraft(event.target.value)} placeholder={enabled ? "写下问题，草稿按当前对象保留…" : "正在确认本机会话或处理草稿选择…"} rows={4} /><div className="composer-footer"><span>联网：未授权</span><button className="primary-button" disabled title="需要配置模型并授权后才能发送">发送 ↑</button></div><small>{saving ? "草稿保存中…" : error ? "草稿保存失败，当前文本尚未持久化。" : "草稿保留在本机浏览器，尚未发送。"}</small></form>
  </div>
}
