import { spawn, execFileSync } from 'node:child_process'
import { createServer } from 'node:net'
import { mkdtempSync, readFileSync, writeFileSync, chmodSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'
import { createHash } from 'node:crypto'
import { setTimeout as pause } from 'node:timers/promises'
import assert from 'node:assert/strict'
import { chromium, expect as baseExpect } from '$HOME/.cache/learning-workbench-acceptance/m63-session-interrupt-ui-oct05/apps/web/node_modules/@playwright/test/index.mjs'
const expect = baseExpect.configure({timeout:15000}), root='$HOME/.cache/learning-workbench-acceptance/m63-session-interrupt-ui-oct05', out=import.meta.dirname, head='22dade7996f13634202250ef5e1c05dc976214a5'
const sha=b=>createHash('sha256').update(b).digest('hex'), git=(...args)=>execFileSync('git',args,{cwd:root,encoding:'utf8',maxBuffer:16*1024*1024}).trim()
function inputs(){assert.equal(git('rev-parse','HEAD'),head);assert.equal(git('status','--porcelain'),'');const files={};for(const row of execFileSync('git',['ls-tree','-rz',head],{cwd:root,maxBuffer:16*1024*1024}).toString().split('\0').filter(Boolean)){const [meta,path]=row.split('\t');if(path.startsWith('progress/'))continue;const bytes=readFileSync(resolve(root,path)),[mode,type,oid]=meta.split(' ');assert.equal(createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex'),oid);files[path]={mode,type,git_blob:oid,sha256:sha(bytes),bytes:bytes.length}}return{head,count:Object.keys(files).length,files}}
const before=inputs();assert.equal(before.count,1525);writeFileSync(resolve(out,'before.json'),JSON.stringify(before,null,2)+'\n')
const tmp=process.env.TMPDIR;assert.ok(tmp.startsWith('$HOME/.cache/lwint22-'));chmodSync(tmp,0o700)
const data=mkdtempSync(resolve(tmp,'data-')),profile=mkdtempSync(resolve(tmp,'profile-'));writeFileSync(resolve(out,'private-paths.json'),JSON.stringify({tmp,data,profile},null,2)+'\n')
const socket=createServer();await new Promise((ok,no)=>{socket.once('error',no);socket.listen(0,'127.0.0.1',ok)});const port=socket.address().port;await new Promise(ok=>socket.close(ok));const origin=`http://127.0.0.1:${port}`
const env={...process.env,TMPDIR:tmp,LEARNING_DATA_DIR:data,LEARNING_PORT:String(port),LEARNING_HOST:'127.0.0.1',LEARNING_CODEX_EXECUTABLE:resolve(data,'missing-real-cli'),PYTHONPATH:`${out}:${root}`,PYTHONDONTWRITEBYTECODE:'1',NATIVE_STATIC_DIR:resolve(out,'dist')}
let api,browser;const calls=[],errors=[],facts={source:head,started_at:new Date().toISOString(),screenshots:[],assertions:[],actual_CLI:'NOT_RUN',actual_remote_model:'NOT_RUN',actual_tool_process:'NOT_RUN'}
const db='learning-workbench.codex-turn-commands.v1'
async function stored(page){return page.evaluate(name=>new Promise((ok,no)=>{const r=indexedDB.open(name,1);r.onerror=()=>no(Error('IDB open'));r.onsuccess=()=>{const d=r.result,t=d.transaction('drafts','readonly'),q=t.objectStore('drafts').getAll();q.onerror=()=>no(Error('IDB read'));q.onsuccess=()=>{ok(q.result.map(v=>JSON.parse(v.text)));d.close()}}}),db)}
async function panels(page){await page.getByRole('button',{name:'创作',exact:true}).click();const p=page.getByRole('region',{name:'Codex 回合准备与安全控制',exact:true});await p.getByRole('button',{name:'读取回合记录与权限',exact:true}).click();await expect(p.getByText('已读取本机记录；当前 session、回合与准备须分别显式读取。',{exact:true})).toBeVisible();await expect(p.getByLabel('回合原文',{exact:true})).toHaveCount(0);return p}
async function basis(p,sid,tid){await p.getByLabel('已建立的 session ID',{exact:true}).fill(sid);await p.getByRole('button',{name:'独立读取当前 session',exact:true}).click();await expect(p.getByRole('region',{name:'独立 GET 当前 session',exact:true})).toContainText(tid);await p.getByRole('button',{name:`读取回合控制 ${tid}`,exact:true}).click();const control=p.getByRole('region',{name:`当前回合控制 ${tid}`,exact:true});await expect(control).toContainText('awaiting_approval');await expect(p.getByRole('button',{name:`明确中断会话回合 ${tid}`,exact:true})).toBeEnabled();return control}
async function capture(page,region,label){for(const width of [1440,390]){await page.setViewportSize({width,height:900});await region.scrollIntoViewIfNeeded();const geometry=await page.getByRole('dialog',{name:'创作',exact:true}).evaluate(e=>({client:e.clientWidth,scroll:e.scrollWidth,viewport:innerWidth,document:document.documentElement.scrollWidth}));assert.ok(geometry.scroll<=geometry.client+1&&geometry.document<=geometry.viewport);const file=`${label}-${width}.png`;await page.screenshot({path:resolve(out,file)});facts.screenshots.push({file,sha256:sha(readFileSync(resolve(out,file))),geometry})}await page.setViewportSize({width:1440,height:900})}
const interrupts=()=>calls.filter(v=>/^POST \/api\/v1\/codex\/sessions\/[^/]+\/interrupt$/.test(v)).length
try {
 api=spawn(`${root}/.venv/bin/python`,['-B','-m','uvicorn','controlled_api:create_app','--factory','--host','127.0.0.1','--port',String(port),'--no-access-log'],{cwd:root,env,detached:true,stdio:['ignore','pipe','pipe']});let tail='';for(const s of [api.stdout,api.stderr])s.on('data',b=>{tail=(tail+b).slice(-8192)});let ready=false;for(let n=0;n<400;n++){if(api.exitCode!==null)throw Error('Owned fixture server exited: '+tail);try{if((await fetch(origin+'/health',{signal:AbortSignal.timeout(500)})).ok){ready=true;break}}catch{}await pause(50)}assert.ok(ready,'Owned loopback readiness')
 const fixture=JSON.parse(readFileSync(resolve(data,'private-fixture.json'),'utf8')), target=`/api/v1/codex/sessions/${fixture.session_id}/interrupt`
 browser=await chromium.launchPersistentContext(profile,{executablePath:'/usr/bin/google-chrome',headless:true,baseURL:origin,viewport:{width:1440,height:900}});await browser.addCookies(fixture.cookies);const page=browser.pages()[0];page.setDefaultTimeout(15000);page.on('dialog',d=>d.accept());page.on('pageerror',()=>errors.push('PAGE_ERROR'));page.on('request',r=>{const u=new URL(r.url());if(u.pathname.startsWith('/api/')){assert.equal(u.origin,origin);calls.push(`${r.method()} ${u.pathname}`)}})
 async function get(path){const r=await page.request.get(path);assert.equal(r.status(),200);return r.json()}
 async function post(path,body,key,status=200){const s=await get('/api/v1/session'),r=await page.request.post(path,{headers:{Origin:origin,'X-CSRF-Token':s.csrf_token,'Idempotency-Key':key},data:body});assert.equal(r.status(),status);return r.json()}
 await page.goto(origin);await expect(page.getByText('✓ UI 会话已保存',{exact:true})).toBeVisible();let p=await panels(page),control=await basis(p,fixture.session_id,fixture.turn_id)
 assert.equal((await get('/api/v1/session')).role,'learner');await capture(page,control,'learner-awaiting-safe-control')
 let lost
 await page.route(`**${target}`,async route=>{const req=route.request(),key=await req.headerValue('idempotency-key'),body=req.postDataJSON(),original=(await stored(page)).find(c=>c.command_id===key);assert.equal(req.method(),'POST');assert.ok(original);assert.equal(original.kind,'interrupt');assert.equal(original.actor_session_id,fixture.actor);assert.equal(original.workspace_id,fixture.workspace);assert.equal(original.session_id,fixture.session_id);assert.deepEqual(original.body,body);assert.deepEqual(body,{turn_id:fixture.turn_id,expected_session_revision:original.basis.session.revision});assert.equal(original.basis.session.active_turn_id,fixture.turn_id);assert.equal(original.basis.turn.id,fixture.turn_id);assert.equal(original.basis.turn.job.status,'awaiting_approval');assert.equal(original.ack,null);const r=await route.fetch();assert.equal(r.status(),200);lost={key,body,bodyText:req.postData(),original,ack:await r.json(),bytes:await r.body()};await route.abort('failed')},{times:1})
 await p.getByRole('button',{name:`明确中断会话回合 ${fixture.turn_id}`,exact:true}).click();await expect(p.getByText('操作结果或本机保存尚未确认；原命令和表单保留，不自动重发。',{exact:true})).toBeVisible();assert.ok(lost);assert.deepEqual(lost.ack,{id:fixture.session_id,turn_id:fixture.turn_id,status:'interrupt_requested'});assert.deepEqual((await stored(page)).find(c=>c.command_id===lost.key),lost.original)
 const terminal=await get(`/api/v1/codex/turns/${fixture.turn_id}`);assert.equal(terminal.job.status,'cancelled');assert.equal(terminal.execution,'terminal');assert.equal(terminal.outcome,'cancelled');assert.equal(terminal.started_at,null);assert.equal(terminal.cancel_requested,true)
 const prior=interrupts();await page.reload();await expect(page.getByText('✓ UI 会话已保存',{exact:true})).toBeVisible();p=await panels(page);assert.equal(interrupts(),prior);assert.deepEqual((await stored(page)).find(c=>c.command_id===lost.key),lost.original)
 const replayResponse=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname===target);await p.getByRole('button',{name:`显式回放回合原 key ${lost.key}`,exact:true}).click();const replay=await replayResponse;assert.equal(replay.status(),200);assert.equal(await replay.request().headerValue('idempotency-key'),lost.key);assert.equal(replay.request().postData(),lost.bodyText);assert.deepEqual(await replay.body(),lost.bytes)
 await expect(p.getByText('中断原 ACK 已保存；当前 session 与回合控制须分别独立 GET，中断请求不证明远端已停止。',{exact:true})).toBeVisible();const durable={...lost.original,ack:lost.ack};assert.deepEqual((await stored(page)).find(c=>c.command_id===lost.key),durable);await expect(p.getByRole('region',{name:'独立 GET 当前 session',exact:true})).toHaveCount(0)
 await p.getByLabel('已建立的 session ID',{exact:true}).fill(fixture.session_id);await p.getByRole('button',{name:'独立读取当前 session',exact:true}).click();await expect(p.getByRole('region',{name:'独立 GET 当前 session',exact:true})).toContainText('活动回合 无');await p.getByRole('button',{name:'读取安全回合分页',exact:true}).click();await expect(p.getByRole('region',{name:'安全回合分页',exact:true})).toContainText('cancelled');await p.getByRole('button',{name:`读取回合控制 ${fixture.turn_id}`,exact:true}).click();await expect(p.getByRole('region',{name:`当前回合控制 ${fixture.turn_id}`,exact:true})).toContainText('cancelled');assert.deepEqual((await stored(page)).find(c=>c.command_id===lost.key),durable);await capture(page,p.getByRole('region',{name:'回合原命令与历史 ACK',exact:true}),'durable-original-ack-independent-current')
 // The second still-unstarted turn creates a genuine competing session CAS.
 await post('/api/v1/session/role',{role:'author'},'native-second-author');const s=await get(`/api/v1/codex/sessions/${fixture.session_id}`)
 const prep=await post(`/api/v1/codex/sessions/${fixture.session_id}/turn-preparations`,{message:'Synthetic second awaiting turn; no execute.',context_refs:[],expected_session_revision:s.revision,provider_id:'codex_local',tools:{max_tool_calls:0,wall_seconds:30}},'native-second-preparation',202);assert.equal(prep.validity,'unavailable');await post('/api/v1/session/role',{role:'learner'},'native-second-learner')
 await p.getByRole('button',{name:'读取回合记录与权限',exact:true}).click();await expect(p.getByText('已读取本机记录；当前 session、回合与准备须分别显式读取。',{exact:true})).toBeVisible();await basis(p,fixture.session_id,prep.turn_id)
 const concurrent=await post(target,{turn_id:prep.turn_id,expected_session_revision:prep.session_revision},'native-explicit-competing-interrupt');assert.equal(concurrent.status,'interrupt_requested')
 const staleResponse=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname===target);await p.getByRole('button',{name:`明确中断会话回合 ${prep.turn_id}`,exact:true}).click();const stale=await staleResponse;assert.equal(stale.status(),412);await expect(p.getByText('版本已变化（412）；原 key、完整命令与只读基准保留。请独立读取当前状态。',{exact:true})).toBeVisible();const staleKey=await stale.request().headerValue('idempotency-key'),staleCommand=(await stored(page)).find(c=>c.command_id===staleKey);assert.equal(staleCommand.actor_session_id,fixture.actor);assert.equal(staleCommand.body.expected_session_revision,prep.session_revision);assert.equal(staleCommand.error.status,412);assert.equal(staleCommand.ack,null)
 const beforeCurrent=interrupts();await p.getByRole('button',{name:'独立读取当前 session',exact:true}).click();await expect(p.getByRole('region',{name:'独立 GET 当前 session',exact:true})).toContainText('活动回合 无');assert.equal(interrupts(),beforeCurrent);assert.deepEqual((await stored(page)).find(c=>c.command_id===staleKey),staleCommand)
 await page.reload();await expect(page.getByText('✓ UI 会话已保存',{exact:true})).toBeVisible();p=await panels(page);assert.equal(interrupts(),beforeCurrent);assert.deepEqual((await stored(page)).find(c=>c.command_id===staleKey),staleCommand)
 const staleReplayResponse=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname===target);await p.getByRole('button',{name:`显式回放回合原 key ${staleKey}`,exact:true}).click();const staleReplay=await staleReplayResponse;assert.equal(staleReplay.status(),412);assert.equal(await staleReplay.request().headerValue('idempotency-key'),staleKey);assert.equal(staleReplay.request().postData(),stale.request().postData());await expect(p.getByText('版本已变化（412）；原 key、完整命令与只读基准保留。请独立读取当前状态。',{exact:true})).toBeVisible();assert.deepEqual((await stored(page)).find(c=>c.command_id===staleKey),staleCommand)
 const all=await stored(page),count=interrupts();await browser.clearCookies();await browser.addCookies(fixture.cookies_b);await page.reload();await expect(page.getByText('✓ UI 会话已保存',{exact:true})).toBeVisible();p=await panels(page);assert.equal((await get('/api/v1/session')).actor_session_id,fixture.actor_b);assert.equal(interrupts(),count);assert.deepEqual(await stored(page),all);await expect(p.getByRole('button',{name:`显式回放回合原 key ${staleKey}`,exact:true})).toBeDisabled();await expect(p.getByText('其他 actor 的安全控制记录只读；不能接管或重放。',{exact:true})).toHaveCount(2);await capture(page,p.getByRole('region',{name:'回合原命令与历史 ACK',exact:true}),'new-actor-original-command-isolated')
 assert.equal(interrupts(),4);assert.deepEqual(errors,[]);assert.equal(calls.filter(v=>v.startsWith('POST ')&&!v.endsWith('/interrupt')).length,0);const sentinels=JSON.parse(readFileSync(resolve(data,'sentinels.json'),'utf8'));assert.deepEqual(sentinels.counts,{codex_executor:0,provider_transport:0,literal_operation:0,later_bootstrap:0});assert.equal(sentinels.executor_none,true);assert.equal(sentinels.synthetic_bootstrap_calls,1);assert.equal(sentinels.phase,'lifespan-entered');facts.sentinels=sentinels
 const after=inputs();assert.deepEqual(after,before);writeFileSync(resolve(out,'after.json'),JSON.stringify(after,null,2)+'\n');facts.status='CONTROLLED_SESSION_INTERRUPT_UI_NATIVE_PASS';facts.finished_at=new Date().toISOString();facts.before_after_exact=true;facts.complete_nonprogress_inputs=before.count;facts.calls=calls;facts.browser_ui_interrupt_requests=interrupts();facts.separate_fixture_competing_interrupt_requests=1;facts.first_original_ack_sha256=sha(lost.bytes);facts.browser=await browser.browser().version();facts.assertions.push('learner safe GET basis; IDB original actor/full body/key/basis before real POST; awaiting turn actually cancelled; actual200 ACK deliberately lost; reload zero automatic POST; explicit same-key byte-exact body and original full ACK; independent current GET does not overwrite ACK; real stale session CAS412 retained across reload and explicit unchanged replay; new actor cannot replay original unknown command');facts.boundary='Real Chrome/loopback HTTP/SQLite/IndexedDB; pure-memory bootstrap1, two unavailable-proof awaiting preparations, no Provider grant/start/model or physical CLI/tool execution. Sentinel counts are named application seams, not general OS/network monitoring.';writeFileSync(resolve(out,'receipt.json'),JSON.stringify(facts,null,2)+'\n');console.log(facts.status)
} catch(e) {writeFileSync(resolve(out,'failure.json'),JSON.stringify({source:head,name:e.name,message:e.message,at:new Date().toISOString()},null,2)+'\n');throw e}
finally {writeFileSync(resolve(out,'terminal-source.json'),JSON.stringify(inputs(),null,2)+'\n');await browser?.close();if(api?.pid){const exit=new Promise(ok=>api.once('close',ok));try{process.kill(-api.pid,'SIGTERM')}catch(e){if(e.code!=='ESRCH')throw e}let timer;await Promise.race([exit,new Promise(ok=>{timer=setTimeout(()=>{try{process.kill(-api.pid,'SIGKILL')}catch(e){if(e.code!=='ESRCH')throw e}ok()},5000)})]);clearTimeout(timer)}writeFileSync(resolve(out,'terminal-sentinels.json'),existsSync(resolve(data,'sentinels.json')) ? readFileSync(resolve(data,'sentinels.json')) : JSON.stringify({status:'NOT_AVAILABLE_STARTUP_NOT_REACHED'}))}
